### ISSUE TITLE
[Qt 5.9] Dock overlaps plasma menus

### ISSUE THREAD

**Issue by valeth** [psifidotos/Latte-Dock#551] opened 2017-06-17 14:46 UTC
The dock overlaps other plasmoids like the application menu.
It also overlaps the panel if the aligment is set to "justify".

The dock visibility is set to Dodge Maximized.

![screenshot_20170617_163934](https://user-images.githubusercontent.com/3198362/27253809-b9147b2c-537b-11e7-85e7-6a4f533f39a8.png)

Qt: 5.9.0
Plasma: 5.10.2
Frameworks: 5.35.0
Latte Dock: git master

**Comment by psifidotos** [comment] 2017-06-17 14:58
Tweaks page, check the option, Behave as a regular dock window

does this fix the app menu issue? For the plasma panel i dont think you can do something else except replacing it with a second latte dock instance

**Comment by valeth** [comment] 2017-06-17 15:35
All this does is segfault the dock when exiting the settings menu.
```
[12911.574778] latte-dock[809]: segfault at 98 ip 00007f7f0e68cea2 sp 00007ffc2f7237c8 error 4 in libQt5Quick.so.5.9.0[7f7f0e4b3000+422000]
[12954.960615] traps: latte-dock[4522] general protection ip:7fc3dbe54ead sp:7fff9bafb8d8 error:0 in libQt5Quick.so.5.9.0[7fc3dbc7b000+422000]
```

**Comment by valeth** [comment] 2017-06-17 15:43
Here's a GDB backtrace, some symbols are stripped unfortunately, because Arch Linux packages come without them by default.
https://gist.github.com/valeth/60dffecdea0763cab46f7703a8f66844#file-latte-dock-gdb-backtrace001-txt

**Comment by psifidotos** [comment] 2017-06-17 15:55
looks like we found a way to reproduce #548

After crash isnt latte starting? It segfaults?

**Comment by valeth** [comment] 2017-06-17 15:57
Yes, it segfaults, no automatic restarts after that.

**Comment by psifidotos** [comment] 2017-06-17 15:59
Lets welcome then the Qt 5.9 crashes... The nrxt days i will also update and see what is going on...

**Comment by psifidotos** [comment] 2017-06-17 18:46
@valeth I have just update to qt 5.9 in tumbleweed and this crash can not be reproduced... 
please save your layout and try with the default one to check if the crash occurs again...

**Comment by valeth** [comment] 2017-06-18 18:46
@psifidotos It's not crashing with default settings, and enabling this options seems to solve the issue with the overlapping plasma menu.

**Comment by psifidotos** [comment] 2017-06-18 19:27
In such case it is an applet or a specific setting... you could try to add your applets one by one and activate your previous settings one by one in order to find what creates that crash

**Comment by valeth** [comment] 2017-06-18 19:30
The only changes I made were removing the clock widget and pinning more launchers to the dock.

I already re-added them one-by-one while enabling and disabling this options to see if any crashes occur. Nothing crashed so far.

**Comment by psifidotos** [comment] 2017-06-18 20:18
Did you update any of your packages, especially qt, plasma or kde frameworks?

**Comment by valeth** [comment] 2017-06-18 20:41
Only thing I did lately was installing flatpak, which triggered an initramfs update.
No updates of any other packages though.

**Comment by psifidotos** [comment] 2017-06-18 20:59
ok... I close this until we find something more concrete... there is still #548 which can help us track this down..

**Closed by psifidotos** 2017-06-18 20:59 UTC
