### ISSUE TITLE
KDE Frameworks 5.32: Dock's background visible after hiding

### ISSUE THREAD

**Issue by himanshub16** [psifidotos/Latte-Dock#292] opened 2017-03-20 15:07 UTC
![image](https://cloud.githubusercontent.com/assets/14041572/24105940/8493f7fc-0dac-11e7-8812-9175d63b1cac.png)
The orange background takes space uselessly. It was not the case until I updated my system today (KDE Neon). I've also updated Latte dock with the master branch as of now 20 March 8:37 PM IST.

**Comment by psifidotos** [comment] 2017-03-20 15:48
Are you in **not compositing** state? This background is shown only in such case and only for editing mode (when showing the settings window)... 

How did you achieve this screenshot?

**Comment by himanshub16** [comment] 2017-03-20 16:04
I don't know about **compositing state**. With 'print screen' key, and 'Spectacle : They screenshot tool'. It just started normal. I even restarted it sometimes. When you open Latte Settings, the background becomes light-blue, but later on it's the same as in the screenshot.

I tried debug from the terminal. Here's the dump.
```
[debug 21:32:46.922922] - package is valid true
[debug 21:32:46.922922] - connector : "eDP-1"  -  "10"
[debug 21:32:46.922922] - Known Screen -  "eDP-1"  -  10
[debug 21:32:46.923923] - Latte::DockCorona the package QJsonObject({"KPlugin":{"Authors":[{"Email":"mvourlakos@gmail.com, audoban@openmailbox.org","Name":"Michail Vourlakos, Smith Ar"}],"Description":"Shell provided for the Latte Dock","Id":"org.kde.latte.shell","License":"GPLv3+","Name":"Latte Shell","ServiceTypes":["Plasma/Shell"],"Version":"0.5.91","Website":"https://github.com/psifidotos/Latte-Dock"},"Keywords":"shell","X-KDE-ParentApp":"latte-dock"}) is valid!
[debug 21:32:46.925925] - containment values:  true  -  -1
[debug 21:32:46.925925] - TASKS WILL BE PRESENT AFTER LOADING :::  true
[debug 21:32:46.970970] - add dock - containment id :  -1
[debug 21:32:46.970970] - Adding dock for container...
[debug 21:32:46.970970] - onPrimary:  true screen!!! : -1
[debug 21:32:47.2121] - adapting to screen...
[debug 21:32:47.5151] - SOURCE: QUrl("/usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml")
[debug 21:32:47.5252] -   Delayer  
[debug 21:32:47.5252] -       D, found screen:  "eDP-1"
[debug 21:32:47.5252] - dock screen exists  :::  true
[debug 21:32:47.5757] - QMap(("activityId", "")("formfactor", "2")("immutability", "1")("lastScreen", "-1")("location", "4")("plugin", "org.kde.latte.containment")("raiseOnActivityChange", "false")("raiseOnDesktopChange", "false")("timerHide", "700")("timerShow", "200")("visibility", "2")("wallpaperplugin", "org.kde.image"))
[warning 21:32:47.335335] - Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
[debug 21:32:47.589589] - ----------- Latte Plasmoid Signal: Activities number was changed ---------
[debug 21:32:47.589589] - 29557b3a-5c6c-49fd-922f-d04d73a018f6
[debug 21:32:47.589589] - ----------- Latte Plasmoid Signal End ---------
[warning 21:32:47.607607] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/main.qml:151:42: Unable to assign int to QObject*
[warning 21:32:47.920920] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:168:41: Unable to assign int to QObject*
[warning 21:32:47.920920] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1282: TypeError: Cannot read property 'visibility' of null
[warning 21:32:47.920920] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1257: TypeError: Cannot read property 'visibility' of null



^C[debug 21:32:50.492492] - Destroying Latte Dock Containment ui...
[debug 21:32:50.594594] - dock containment destroyed!!!!
[debug 21:32:50.623623] - dock view deleting...
[debug 21:32:50.623623] - VisibilityManager deleting...
[debug 21:32:50.623623] - VisibilityManagerPrivate deleting...
[debug 21:32:50.628628] - Latte::QuickWindowSystem destructed
[warning 21:32:50.636636] - "There are still \"-1\" items in the process of being created at engine destruction."
[debug 21:32:50.639639] - deleted Latte::DockCorona(0x7ffdbb4f1690)
x window interface deleting...
```

**Comment by psifidotos** [comment] 2017-03-20 18:45
> I don't know about compositing state. 

this is when you dont have animations and transparency for your windows... is that the case for you ?

Could you try to remove your build directory inside Latte and install from the begin clean in order to be sure?

**Comment by psifidotos** [comment] 2017-03-20 18:46
also you can run latte with:

**latte-dock -d --with-window**
this will appear a debug window, make a screenshot of it when the problem appears...

**Comment by ToastyYogurtTime** [comment] 2017-03-20 23:55
I've been having a similar problem since the update that was meant to fix the problems I was having with the dock while compositing was disabled. The dock hides now while compositing is off, but now I get a similar annoying background covering any space the dock is allowed to occupy at any given time.
![2017-03-20_18 40 21](https://cloud.githubusercontent.com/assets/14959006/24126689/4bfee15e-0d9d-11e7-8f01-f161b19f483f.png)
![2017-03-20_18 40 57](https://cloud.githubusercontent.com/assets/14959006/24126690/4bffc6a0-0d9d-11e7-99c1-d1beeb41250a.png)
I should mention that I have the dock's maximum length set to 95%, which is why this background doesn't stretch across the entire height of the screen.

As for fixing it, would it be possible to do any of the following while compositing is disabled?

- Set visibility to "always visible."
- Set the dock to be below all windows. (This works for my purposes, as I just don't want it to block anything while compositing is disabled)
- Set the dock to always be drawn on screen, but only appear above windows when the cursor hits its edge of the screen. (Similar to Plasma's "Windows Can Cover" setting for panels, would be the most useful for those that don't use compositing at all.)

**Comment by audoban** [comment] 2017-03-21 02:25
@psifidotos, I think it would be best to remove the beige background.

**Comment by psifidotos** [comment] 2017-03-21 05:14
@audoban, this is a bug... if i remove this then at its place will be a black box. I asked for the,

latte-dock -d --with-window

nothing will be touched until bug reporters follow the guidelines... impatience wont drive development...

**Comment by psifidotos** [comment] 2017-03-21 05:30
@audoban to give a nint, this is also an indicator that mask does not work as it should under !compositing at some cases.

The orange background loads with:

```
    //! Load a sepia background in order to avoid black background
    Loader{
        anchors.fill: parent
        active: !Latte.WindowSystem.compositingActive
        sourceComponent: Image{
            anchors.fill: parent
            fillMode: Image.Tile
            source: "../icons/sepiaprint.jpg"
        }
    }
```

so, it should appear only at !compositing state an in order to show the black background of the window which is very ugly...

**Comment by audoban** [comment] 2017-03-21 05:58
@psifidotos, ok no problem. With respect to bug, the problem is related then with KWin or maybe with the graphics?

**Comment by pinoh** [comment] 2017-03-21 06:23
@psifidotos I've same issue, see log in attachment. My Latte's configuration is vanilla/untouched.


[latte_log.txt](https://github.com/psifidotos/Latte-Dock/files/857224/latte_log.txt)

**Comment by audoban** [comment] 2017-03-21 06:47
@psifidotos The mask appears to be correct.

**Comment by psifidotos** [comment] 2017-03-21 07:46
I want the screenshot of the debug window,

@audoban does it occur also to you?

**Comment by psifidotos** [comment] 2017-03-21 07:51
The ishidden flag says no but the tasks are hidden..

**Comment by psifidotos** [comment] 2017-03-21 07:52
I want the screenshot of the debug window,

@audoban does it occur also to you?

If you show the configuration window and after that close it, what happens?

**Comment by psifidotos** [comment] 2017-03-21 08:01
@audoban We want a way to reproduce this... it doesnt happen in my system

@pinoh
when you change settings... visibility mode etc... what happens?
when you load latte is everything ok?
How do you reproduce at your system?

**Comment by pinoh** [comment] 2017-03-21 10:01
> @audoban We want a way to reproduce this... it doesnt happen in my system
I'm on Antergos (Arch).

@psifidotos 
> when you change settings... visibility mode etc... what happens?
The orange background is still here, no matter what settings I change.

> when you load latte is everything ok?
Yes, it is.

> How do you reproduce at your system?
Simply by starting `latte-dock`.

**Comment by psifidotos** [comment] 2017-03-21 10:14
@pinoh I suppose you are running at a not compositing system, right?

> > when you load latte is everything ok?
> Yes, it is.

can you make a screenshot how does it look when you start and everything is ok and also the debug window in that case?

**Comment by psifidotos** [comment] 2017-03-21 10:17
@pinoh did I understand correct that when latte starts in no compositing state it looks ok and when it hides itself the issues is appearing? 

@pinoh when everything works ok at startup and you hover over tasks, what happens in that case?

**Comment by mstraube** [comment] 2017-03-21 10:35
> We want a way to reproduce this... it doesnt happen in my system

I can reproduce it by deactivating the compositor in Plasma settings and then just start latte-dock.
It shows the beige background on startup. I'm on Arch Linux.

Would a screenshot of the debug window and/or terminal output be helpful?

**Comment by psifidotos** [comment] 2017-03-21 11:33
a screenshot of the debug window and how latte looks on startup...

**Comment by mstraube** [comment] 2017-03-21 12:47
![latte](https://cloud.githubusercontent.com/assets/20053197/24147932/cd249d74-0e3c-11e7-973f-b4520c39063f.png)

**Comment by pinoh** [comment] 2017-03-21 13:03
@psifidotos 
> @pinoh I suppose you are running at a not compositing system, right?

Uh? I have KWin.

> @pinoh did I understand correct that when latte starts in no compositing state it looks ok and when it hides itself the issues is appearing?

Sorry, I meant everything else was/is ok, I misunderstood the question.

However, I removed Latte (the GitHub's release) and then I reinstalled it by AUR. Now I have the strange behaviour in pic, plus when mouse is over the dock Latte crash by "segmentation fault". I've tried a `make clean` and then reinstalling it. Do I have to open another issue?
![spectacle j30426](https://cloud.githubusercontent.com/assets/7703116/24148222/268fc482-0e3e-11e7-9a85-6755ab033d73.png)

**Comment by psifidotos** [comment] 2017-03-21 13:29
@mstraube please try to change your theme to something else from defaults...

@pinoh as long as you are using Antergos there is #268

**Comment by mstraube** [comment] 2017-03-21 14:34
I tried different settings for look-and-feel (Arc Dark, Maia, ElPlas) and desktop-theme (Arc, Air, Maia, Oxygen). The only one that makes a difference is when the desktop-theme is oxygen.

![latte-oxygen](https://cloud.githubusercontent.com/assets/20053197/24152355/ad5a8206-0e4b-11e7-94c6-5f096ec631ed.png)

**Comment by psifidotos** [comment] 2017-03-21 16:22
@mstraube I have another idea.... make sure you have compositing enable and choose from your latte settings- -> appearance -> solid background

does a background appears in such case ?

**Comment by audoban** [comment] 2017-03-21 17:29
@psifidotos   maybe is related with the flag Bypassmanagerwindowhint?

**Comment by psifidotos** [comment] 2017-03-21 17:38
@audoban I found it... this is definitely a KDE Frameworks 5.32 issue... they changed things and many warnings not appearing from FrameSVG:

`The image "widgets/scrollbar" doesn't contain any of the prefixes ("background-horizontal")`

it could be related to: ` [FrameSvgItemMargins] Don't update on repaintNeeded`

**Comment by psifidotos** [comment] 2017-03-21 17:54
my patience is starting ending...

**Comment by psifidotos** [comment] 2017-03-21 18:27
bug kde: https://bugs.kde.org/show_bug.cgi?id=377893

**Comment by psifidotos** [comment] 2017-03-21 18:33
@himanshub16 @mstraube  do observe that this is plasma fault... use a plasma theme that has rounded corners,  add a regular plasma panel and go to no compositing state... You will see that no more rounded corners are appearing at !compositing state...

**Comment by psifidotos** [comment] 2017-03-21 18:37
@audoban I believe that before adding a workaround to at least have a normal panel without rounded corners we should wait a bit to see that plasma developers consider of this...

this breaks also our solid background feature... if plasma developers dont want to fix this, this feature can only be dropped...

**Comment by mstraube** [comment] 2017-03-21 18:54
Arc window decoration:
![arc-latte](https://cloud.githubusercontent.com/assets/20053197/24165131/e1d1e3c0-0e6f-11e7-806c-fb334f458469.png)

Plasma panel with Oxygen desktop-theme:
![oxygen-latte](https://cloud.githubusercontent.com/assets/20053197/24165231/272d851e-0e70-11e7-8a53-dd96c51bdb29.png)

**Closed** 2017-03-21 19:01 UTC
Labels: reported!, upstream

**Comment by psifidotos** [comment] 2017-03-21 19:02
this patch will make your life a bit easier in !compositing but dont expect rounded themes to look good for !compositing. This can only be fixed by plasma developers in frameworks...

**Comment by psifidotos** [comment] 2017-03-22 13:36
Fixed in plasma frameworks master branch... KF 5.33 wont have this issue at all, and those using unstable branches should get the plasma fix in the next days and have rounded corners for !compositing

**Comment by himanshub16** [comment] 2017-03-22 14:44
@psifidotos Thanks
