### ISSUE TITLE
Not needed extra space beside the latte dock

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#113] opened 2017-01-30 14:39 UTC
I think one of the latest commits introduced extra space beside the latte dock (see screenshot below).

![image](https://cloud.githubusercontent.com/assets/3875196/22427024/833d2788-e6cf-11e6-817f-701ecacc09ec.png)

Not sure if that extra space may be needed/useful while zooming on hover, but when zoom is not used (like here), it basically wastes screen space.

Also, weirdly enough, there is text (from active window control) that is somehow copied down in that extra space. This doesn't happen always, it is only triggered when using krunner to open an application (which I do frequently).

I tested with active window control in a regular panel and this does not occur, neither it did (at least I didn't realize) until this extra space was introduced.

**Comment by psifidotos** [comment] 2017-01-30 17:46
have you tried to reduce your icon size?

**Comment by psifidotos** [comment] 2017-01-30 17:56
this is my latest system....
you see all Latte...
at the top the new 3layouts for Fill mode, left, center,right. I am using iconsize: 24, background size: 20, always visible mode,

tested with both breeze dark and arc dark themes...

![latte3lays](https://cloud.githubusercontent.com/assets/2216474/22434713/d772677c-e725-11e6-90f5-3526d62268b4.png)

**Comment by kupiqu** [comment] 2017-01-30 18:02
I tried, but the issue is indep of the icon size (also I think 32 px in my system look very similar to 24 px in yours, 24 is way too small for my screen).

It is weird that you are not finding the issue. I'll try to identify the commit that made the change...

**Comment by psifidotos** [comment] 2017-01-30 18:09
the commit is just the new calculations which it can not be reverted back because it fixes so many wrong calculations all around for configuration window positioning and at many more places...

The issue is that latte dock uses both iconsize and panel thickness in order to provide the correct thickness for everything... The maximum value is used... Also Latte can not know how the applets are rendering their contents and it doesnt know if the panel thickness set by the user is enough for these contents..

If you increase you panel thickness from your configuration window this might be fixed...

Another solution could be the user to choose from the configuration window to force the panel's thickness instead of the iconSize one...

**Comment by kupiqu** [comment] 2017-01-30 18:19
Indeed, I found commit 25f4de2f5cdd9f8d8f1714cfe971abd963d608df was the one that introduced the issue for me, which I think it is the one that you are describing.

What you mean by panel thickness from configuration window, do you refer to the size of the panel background?

Perhaps this "another solution" you mentioned would work better? I think you meant to specify how wide is the panel so icons scale themselves to it. Is that right?

**Comment by psifidotos** [comment] 2017-01-30 20:41
this is in my system with: iconsize:32, panel background: 28, zoom factor:1.0
as you can see snapping works just fine for me even with lower background size than iconsize, the mentioned space appears for me below panel background 26px ...

what are your settings?

![calcsnew](https://cloud.githubusercontent.com/assets/2216474/22440623/f94606a8-e73c-11e6-90a1-a5274da1e586.png)

**Comment by kupiqu** [comment] 2017-01-30 20:46
may the issue depend on the screen size? mine is 2560x1440

my settings (I played with them, some larger, some smaller, but didn't find any that would work in my system): iconsize 32, panel background 30, zoom factor 1

**Comment by psifidotos** [comment] 2017-01-30 20:48
have you tried to increase the panel background above 32?

**Comment by kupiqu** [comment] 2017-01-30 20:49
yes (64), but I just did it again for 40 and 48, and the same happens :/

**Comment by psifidotos** [comment] 2017-01-30 20:50
no the icon size!!! the panel background size!

**Comment by kupiqu** [comment] 2017-01-30 21:02
I see, actually increasing the size of panel background makes it worse (the most I can go is 36).

Actually the behavior is a bit weird:

if I reduce background from let's say 30 to 24, things get better but there is still a bit of a gap. If I then disable the background, then this gap disappears.

However, if I disable the background that was set to 30, then the gap is reduced but not entirely disappears.

**Comment by kupiqu** [comment] 2017-01-30 21:04
So, in other words, the effect of disabling the background depends on the size it had when it was enabled.

**Comment by psifidotos** [comment] 2017-01-30 21:06
what theme are you using?

because you have a high dpi screen, did you have any issues with your fonts ?

**Comment by kupiqu** [comment] 2017-01-30 21:09
I force fonts to be 144 dpi

I use breeze dark for plasma, should I try breeze?

**Comment by psifidotos** [comment] 2017-01-30 21:11
no, the theme is just fine...

i am at channel #latte-dock in irc, I think something is going on with how you have set your fonts...

**Comment by psifidotos** [comment] 2017-01-30 21:11
what is your regular font size from your plasma system settings ?

**Comment by psifidotos** [comment] 2017-01-30 21:21
this how your Latte settings look in my system..
also, I am using resolution:1680x1050, regular font size: 11, 96 dpi

![calcsnew2](https://cloud.githubusercontent.com/assets/2216474/22442102/c131b98c-e742-11e6-8e74-6d5493abace8.png)

**Comment by kupiqu** [comment] 2017-01-30 21:23
In my system I use Nimbus Sans L 10. Plasma I think uses the same

I don't use irc, sorry. I guess I could set it up. But this would need to be tomorrow, as I have to leave my computer in about 20 min.

**Comment by psifidotos** [comment] 2017-01-30 21:30
these settings worked ok in my system...
I noticed also that changing the dpi the interface changes accordingly!!!
you could try to play with your dpi, does this behave the same ?

**Comment by kupiqu** [comment] 2017-01-30 21:39
I don't know, this issue may be related to high dpi in plasma. I tried what you said of playing with dpi, but it doesn't seem to help.

It would be good to see how other people with high dpi monitors experience this, if at all.

**Comment by psifidotos** [comment] 2017-01-30 21:48
yep... good idea... otherwise we will schedule a meeting in irc in order to fix this for you...

**Comment by psifidotos** [comment] 2017-01-31 10:22
I will try to create a new implementation for calculations tonight and create a branch called fix113 to test when it is ready... if this doesnot work in the end then after we can still try to implement a reverse icon size setting, the icon size(in steps of 8 of course) will be set by the panel background size

**Comment by kupiqu** [comment] 2017-01-31 10:57
:+1: 

Sounds great!

**Comment by psifidotos** [comment] 2017-01-31 15:47
@kupiqu I created branch **fix113** , includes more improvements in ways the shadows and mask are calculated...

**BUT**

I just realized that the issue you are reporting concerns **snapping** (that is moving a window near the dock and how that window snaps near the dock), in that case the gap you see is because of the shadows shown for that panel.

**on the other hand**

if you try to maximize a window that gap should exist because the struts of dock window are calculated correctly...

what is your case?

**Comment by kupiqu** [comment] 2017-01-31 16:04
Re fix113: it improves the situation significantly, the gap is now reduced to less than half the previous :)

Re snapping: it makes sense. Varying the amount of pixels to snap does not seem to change anything though.

Re maximize: Indeed, it does not happen for maximized windows. However I use dodge maximized, which I think it's a neat feature of latte dock, btw :)

**Comment by psifidotos** [comment] 2017-01-31 17:19
ok, at least now we know that the calculations are correct also to your system...

> Re snapping: it makes sense. Varying the amount of pixels to snap does not seem to change anything though.

this has nothing to do with the snap amount of pixels. This has to do with the fact that the panel's shadows are drawn inside our window. Plasma in order to overcome this, it calls X and Wayland draw functions to draw these shadows. But Plasma doesnt have animated panels that grow and semi-transparent panels that their shadows are below the panel's contents.

They only way this could be solved is to immitate the plasma behavior for very specific cases and only these... This should be only in the case of:

- Fill mode, zoom factor:1.0,  Always Visible

in this case it makes sense to implement, for all the rest it would be very difficult to synchronize correctly these shadows draws with the Latte's animations. Of course this increases a lot the complexity in our c++ code and I dont know if it is that important to have that mechanism at hand... I will try to implement it and test it at an alternative branch but I can not guarantee anything...

**Comment by kupiqu** [comment] 2017-01-31 18:54
Perhaps it is just fine the way it currently is...

Naive question, is there an easy way to disable shadows in plasma? Could this be added as an option to latte-dock?

Right now, more than for the extra space, which is minor, I am annoyed by the fact that text in active window control is somehow projected into the panel's shadow (take a close look to the first screenshot above). This is the main concern I have right now...

**Comment by kupiqu** [comment] 2017-01-31 18:56
To be clear, I don't think this text projection is latte's fault at all. I don't know where it comes from, actually, but it is a bit annoying and would love to somehow fix it...

**Comment by psifidotos** [comment] 2017-01-31 19:37
> Naive question, is there an easy way to disable shadows in plasma? Could this be added as an option to latte-dock?

yes, this can be added easily, disable shadows for the panel background but it looks a bit weird...

> Right now, more than for the extra space, which is minor, I am annoyed by the fact that text in active window control is somehow projected into the panel's shadow (take a close look to the first screenshot above). This is the main concern I have right now...

I dont know why this is happening to you, the weird thing is that text window not only creates two lines but that exceeds the space provided from Latte for it.
Is this still the same with latest Latte? Can you upload a screenshot based on last master?

a guess from me is that it could be an issue with high resolution screen and dpi settings... Try to use the same widget with regular panel and play with panel's height but dont set fillWidth use the same settings you use with Latte... If this happens also to plasma panel then weird situation...

**Comment by kupiqu** [comment] 2017-01-31 20:25
> yes, this can be added easily, disable shadows for the panel background but it looks a bit weird...

Oh, does it?

> I dont know why this is happening to you, the weird thing is that text window not only creates two lines but that exceeds the space provided from Latte for it.
Is this still the same with latest Latte? Can you upload a screenshot based on last master?

Not sure it is a second line. I'll play a bit with the source code of active window control to see if I can find sth out. I tried to replicate the behavior in default plasma panel before but couldn't

**Comment by kupiqu** [comment] 2017-01-31 20:55
> If this happens also to plasma panel then weird situation...

Unfortunately, with plasma panel there is no way to see if text is duplicated as well, as the little extra space (due to snapping) does not appear and then the effect is invisible (I only realized about the issue in the context of the gap).

**Comment by kupiqu** [comment] 2017-01-31 21:25
Reducing a bit the fontsize in active window control 'fixed' the issue for me:

with a scale factor <=0.93

**Comment by psifidotos** [comment] 2017-01-31 21:50
how did you manage to set scale factor<= 0.93? I thought the minimum was 1.0 and the maximum 2.0

**Comment by kupiqu** [comment] 2017-01-31 22:39
Exactly, but just hardcoded for active window control

**Comment by psifidotos** [comment] 2017-02-01 23:04
@kupiqu I dont know if this will ever be merged in master but you can try **_snapping_** branch. I contains the fix for the gap and snapping you mentioned. 
To compile it you need also x11, xcb and kwayland development packages

it works only for docks that the user has set: 
**Always Visible, zoom factor:1.0, maximum panel size, Justify alignment**

**Comment by kupiqu** [comment] 2017-02-01 23:16
I think I may have been asking too much to latte dock. All issues seem to appear related to the panel that does not include the task bar, so perhaps a regular plasma panel for that is just what I should use. What do you think?

for sure I am going to keep latte for the other panel, which includes the latte task bar

**Comment by psifidotos** [comment] 2017-02-01 23:25
Personally I will stay with Latte solution fot a little while. It was advance to provide but in the end playing with it, provides a beautiful experience...

We will discuss it as a team and observe if it is needed or not to add that part in our code...

**Comment by kupiqu** [comment] 2017-02-02 00:55
Yeah, I agree, latte experience is great, e.g. the dodge options (just one feature that I love... Actually, dodge options would be very nice to have upstream in plasma too)

**Comment by psifidotos** [comment] 2017-02-02 01:06
I wasnt refering in general, i was refering also at the snapping branch, it works very nice in my system... i like a lot when i drag a window near the top bar and the top bar sticks automatically the edges of the two windows... it fixed also for me the centered applets in Justify alignment... with plasma this doesnt work always correctly to put two spacers to center an applet

**Comment by psifidotos** [comment] 2017-02-02 21:51
for this issue someone could test the **_snapping_** branch....

**Closed by psifidotos** 2017-02-02 21:51 UTC
Labels: needsinfo

**Comment by kupiqu** [comment] 2017-02-03 02:30
Sorry, I didn't have time to try this out. I'm curious about the feature you explained (not sure I got it 100% though). I may give it a try...

On a different vein, I recently updated to plasma 5.9 (kde neon), which included an update to Qt 5.7.1. This update seems to have fixed the issue of text duplication :)

**Comment by kupiqu** [comment] 2017-02-03 02:48
I just tried it (the only missing library was wayland, I guess I already had the other two for other applets).

In my system the gap is still present, but anyway, please do not spend more time on this, unless you think this may be worth for other people as well (the default plasma panel covers my current needs for a top panel).

As said, I will use latte for my side panel, which includes the latte applet :)

**Comment by psifidotos** [comment] 2017-02-03 16:55
@kupiqu unfortunately this small issue opened a good discussion concerning this technology and it appears that we want to support it. It will enable us to support shadows better in some corner cases...

there is some work in snapping branch if you want to give it one more ride... the panel size must be >= icon size in order for this to be triggered active...

**Comment by psifidotos** [comment] 2017-02-03 18:38
@kupiqu this is merged in master!!

**Comment by kupiqu** [comment] 2017-02-03 20:35
It is nice indeed! 

The only issue I'm currently having that makes me hesitate to come back to latte for the top panel is on automatizing the space for active window control.

Would you know of any trick I could use within the applet to adjust its size properly for the latte dock (when using justified alignment)?

**Comment by psifidotos** [comment] 2017-02-03 23:59
> for the top panel is on automatizing the space for active window control. Would you know of any trick I could use within the applet to adjust its size properly for the latte dock (when using justified alignment)?

you mean that the applet should change its length based on the available free space in latte ?

**Comment by kupiqu** [comment] 2017-02-04 00:24
Yes, but I am aware this may not be that easy. 

I am quite happy now with another layout that does not require this. please see screenshot in https://github.com/psifidotos/Latte-Dock/issues/126

**Comment by psifidotos** [comment] 2017-02-04 00:29
ok!

**Comment by psifidotos** [comment] 2017-02-04 00:29
your new layout it looks like a lot like mine now... :)

**Comment by kupiqu** [comment] 2017-02-04 00:37
cool!
