### ISSUE TITLE
Launchers disappear briefly while the application is starting

### ISSUE THREAD

**Issue by mooop12** [psifidotos/Latte-Dock#353] opened 2017-04-03 11:38 UTC
When starting any app from the dock the apps icon disappears briefly until the apps window is shown.

**Comment by psifidotos** [comment] 2017-04-03 14:01
I just used Latte under Plasma 5.8 and this occurs almost always... in my plasma 5.9 the situation is not optimal but it behaves ok with most of the launchers...

I have responded so many times concerning this, that I will describe the situation here and leave this open to forward users ....

The main issue is with plasma libtaskmanager, you can read more at: #72 

at the same time the fact that Latte 0.6 is supporting two different versions of libtaskmanager (one for 5.8 and one for 5.9) does not help at all... any workarounds that we add for one version break the behavior on the other and vice versa... you can read more at: #343 

so this is based mainly on plasma libtaskmanager behavior but Latte doesnot help this situation by just supporting one version of libtaskmanager and adding only the workarounds that improve the relevant experience...

**Comment by mooop12** [comment] 2017-04-03 14:21
Sorry, I guess I really am bad at searching :)

I just disabled all animations like you mentioned in the other issue, as I'd rather have no animations at all than have a constantly shrinking and expanding dock. Hope upstream will fix this soon.

**Comment by psifidotos** [comment] 2017-04-10 07:43
@mooop12 there is a chance that #343 which is inside the **launchers59** fixes this ...

**Comment by mooop12** [comment] 2017-04-10 12:10
Unfortunately, this didn't seem to fix the issue for me, and I'm using Plasma 5.9.4.

**Comment by psifidotos** [comment] 2017-04-10 14:35
Provide a screenshot please...

**Comment by psifidotos** [comment] 2017-04-10 14:36
put in it as many double launchers you want

**Comment by psifidotos** [comment] 2017-04-10 15:10
Cam you provide also a screenshot from gitk to see what is the last commit you are using?

**Comment by mooop12** [comment] 2017-04-10 20:54
Last commit is correct:

```
commit b4bfdd94193379f04220129c000eccbb0ba63c5d
Author: Michail Vourlakos <mvourlakos@gmail.com>
Date:   Mon Apr 10 09:58:02 2017 +0300

    fix animation check when removing launcher
```

Here's how it looks:
![peek 2017-04-10 22-47](https://cloud.githubusercontent.com/assets/20934112/24882034/f9a8da32-1e3f-11e7-9ece-044b55d45f6b.gif)

**Comment by psifidotos** [comment] 2017-04-10 21:26
Something is weird in your system... i cant reproduce this in my system...

**Comment by psifidotos** [comment] 2017-04-10 21:28
when removing the window it works ok in your video... only when executing launcher it happens right?

**Comment by mooop12** [comment] 2017-04-10 21:32
That is correct. It works the same for me on the master branch as on the launcher59 branch.

**Comment by psifidotos** [comment] 2017-04-10 21:50
@mooop12 I uploaded one more commit... can you please check again?

**Comment by mooop12** [comment] 2017-04-10 21:59
That one did it! Thanks :smile:

**Comment by psifidotos** [comment] 2017-04-10 22:00
:) ok... I will include this patch when I will merge the **launchers59** branch in master...

**Comment by psifidotos** [comment] 2017-04-21 13:41
fixed in master....

**Closed by psifidotos** 2017-04-21 13:41 UTC
Labels: bug, reported!, upstream

**Comment by MPE2016** [comment] 2017-05-02 16:05
hi there, I'm having the exact same problem. Installed the version in the AUR repo. 
I run Plasma version 5.9.4 on Manjaro.

**Comment by psifidotos** [comment] 2017-05-02 16:11
fixed in master...
