### ISSUE TITLE
Dock is not onAllDesktops in rare cases

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#331] opened 2017-03-25 18:32 UTC
"Behave as a normal dock window"
- strange behavior when combined with Visibility mode auto hide
- its check box always returns as disabled

[Video](https://youtu.be/AW57NFhiKeI)

**Comment by psifidotos** [comment] 2017-03-25 18:47
I cant reproduce...

**Comment by JenaPlinsky** [comment] 2017-03-25 20:12
other interesting video 
[from minut 2:50 onward](https://youtu.be/RHSBiX02OtI)

**Comment by psifidotos** [comment] 2017-03-26 07:41
I still cant reproduce...

**Comment by JenaPlinsky** [comment] 2017-03-26 10:55
It happens passing from **always visible** to **auto hide** and vice versa 
but I dont understand in which order and by enabling or disabling the flag "Behave as a normal dock window"
![spectacle k21424](https://cloud.githubusercontent.com/assets/24593950/24330638/4c4b027a-1223-11e7-8213-3d1ab73ff081.png)

**Comment by psifidotos** [comment] 2017-03-26 12:20
I still cant find a way to reproduce this in my system...

**Comment by JenaPlinsky** [comment] 2017-03-26 14:12
@audoban can you  reproduce it?

**Comment by audoban** [comment] 2017-03-26 19:02
@JenaPlinsky Yes I can reproduce, And I suspect it happens because latte could not put the window on all the desktops

**Comment by JenaPlinsky** [comment] 2017-03-26 19:13
for the moment this seems to be the main flaw of Latte it happen often enough ( I admit ...I try to put your work in crisis ...ahahahah)

**Comment by audoban** [comment] 2017-03-28 04:45
This bug will be fixed on Friday when I has more time, because it's a bit difficult to debug.

**Comment by psifidotos** [comment] 2017-03-28 08:33
@audoban should we delay 0.6 release for this?

**Comment by Petross404** [comment] 2017-03-28 14:28
Also 0.6.1 can fix in a few days what 0.6.0 din't instead of postponing ;)

**Comment by psifidotos** [comment] 2017-03-29 11:36
@JenaPlinsky can you please check branch **fix331** and see if this is fixed for you ?

**Comment by psifidotos** [comment] 2017-03-29 11:58
some infos on this...

in my system this occured only for AlwaysVisible state and very rare and only when Always Visible was recreating the dock... 

Steps to Reproduce:

- add four "Always Visible" docks in default session and four "Always Visible" docks in Alternative Session
- switch between Default and Alternative Session (this is the easier and faster way to recreate docks and nothing related to the "Behave as normal dock window" feature
- there are cases that some of the docks are not on all desktops

after applying the patch from the branch **fix331** I cant reproduce the behavior. The patch applies the onAllDesktops flag very early in the docks creation...

**Comment by JenaPlinsky** [comment] 2017-03-29 19:54
@psifidotos  seems the fix works properly !!! Great !!!! 

please let me just give you a confirmation?
...since I changed the script, that I use to download from github
...and now it shows me a combo box with the list of all the available branch

I wanted to be sure, that I have installed from  the correct branch

with the Fix331 when visibility mode is set to **always visible** ...the  check box "Behave as a normal dock window" is now "gray/unavailable", right ?

**Comment by JenaPlinsky** [comment] 2017-03-29 19:57
@audoban can you confirm too? is it fixed ?

**Comment by psifidotos** [comment] 2017-03-29 20:09
> with the Fix331 when visibility mode is set to always visible ...the check box "Behave as a normal dock window" is now "gray/unavailable", right ?

yes, this is true... in Always Visible mode the "Behave as a normal dock" doesnt make any difference so it is disabled...

**Comment by JenaPlinsky** [comment] 2017-03-29 20:16
ok, so I tested the right branch :) ...and I think now everything is ok !!!
35/5000
Very nice ... it gets better

**Closed** 2017-03-29 20:22 UTC
Labels: bug

**Comment by psifidotos** [comment] 2017-03-29 20:24
ok... I merged it in order to have more time for testing from bigger user audience... we are just few days before release...
