### ISSUE TITLE
Screen changes don't make docks/panels aware of what screen they are on

### ISSUE THREAD

**Issue by slagiewka** [psifidotos/Latte-Dock#542] opened 2017-06-14 18:43 UTC
This may or may not be related to two things I'm observing.

Background:
1 x Laptop screen with dock on the bottom
2 x external displays, on of which has dock on left side
Beside docks with tasks Latte plasmoid, every screen gets a panel-like Latte with more or less same setup - most important - Active Window Control with option making it only display the title of the window if it is on the same screen.

1. When screen configuration changes the Active Window Control widgets do not always point to the right window. Sometimes the widget on two screens will display the active window's name. Or a widget on one screen would display the name of a window from another screen and the other way round. Restarting Latte helps.

2. I sometimes disable laptop and one of the external screens (both screens have task docks, as mentioned in the background). I'd also like to stress the fact that each Latte dock/panel is explicitly to which screen it belongs - eDP-1, DP-1-8, DP-1-1. I nerver use Primary and I don't set primary display in kscreen.
Expected behaviour of Latte:
Only one panel stays on the screen - the one that was originally assigned to it.
Actual behaviour:
On the display I have two Latte - on is the panel that should be there (at least I think so - can't distingiush panels from external display - only the laptop one has two extra widgets) and the bottom Latte dock from the laptop display.

Before disabling the displays I started checking if the unwanted dock has correct settings. It does - it's always eDP-1, as it's supposed to be. Nevertheless I end up with the dock landing on DP-1-8...

If I could provide any more details - do not hesitate to ask.

**Comment by psifidotos** [comment] 2017-06-14 19:34
I would prefer screenshots to understand better the faulty behavior..
 Are you using master?

**Comment by slagiewka** [comment] 2017-06-14 22:31
Ok, from the beginning:

![screenshot_20170614_220701](https://user-images.githubusercontent.com/11974489/27155092-dba08166-5157-11e7-9b33-8eaa5a120210.png)
![screenshot_20170614_220720](https://user-images.githubusercontent.com/11974489/27155095-dda3022c-5157-11e7-9569-812919492e69.png)
Now, let's disable the entire left side (don't mind the time, I had to reshot):
![screenshot_20170614_223605](https://user-images.githubusercontent.com/11974489/27155431-45f44d62-5159-11e7-8f33-d89cd4412502.png)
Looks OK, but is it? Let's maximize a window:
![screenshot_20170614_223612](https://user-images.githubusercontent.com/11974489/27155444-53886828-5159-11e7-86da-2dcb519337bf.png)
Now let's unplug external cord, and plug it again:
![screenshot_20170614_223632](https://user-images.githubusercontent.com/11974489/27155485-77df272a-5159-11e7-8f97-4c654d833f20.png)
![screenshot_20170614_223937](https://user-images.githubusercontent.com/11974489/27157445-d45f9874-5161-11e7-92ec-9589ce611951.png)
Oh, oh…

In the meantime I had a crash which I wanted to trace, so I opened Latte with ddd when I had only one display enabled. I couldn't recrash it, but I noticed something:
![screenshot_20170614_222018](https://user-images.githubusercontent.com/11974489/27156018-8b9530d2-515b-11e7-80d1-222efd61c65f.png)
So basically it depends if Latte was started when this one display was enabled or all of them were on. If Latte was started when all of them were enabled - the dock from laptop display show on the last one standing (DP-1-8) which is unwanted. When Latte is started if only DP-1-8 is on, the dock from eDP-1 will not show, but the one from DP-1-1 will. This also unwanted, but tolerable.

Now let's say I started Latte with only DP-1-8 on. Let's enable the rest of them:
![screenshot_20170614_222803](https://user-images.githubusercontent.com/11974489/27156965-b78d64f8-515f-11e7-868d-5fe434236422.png)

 Now the left dock point's to On Primary. Whaaaat?

Side note - after I disabled the left side (third screenshot) - the top panel does not show the title anymore.
When the left side was enabled again:
![screenshot_20170614_221356](https://user-images.githubusercontent.com/11974489/27157319-4828c6d2-5161-11e7-804c-3235dcaf94d7.png)
No tilte. Let's move the window to the left:
![screenshot_20170614_221347](https://user-images.githubusercontent.com/11974489/27157342-5b34f55c-5161-11e7-8b9d-4a93cf1caf6e.png)
Same would happen for a window on laptop screen (title shown).

Unfortunately, I couldn't make the config show title on two panels simultaneously when testing.

**Comment by psifidotos** [comment] 2017-06-15 05:34
Ok...
I suppose you dont know some of the internals to understand what is happening... some of them are bugs some arent based on how Latte was designed.

Rule 1: Latte in multi-screen environment tries to never let you without at least one Latte Dock that contains the Latte plasmoid(tasks). How this is achieved....

1a. if this situation occurs after startup (during working-running), Latte moves a dock containing a Latte plasmoid to the last screen (this is a screen that shouldnt have any latte dock in it but a situation occured that no latte plasmoid is shown in any other screen so Latte is trying to protect you). If that happens then when the original dock screen is activated again then the dock that was moved from Latte returns to its original screen.

1b. if this situation occurs  on startup (when starting Latte), then Latte shows in that screen the oldest dock containing a Latte plasmoid (tasks in it). When the original screen of that screen is activated again then this dock should return at its original screen


Questions:
1. the top docks are Latte or plasma panels?


Commenting your response:

> Looks OK, but is it? Let's maximize a window:

the bug is not that  Latte from the bottom have moved at this screen, but that it isnt shown even though it is Always Visible, after you unplug-plug again then it is repositioned correctly (we should try to track this)

> Oh, oh…

yes, this is how it should work when you disabled all your left side


> So basically it depends if Latte was started when this one display was enabled or all of them were on. If Latte was started when all of them were enabled - the dock from laptop display show on the last one standing (DP-1-8) which is unwanted.

Do you mean that if all three monitors are activated and then you start Latte, one of them is not positioned in the correct screen even though when closing Latte every dock was at the correct place?

> When Latte is started if only DP-1-8 is on, the dock from eDP-1 will not show, but the one from DP-1-1 will. This also unwanted, but tolerable.

this is default behavior not an issue. Anything else is a feature request

> Now let's say I started Latte with only DP-1-8 on. Let's enable the rest of them:
> Now the left dock point's to On Primary. Whaaaat?

there is a chance that the order you are activating the last two screens may influence this but this looks as a bug and we can try to track it down

> Side note - after I disabled the left side (third screenshot) - the top panel does not show the title anymore.

what is the title? the top panel is Latte dock and it isnt showing its configuration window?


> When the left side was enabled again:
> No tilte. Let's move the window to the left:
> Same would happen for a window on laptop screen (title shown).

I dont understand what is the issue you are describing here... you cant show the Latte configuration window?

> Unfortunately, I couldn't make the config show title on two panels simultaneously when testing.

in Latte yes you can do this... When showing the Latte configuration window at its top-right corner there is a stick button that when it is pressed that configuration window is not closing when loses focus


----

please because this is a big review, I would like to find a way to keep this a bit structured.... Please for each issue you are considering as bug open a different issue and point to this thread... This way it will be much easier to solve things and track down any problems. After that when we track each issue I will create a new branch that you can test if the issue has been solved...

**Comment by psifidotos** [comment] 2017-06-15 05:37
BTW, if you add a third latte dock at your top right screen containing the Latte plasmoid (tasks) then possibly most of them or even all these problems would disappear.... Most of them occur when Latte thinks that you end up in a situation that you dont have any screen available containing the Latte plasmoid. It is trying to protect you

**Comment by psifidotos** [comment] 2017-06-17 12:25
reporter didnt interact with developers...

**Closed by psifidotos** 2017-06-17 12:25 UTC
Labels: bug, needsinfo
