### ISSUE TITLE
Make docks to not overlap when one is set as Always Visible

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#126] opened 2017-02-03 21:42 UTC
The layer level would determine the order (i.e. from top to bottom) of the different latte docks

This would be useful for using a top panel and a side panel, if both try to take advantage of the snapping feature (which implies justification).

Please see the issue in the attachment (top panel should be top layer, but currently it depends on which latte dock was activated last, in this case the side panel).

![image](https://cloud.githubusercontent.com/assets/3875196/22609326/c95b741a-ea2e-11e6-90e9-3299d5d6453d.png)

**Comment by audoban** [comment] 2017-02-03 22:13
@kupiqu I like your idea, but it's not that simple. This behavior is natural of KWIN

I propose that when a panel is AlwaysVisible, any other Dock should avoid cover the dock that have visibility AlwaysVisible.

Let me upload a branch to see how it could be.

**Comment by kupiqu** [comment] 2017-02-04 00:21
that would be even better :)

**Comment by psifidotos** [comment] 2017-02-04 10:51
for this we might need an internal offset mechanishm for the qml side to support proper visual layout

**Comment by audoban** [comment] 2017-02-05 07:56
I'm developing a feature to prevent docks from overlapping, using Corona::availableScreenRect as base for calcutate the maxLength of a Dock, without break the maxLength percent option.

**Comment by audoban** [comment] 2017-02-11 05:39
Ok, now I need some of feedback.

please try the brach [enhancement-overlaping](https://github.com/psifidotos/Latte-Dock/tree/enhancement-overlaping)

**Comment by kupiqu** [comment] 2017-02-11 07:55
It worked!! Already using it as default :)

Only one question, what is the intended behavior when top panel is set to a scaling < 100%? Right now the side panel is moved down, I think, irrespective of the scaling of the top panel.

Would it make sense if the side panel moves down only when an overlay is expected?

**Comment by audoban** [comment] 2017-02-11 08:01
> Only one question, what is the intended behavior when top panel is set to a scaling < 100%? Right now the side panel is moved down, I think, irrespective of the scaling of the top panel.
Would it make sense if the side panel moves down only when an overlay is expected?

Yes, you have reason, I will to improve this behavior.

thanks, if you have any other ideas, please tell me.
Thanks for waiting. I have been very busy.

**Comment by kupiqu** [comment] 2017-02-11 12:41
Many thanks to you, excellent feature! :)

**Comment by psifidotos** [comment] 2017-02-12 14:12
@audoban I think this is fixed, right?

**Comment by kupiqu** [comment] 2017-02-12 14:14
I think @audoban is working on an improvement of the feature, so the side panel does not move down if the top panel is not expected to overlay... this relates to the scaling factor of the top panel

**Comment by audoban** [comment] 2017-02-20 05:11
Hello @kupiqu I am doing some improvements to this feature. Now the lateral dock just avoid the overlapping when an horizontal panel is alignment to Justify. 

Let me know your opinion.

 branch https://github.com/psifidotos/Latte-Dock/tree/overlap

**Comment by audoban** [comment] 2017-02-20 05:12
> I think @audoban is working on an improvement of the feature, so the side panel does not move down if the top panel is not expected to overlay... this relates to the scaling factor of the top panel

Describe me better than you want.

**Comment by kupiqu** [comment] 2017-02-20 06:16
not sure this is possible or easy, but it would be nice if under justified alignment, the lateral dock avoids overlapping when in fact there is overlapping (vertical offset), but it doesn't otherwise.

saying so, because there is a feature for scaling the dock in percentage factors.

for instance, in my case, overlapping would happen (although it is resolved by your feature: by a vertical offset of the lateral panel) for 100% and 95%, but for scalings <95% there is no overlapping of the two docks, thus no need to avoid such an inexistent overlapping (so no vertical offset should be applied to the lateral dock).

Would you agree?

I hope what I mean it's clearer now...

**Comment by audoban** [comment] 2017-02-20 21:44
> not sure this is possible or easy, but it would be nice if under justified alignment, the lateral dock avoids overlapping when in fact there is overlapping (vertical offset), but it doesn't otherwise.

Well is possible.

> for instance, in my case, overlapping would happen (although it is resolved by your feature: by a vertical offset of the lateral panel) for 100% and 95%, but for scalings <95% there is no overlapping of the two docks, thus no need to avoid such an inexistent overlapping (so no vertical offset should be applied to the lateral dock).

> Would you agree?

Yes, I'm agree, but I do not want it to depend of the percentage, only of free space, it would be more accurate, avoid the overlapping just when is necessary.

**Comment by kupiqu** [comment] 2017-02-21 04:48
Sure. I was just trying to illustrate the point :)

**Comment by kupiqu** [comment] 2017-03-01 04:34
I realized that current implementation for Always Visible panels with "avoid overlapping" feature presents an issue, so windows are not 'aware' of the side panel, thus:

- launched windows may be covered by the side panel
- maximized windows are also covered by the side panel

Could you please check?

This behavior was not present before introducing "avoid overlapping" feature (commit e9221f87196fa900408f3a7bb1e2615ae447c63d)

**Comment by psifidotos** [comment] 2017-03-01 08:24
can you make screenshots in order to compare and understand?

**Comment by kupiqu** [comment] 2017-03-01 11:46
Sure, please see screenshot:

![image](https://cloud.githubusercontent.com/assets/3875196/23458392/1c05392e-fe4a-11e6-9391-e7d5bc830677.png)

This apply to the second case above: maximized windows are also covered by the side panel

Further testing showed me not accurate about the first point above, most windows are correctly placed at launch for the side panel as for the top panel (although some windows such as Kontact and Choqok do not respect any of the latte dock borders, nor for the top panel, neither for the side panel -- I think you are aware of this issue, aren't you?)

**Comment by psifidotos** [comment] 2017-03-01 12:15
> This apply to the second case above: maximized windows are also covered by the side panel

have you set the side panel to Always Visible?

>  such as Kontact and Choqok do not respect any of the latte dock borders, nor for the top panel, neither for the side panel -- I think you are aware of this issue, aren't you?)

you are refering to snapping? snapping works only in with  Always Visible ... Extremely good snapping and accurate work only with (Always Visible + Fill Alignment+ maximum backgound size)

**Comment by psifidotos** [comment] 2017-03-01 12:19
ok... confirmed!

struts and snapping do not work properly with vertical docks...

**Comment by psifidotos** [comment] 2017-03-01 12:24
ok.. more details... struts and snapping do not work correctly with docks that change their size to not overlap!!!

**Comment by kupiqu** [comment] 2017-03-01 12:28
Yes, that is what I meant, sorry I was not clear enough

**Comment by psifidotos** [comment] 2017-03-01 13:19
> Yes, that is what I meant, sorry I was not clear enough

looking more into it... this exist only with the left dock, the right works ok...

**Comment by psifidotos** [comment] 2017-03-01 13:28
@kupiqu fixed in master... it was just a small wrong typo

**Comment by kupiqu** [comment] 2017-03-01 13:33
Super, thanks!

And wrt:

> Re: such as Kontact and Choqok do not respect any of the latte dock borders, nor for the top panel, neither for the side panel -- I think you are aware of this issue, aren't you?)

> you are refering to snapping? snapping works only in with Always Visible ... Extremely good snapping and accurate work only with (Always Visible + Fill Alignment+ maximum backgound size)

Yes, I have such configuration and Kontact, Choqok and few others do not respect good snapping. I guess there is no easy way to workaround it, is there?

**Comment by psifidotos** [comment] 2017-03-01 17:28
I dont know... either with the latest master dont you get extremely good snapping for these apps?

**Comment by kupiqu** [comment] 2017-03-01 19:27
Yes, with latest master. I have to say that most apps obey, yet there are few apps that do not :-/

**Comment by psifidotos** [comment] 2017-03-01 19:50
> yet there are few apps that do not :-/

do these apps obey the official plasma panel's geometry ? if they dont can you give an example and screenshot?

**Comment by kupiqu** [comment] 2017-03-02 12:00
I'd say they behave in plasma, but need to try...

**Comment by psifidotos** [comment] 2017-03-02 20:16
@kupiqu I have done some work for this but first is must also be checked from @audoban and I havent tested it also how it works with multi-screens... meaning it calculates the docks positioning correctly...

**Comment by kupiqu** [comment] 2017-03-02 20:28
is this related to the newoverlap branch? Unfortunately it doesn't build in my system:

```
dockview.cpp: In member function ‘QRect Latte::DockView::maximumNormalGeometry()’:
Latte-Dock/app/dockview.cpp:387:9: error: return-statement with no value, in function returning ‘QRect’ [-fpermissive]
         return;
         ^
app/CMakeFiles/latte-dock.dir/build.make:206: recipe for target 'app/CMakeFiles/latte-dock.dir/dockview.cpp.o' failed
make[2]: *** [app/CMakeFiles/latte-dock.dir/dockview.cpp.o] Error 1
CMakeFiles/Makefile2:230: recipe for target 'app/CMakeFiles/latte-dock.dir/all' failed
make[1]: *** [app/CMakeFiles/latte-dock.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by psifidotos** [comment] 2017-03-02 20:34
fixed it in **newoverlap** branch

**Comment by psifidotos** [comment] 2017-03-02 20:49
it works so good with the new multi-screen behavior that I will cry!!!! :)

**Comment by kupiqu** [comment] 2017-03-03 16:28
> do these apps obey the official plasma panel's geometry ? if they dont can you give an example and screenshot?

Confirmed, they (tested for Kontact, Choqok and Kwalletmanager) behave properly with plasma panels.

Please see screenshots below for how these applications appear under the latte panels at startup:

![image](https://cloud.githubusercontent.com/assets/3875196/23559049/d03311c2-0003-11e7-8ece-fd2c913f7797.png)

![image](https://cloud.githubusercontent.com/assets/3875196/23559181/2138344e-0004-11e7-8046-4d8b84b4683d.png)

![image](https://cloud.githubusercontent.com/assets/3875196/23559235/497f248a-0004-11e7-9ff0-e4d81bccd1b1.png)

**Comment by psifidotos** [comment] 2017-03-03 17:59
@kupiqu sorry but I can confirm the behavior in Latte... These work ok in my system...

Plasma 5.9.3 and a top bar Always Visible, are you using latest master? the one we reverted back the flag, ByPassWindowManagerHint?

**Comment by kupiqu** [comment] 2017-03-03 18:10
Mmm, that's very weird, I wonder what's failing here :-/ 

Yes, I'm in latest master, same plasma version and configuration (both panels always visible). Just to be sure, do you also have two (top and left) panels as well?

My top panel is set to 32px and my side panel to 56px, could you try to see if this would change anything?

**Comment by psifidotos** [comment] 2017-03-03 18:32
I am using branch **newoverlap** which contains all latest fixes in review stage before commiting it in master... I am using 2-3 docks at the same time in my system and testing with them the issues accordingly...

**Comment by kupiqu** [comment] 2017-03-03 18:40
there seems to be a conflict between master and newoverlap in app/dockview.cpp now

**Comment by psifidotos** [comment] 2017-03-03 19:03
I rebased to be sure and recreated it...

It might be a good idea to send the screenshots of your debug windows also to check the various settings...

`latte-dock -d --with-window`

**Comment by kupiqu** [comment] 2017-03-03 19:29
Unfortunately same behavior with the newoverlap branch.

These are my settings:

![image](https://cloud.githubusercontent.com/assets/3875196/23565928/a66b08bc-001d-11e7-9e96-1a56e5255003.png)

**Comment by psifidotos** [comment] 2017-03-03 19:34
If you lower your screen resolution, same problem?

**Comment by psifidotos** [comment] 2017-03-03 19:45
and also the use of, Global Menu, how did you add it in Latte? and the use of active window..

Is this happening only with these apps or all apps that usr global menu?

When you drag these apps at the top dont they understand any snapping?

**Comment by kupiqu** [comment] 2017-03-03 19:54
Unfortunately, same on different resolutions

Global menu is now part of active window (I don't use the one delivered by the plasma team)

It also happens in apps that don't activate global menu, e.g. inkscape

They behave correctly for snapping and everything, only problem I'm having is in the position they occupy at launch

**Comment by psifidotos** [comment] 2017-03-03 20:19
have you added any window rules for them?

**Comment by psifidotos** [comment] 2017-03-03 20:28
system settings -> Windows Management -> Windows Behavior -> Advance (Tab) -> Locate Windows

what kwin window policy are you using? have your tried centered, maximized instead of Smart?

on startup windows are placed completely with kwin's responsibility....

**Comment by kupiqu** [comment] 2017-03-03 20:35
I don't have specific window rules for them.

Indeed, I use Smart location, I'll check others (although the one I like is Smart). Not sure what's going to happen with Maximized, but I think it will trivially work with Centered as it does not rely on locating the boundaries any more...

**Comment by kupiqu** [comment] 2017-03-03 20:44
Mmm, that's weird, I tried with choqok and it behaves the same in the three configurations. So confused

**Comment by psifidotos** [comment] 2017-03-03 20:47
Smart works for me, but i dont know why it doesnt work at your system...

As long as snapping works the boundarries are known to kwin but i dont know why kwin doesnt use them

**Comment by kupiqu** [comment] 2017-03-03 20:56
Let me see if this is because of a kwin script...

**Comment by kupiqu** [comment] 2017-03-03 21:25
This didn't work either. I removed all kwin scripts and removed my local kwinrc file, but same thing...

Thanks for helping! this must be frustrating for you... Let's have a break for now, maybe we come with new ideas later :)

**Comment by psifidotos** [comment] 2017-03-03 22:51
it is a bit... but we always learn something... I updated the geometry callculations in order of the rare case that struts were confused from values that were negative or outside of the dock window, and also some small improvements in that area... I dont know if that helps...

the commit is at newoverlap branch

**Comment by kupiqu** [comment] 2017-03-03 23:33
I think there is sth really going wrong with kwin and this doesn't have to do anything with latte as the same wrong location happens with and without latte being present for those apps when under kwin's centered location preference.

I will play a bit further with kwinrc to see if I can figure this out and will fill a bug otherwise.

My feeling is that I might have used rules for those apps but then I removed the rules and somehow this has messed things...

The reason I thought it was latte and not sth related to plasma or kwin before is that Smart somehow was respecting the boundaries of plasma panels to a extreme that doesn't seem to do with latte panels.

But I think this has to be some secondary security check, as other apps not suffering this issue in kwin (seen also with centered location preference), behave properly both in plasma and latte...

**Comment by kupiqu** [comment] 2017-03-03 23:34
> My feeling is that I might have used rules for those apps but then I removed the rules and somehow this has messed things...

I meant over the years...

**Comment by psifidotos** [comment] 2017-03-04 00:10
makes sense... you can test with a second user in your system that has clean plasma configuration...

**Comment by psifidotos** [comment] 2017-03-04 10:20
@kupiqu also the new calculations for snapping has just been uploaded at **newoverlap** branch... I dont know if that helps you also...

**Comment by kupiqu** [comment] 2017-03-04 13:01
Mmm, these new calculations don't work very well my system

Top panel:
![image](https://cloud.githubusercontent.com/assets/3875196/23578961/7d7080f2-00b0-11e7-85ea-566237c88fb5.png)

Side panel:
![image](https://cloud.githubusercontent.com/assets/3875196/23578965/8cc2b2d2-00b0-11e7-8a6a-30c80c2745e1.png)

I cannot effectively change the visible background width although I change its size in settings. Also numbers are not multiples of 8 anymore.

**Comment by psifidotos** [comment] 2017-03-04 13:37
panel background has updated to percentage instead of pixel make it to be 100%...

download latest commits from new overlap... it has many goodies in it... support solid background...
support blur and background contrast kwin effects for the docks that draw their shadows outside..

that is: "always visible, !solid_background, zoom factor:1, panel background: 100%"

**Comment by psifidotos** [comment] 2017-03-04 13:40
also with the new features... the Unity paradigm top dock and left dock is very easy... and of course a lot of smart positioning for docks in order to know what is the free space that can be used...

**Comment by kupiqu** [comment] 2017-03-04 14:06
So cool, I missed the fact it was in %

**Comment by kupiqu** [comment] 2017-03-04 14:09
Amazing! These problematic apps now work in latte exactly as in plasma.

I still think there is sth wrong with kwin as they don't obey the location preference, but now they obey kwin's borders based on plasma as well as latte, finally!

Many thanks

**Comment by psifidotos** [comment] 2017-03-04 14:13
> Amazing! These problematic apps now work in latte exactly as in plasma.

nice!!! :)

In my system's screen... :) I add 3 docks and I set all of them always visible and after that I change their alignments and positionings and their max lengths... it is a beauty... Latte finds the best placements... ;)

**Comment by kupiqu** [comment] 2017-03-04 14:15
Neat!

Is that your current setup or just for testing. Wondering what is the 3rd panel for, in your case...

**Comment by psifidotos** [comment] 2017-03-04 14:21
just for testing... :-)

**Comment by psifidotos** [comment] 2017-03-05 12:38
before commit: https://github.com/psifidotos/Latte-Dock/commit/b260939470cb2828cf5c29777dc2ba14240d861a

there are also 3-4 commits providing this feature....

**Closed by psifidotos** 2017-03-05 12:38 UTC
Labels: enhancement

**Comment by kupiqu** [comment] 2017-03-05 13:36
The new features work great!

Unfortunately it seems there is a small glitch. When I decrease the scaling of the top panel (let's say to 95%, then to 90%) and then back to 100% again, the side panel does not correct its top position to avoid overlapping. I need to restart latte to come back to desired behavior.

Can you please try to confirm?

**Comment by psifidotos** [comment] 2017-03-05 13:54
> Can you please try to confirm?

sorry, cant reproduce... can you make a video?

**Comment by kupiqu** [comment] 2017-03-05 14:23
I'll try to make a video later if I can, but for now let me explain better: to raise the issue, I need to scale down the top panel and then set it to 100% again. It doesn't happen always, so perhaps you see the problem if you play a bit with it. I realized that I can get back to correct behavior not only restarting latte but also configuring the side panel, and scaling it down and up again.

These changes from newoverlap haven been added to master, right? I think I tried with master and newoverlap branches with same results.

**Comment by psifidotos** [comment] 2017-03-05 14:42
newoverlap was merged into master today... I found another case that something like what you are describing was happening and have just uploaded a commit in master, when the configuarion window becomes hidden the issue I found in my system is fixed...
I dont know if that corrects also your case...

**Comment by kupiqu** [comment] 2017-03-05 15:17
Not quite yet there. when you vary the scaling %, do you hidden the config window? if not, please try to do so.

- top panel:
1. open config window -> appearance -> length -> 90% -> close config window: the top panel shrinks and side panel occupies all vertical space, as expected.
2. open config window again -> appearance -> length -> 100% -> close config window again: the top panel expands to occupy all space (expected), but the side panel does not shrink to avoid overlapping (issue, which happens about half of the times, don't know what it depends on...).

**Comment by psifidotos** [comment] 2017-03-05 15:19
what are the characteristics of the docks? always visible, fill alignment, zoom: 1 ?

**Comment by psifidotos** [comment] 2017-03-05 15:20
background: 100% ?

**Comment by kupiqu** [comment] 2017-03-05 15:21
yes

**Comment by psifidotos** [comment] 2017-03-05 15:23
in my system at step 2 I dont even need to close the config window and the left dock is placed correctly...

**Comment by kupiqu** [comment] 2017-03-05 15:35
Ok, try the following (perhaps few times, as it happens most of the times but not always):

If you just click in different values along the length scrollbar, it typically works, however if you drag and drop the tuner (or whatever it's called: i.e., circle that sets current value in the scrollbar), it mostly fails when moving to a value <95%, stop there, then go to 95%, stop there, and finally end at 100%.

If you repeat this sequence and still works for you ok, then I'm pretty sure it's sth happening only to me for whatever reason.

**Comment by psifidotos** [comment] 2017-03-05 15:38
sorry, it worked for me...

@kupiqu  make a video and show also the debug windows...

**Comment by kupiqu** [comment] 2017-03-06 21:56
I recorded a small video, but now I don't know how to share it with you. github does not seem to allow video files

**Comment by psifidotos** [comment] 2017-03-06 22:02
You can share a link witj google drive or upload in youtube!!

**Comment by kupiqu** [comment] 2017-03-06 22:04
As this goes directly to the email I'm going to try just attaching it here. Let me know if you can see it...

El dilluns, 6 de març de 2017, a les 17:02:29 EST, Michail Vourlakos va escriure:

  You can share a link witj google drive or upload in youtube!!

**Comment by psifidotos** [comment] 2017-03-06 22:33
Sorry I dont see anything...

**Comment by kupiqu** [comment] 2017-03-07 14:51
Ok, here we go:

[https://www.youtube.com/watch?v=zg-mW89AaIo](https://www.youtube.com/watch?v=zg-mW89AaIo)

**Comment by psifidotos** [comment] 2017-03-07 15:00
ok... one question ...

of you be more aggresive... for example go to 80% and then back to 100% does it occur again?

**Comment by kupiqu** [comment] 2017-03-07 15:08
It is not systematic, it doesn't happens always, but it does happens.

I think the problem is in whether the offset of the side panel is kept or not once length is reduced to e.g. 80%. Offset should always be removed in that case, but this is a bit stochastic in my system.

What seems to be totally reliable is the behavior once length comes back to 100%, if offset was removed, then both panels end up overlapping, if offset was kept, then offset remains and overlay does not occur.

**Comment by psifidotos** [comment] 2017-03-07 16:34
@kupiqu fixed in master... that corner case hadnt been taken into account... top and left dock overlap but at the same time there is also some screen free space in that overlap....

**Comment by kupiqu** [comment] 2017-03-07 16:40
Sorry, it still fails in my system :/

**Comment by psifidotos** [comment] 2017-03-07 17:26
show me a screenshot how it looks for top at 95% after closing config window

**Comment by psifidotos** [comment] 2017-03-07 17:27
this is in my system...

![image](https://cloud.githubusercontent.com/assets/2216474/23669219/0e144c0c-036c-11e7-85a0-9e791675065f.png)

**Comment by kupiqu** [comment] 2017-03-07 17:32
This is how 95% length looks like in my system:

![image](https://cloud.githubusercontent.com/assets/3875196/23669389/ef835812-0331-11e7-8e71-3b8a3591df97.png)

**Comment by psifidotos** [comment] 2017-03-07 17:36
if the left dock is drawing Shadows external... you can check this from the debug window... then you are not using the latest commits from master

**Comment by kupiqu** [comment] 2017-03-07 17:43
mmm, I'm up-to-date with master, and ran install.sh after pulling last commits

![image](https://cloud.githubusercontent.com/assets/3875196/23669720/30881324-0333-11e7-95b2-02d4d9b2fe6f.png)


however shadows appear as external:

![image](https://cloud.githubusercontent.com/assets/3875196/23669744/528173d0-0333-11e7-8b42-86dfcd099cc9.png)

I'll try to purge latte-dock and install it from scratch to see if it gets fixed

**Comment by kupiqu** [comment] 2017-03-07 17:45
Same thing, I used uninstall.sh then install.sh, draw shadows continue being external for both panels :/

**Comment by psifidotos** [comment] 2017-03-07 17:47
for this case of 95% it should appear the top border of the left panel correctly...
except if it considers the top dock to be 100% but this shouldnt happen...

if you go from 90% to 95% the top border of the left dock doesnt appear correctly?

**Comment by kupiqu** [comment] 2017-03-07 17:50
This is what I saw:

- top panel length set to 90% -> left panel didn't remove the offset
- top panel length set to 95% -> left panel removed the offset
-top panel length set to 100% -> left panel didn't introduce the offset, so both panels overlap

**Comment by psifidotos** [comment] 2017-03-07 18:12
so even for 90% does not work ok with you?

the screenshot you sent was for 95% or for 90% ?

can you sent a screenshot of 90% of not removing the offset ?

**Comment by kupiqu** [comment] 2017-03-07 18:17
Sure:

![image](https://cloud.githubusercontent.com/assets/3875196/23671205/6848e16c-0338-11e7-9f17-f710fd18b73d.png)

**Comment by psifidotos** [comment] 2017-03-07 18:21
this is totally wrong... it doesnt draw the top border correctly, it doesnt even occupy the needed space... and a screenshot of the two debug windows for this?

**Comment by psifidotos** [comment] 2017-03-07 18:21
does this happen always?

**Comment by psifidotos** [comment] 2017-03-07 18:25
and when you go from 85% to 90% the problem shown in then screenshot remains?

**Comment by psifidotos** [comment] 2017-03-07 18:46
I am starting to believe that the only way to hunt this down is through irc chatting... we could schedule a meeting if you want...

**Comment by kupiqu** [comment] 2017-03-07 19:29
![image](https://cloud.githubusercontent.com/assets/3875196/23674014/665186b6-0342-11e7-9a49-aca937d64faa.png)

**Comment by kupiqu** [comment] 2017-03-07 19:30
As far as I can say it is quite systematic for this sequence:

- top panel length set to 90% -> left panel didn't remove the offset
- top panel length set to 95% -> left panel removed the offset
- top panel length set to 100% -> left panel didn't introduce the offset, so both panels overlap

**Comment by kupiqu** [comment] 2017-03-07 19:32
If I start with 85%, the result is the same:
- top panel length set to 85% -> left panel didn't remove the offset
- top panel length set to 90% -> left panel removed the offset
- top panel length set to 100% -> left panel didn't introduce the offset, so both panels overlap

**Comment by kupiqu** [comment] 2017-03-07 19:37
I think we should rest from this, at least for a while.... :)

**Comment by psifidotos** [comment] 2017-03-07 19:47
@kupiqu as you wish... :) my proposal was to discuss it in irc and creating runtime a branch to test in your system and responding me the debugging messages in order to find the root of why this is working correctly in your system... :)

**Comment by kupiqu** [comment] 2017-03-07 19:56
it's not that urgent (i use 100% length anyways). i am just trying to help debugging for the case other users may suffer the same (but nobody else complained so far)

perhaps next week? i'm a bit busy now.... 

in a different vein, i never used irc :/

**Comment by psifidotos** [comment] 2017-03-07 19:59
ok... no prob... :)

you could try telegram when you find time... ;) see you around...

**Comment by kupiqu** [comment] 2017-03-07 20:13
Yes, let's do a telegram next week!

**Comment by kupiqu** [comment] 2017-03-09 00:58
Yo may not believe it, but it seems to work now. Not sure you changed anything to this regard in your last commits, or it is the fact that I removed the build folder and installed the applet again, but now the wrong behavior seems to be gone for good!

**Comment by psifidotos** [comment] 2017-03-09 16:44
I cant know... some calculations were improved more from one of those commits...

Nice hearing this is fixed for you... ;)
