### ISSUE TITLE
Crash when switching desktops

### ISSUE THREAD

**Issue by devillemereuil** [psifidotos/Latte-Dock#602] opened 2017-07-20 00:07 UTC
Sometimes (not always, would be too easy), when I switch between desktop (e.g. using the grid effect), Latte-Dock (v0.6.2) crashes. Here's the backtrace from DrKonqi:

    Application: Latte Dock (latte-dock), signal: Segmentation fault
    Using host libthread_db library "/lib64/libthread_db.so.1".
    [Current thread is 1 (Thread 0x7f01d24448c0 (LWP 29332))]
    
    Thread 4 (Thread 0x7f01945f1700 (LWP 29340)):
    #0  0x00007f01cc5e020d in poll () at /lib64/libc.so.6
    #1  0x00007f01c7e69314 in  () at /usr/lib64/libglib-2.0.so.0
    #2  0x00007f01c7e6942c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
    #3  0x00007f01cd10433b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
    #4  0x00007f01cd0b1feb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
    #5  0x00007f01cceecf1a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
    #6  0x00007f0195a1a8f7 in KCupsConnection::run() () at /usr/lib64/libkcupslib.so
    #7  0x00007f01ccef19e9 in  () at /usr/lib64/libQt5Core.so.5
    #8  0x00007f01c8386744 in start_thread () at /lib64/libpthread.so.0
    #9  0x00007f01cc5e8aad in clone () at /lib64/libc.so.6
    
    Thread 3 (Thread 0x7f01affff700 (LWP 29335)):
    #0  0x00007f01cc5e020d in poll () at /lib64/libc.so.6
    #1  0x00007f01c7e69314 in  () at /usr/lib64/libglib-2.0.so.0
    #2  0x00007f01c7e6942c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
    #3  0x00007f01cd10433b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
    #4  0x00007f01cd0b1feb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
    #5  0x00007f01cceecf1a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
    #6  0x00007f01cfeb29d8 in  () at /usr/lib64/libQt5Qml.so.5
    #7  0x00007f01ccef19e9 in  () at /usr/lib64/libQt5Core.so.5
    #8  0x00007f01c8386744 in start_thread () at /lib64/libpthread.so.0
    #9  0x00007f01cc5e8aad in clone () at /lib64/libc.so.6
    
    Thread 2 (Thread 0x7f01c0142700 (LWP 29333)):
    #0  0x00007f01cc5dc28d in read () at /lib64/libc.so.6
    #1  0x00007f01c7ea9670 in  () at /usr/lib64/libglib-2.0.so.0
    #2  0x00007f01c7e68e49 in g_main_context_check () at /usr/lib64/libglib-2.0.so.0
    #3  0x00007f01c7e692a8 in  () at /usr/lib64/libglib-2.0.so.0
    #4  0x00007f01c7e6942c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
    #5  0x00007f01cd10433b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
    #6  0x00007f01cd0b1feb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
    #7  0x00007f01cceecf1a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
    #8  0x00007f01cdc6d295 in  () at /usr/lib64/libQt5DBus.so.5
    #9  0x00007f01ccef19e9 in  () at /usr/lib64/libQt5Core.so.5
    #10 0x00007f01c8386744 in start_thread () at /lib64/libpthread.so.0
    #11 0x00007f01cc5e8aad in clone () at /lib64/libc.so.6
    
    Thread 1 (Thread 0x7f01d24448c0 (LWP 29332)):
    [KCrash Handler]
    #6  0x00007f01cd07f1c0 in  () at /usr/lib64/libQt5Core.so.5
    #7  0x00007f01cd07f49f in  () at /usr/lib64/libQt5Core.so.5
    #8  0x00007f01cd086339 in  () at /usr/lib64/libQt5Core.so.5
    #9  0x00007f01cd0ddbc1 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
    #10 0x00007f01cd154284 in QAbstractItemModel::rowsRemoved(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) () at /usr/lib64/libQt5Core.so.5
    #11 0x00007f01cd062b31 in QAbstractItemModel::endRemoveRows() () at /usr/lib64/libQt5Core.so.5
    #12 0x00007f01a27d655f in TaskManager::TaskGroupingProxyModel::Private::sourceRowsAboutToBeRemoved(QModelIndex const&, int, int) () at /usr/lib64/libtaskmanager.so.6
    #13 0x00007f01a27d90e9 in  () at /usr/lib64/libtaskmanager.so.6
    #14 0x00007f01cd0ddbc1 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
    #15 0x00007f01cd154234 in QAbstractItemModel::rowsAboutToBeRemoved(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) () at /usr/lib64/libQt5Core.so.5
    #16 0x00007f01cd0622b4 in QAbstractItemModel::beginRemoveRows(QModelIndex const&, int, int) () at /usr/lib64/libQt5Core.so.5
    #17 0x00007f01cd080e1d in  () at /usr/lib64/libQt5Core.so.5
    #18 0x00007f01cd084add in  () at /usr/lib64/libQt5Core.so.5
    #19 0x00007f01cd085531 in QSortFilterProxyModel::invalidateFilter() () at /usr/lib64/libQt5Core.so.5
    #20 0x00007f01a27d2ac5 in TaskManager::TaskFilterProxyModel::setVirtualDesktop(unsigned int) () at /usr/lib64/libtaskmanager.so.6
    #21 0x00007f01a27f9cec in  () at /usr/lib64/libtaskmanager.so.6
    #22 0x00007f01a27fac7b in TaskManager::TasksModel::qt_metacall(QMetaObject::Call, int, void**) () at /usr/lib64/libtaskmanager.so.6
    #23 0x00007f01cfe9e7fb in QQmlBinding::write(QQmlPropertyData const&, QV4::Value const&, bool, QFlags<QQmlPropertyPrivate::WriteFlag>) () at /usr/lib64/libQt5Qml.so.5
    #24 0x00007f01cfea026a in QQmlBinding::update(QFlags<QQmlPropertyPrivate::WriteFlag>) () at /usr/lib64/libQt5Qml.so.5
    #25 0x00007f01cfea03be in QQmlBinding::expressionChanged() () at /usr/lib64/libQt5Qml.so.5
    #26 0x00007f01cfe77127 in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () at /usr/lib64/libQt5Qml.so.5
    #27 0x00007f01cfe252b4 in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) () at /usr/lib64/libQt5Qml.so.5
    #28 0x00007f01cd0dd963 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
    #29 0x00007f01cd0de1d3 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
    #30 0x00007f01cf7a727e in KWindowSystem::currentDesktopChanged(int) () at /usr/lib64/libKF5WindowSystem.so.5
    #31 0x00007f01ad4763e0 in  () at /usr/lib64/qt5/plugins/kf5/org.kde.kwindowsystem.platforms/KF5WindowSystemX11Plugin.so
    #32 0x00007f01cd0b1280 in QAbstractEventDispatcher::filterNativeEvent(QByteArray const&, void*, long*) () at /usr/lib64/libQt5Core.so.5
    #33 0x00007f01bddf3be4 in QXcbConnection::handleXcbEvent(xcb_generic_event_t*) () at /usr/lib64/libQt5XcbQpa.so.5
    #34 0x00007f01bddf5c3b in QXcbConnection::processXcbEvents() () at /usr/lib64/libQt5XcbQpa.so.5
    #35 0x00007f01cd0df176 in QObject::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
    #36 0x00007f01ce03ce3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
    #37 0x00007f01ce04149a in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
    #38 0x00007f01cd0b3fd5 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
    #39 0x00007f01cd0b5dba in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib64/libQt5Core.so.5
    #40 0x00007f01cd104c93 in  () at /usr/lib64/libQt5Core.so.5
    #41 0x00007f01c7e69134 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
    #42 0x00007f01c7e69388 in  () at /usr/lib64/libglib-2.0.so.0
    #43 0x00007f01c7e6942c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
    #44 0x00007f01cd10431c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
    #45 0x00007f01cd0b1feb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
    #46 0x00007f01cd0b9ed6 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
    #47 0x0000000000424de6 in main ()

Happy to provide more info if needed.

**Comment by psifidotos** [comment] 2017-07-20 00:36
do you have virtualbox running when the crash occurs?

**Comment by devillemereuil** [comment] 2017-07-20 00:45
No. Here's a list of mostly used software on this machine: Chrome, Kmail, Dolphin, Okular, Kile, Rkward. I've had the feeling that crashes are more frequent when Kile and/or Rkward are used, but never could confirm this due to the highly random nature of the thing.

**Comment by devillemereuil** [comment] 2017-07-20 00:47
Might be important: "Raise dock on desktop change" is activated.

**Comment by psifidotos** [comment] 2017-07-20 00:53
this is a duplicate of #589 , it is the same crash lets keep the discussion there... I have opened a bug report also at bugs.kde.org

**Closed by psifidotos** 2017-07-20 00:53 UTC
Labels: needsinfo
