### ISSUE TITLE
Fork folderview in order to work correctly with Latte  parabolic effect

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#83] opened 2017-01-18 18:14 UTC
test animation on folderview
https://youtu.be/YtdWR8pXHto

**Comment by psifidotos** [comment] 2017-01-19 19:32
this is not folderview, it is the icon applet... As referenced before, upstream bug..

Nonetheless if you want launchers to zoom ok for your, drop them on the tasks plasmoid and change their position afterwards... Zoom works just fine for launchers inside the task plasmoid...

**Comment by psifidotos** [comment] 2017-01-19 20:22
@JenaPlinsky  I checked your lattedock-appletsrc file, you are right these are folderviews and they point to locations... Only way for this to be fixed is for someone to fork the folderview and replace some of the icon code...

**Comment by JenaPlinsky** [comment] 2017-01-19 20:22
No you're wrong, it is a folder view applet and I noticed that the animation is smooth when icons are at their maximum size, while it is not smooth, when the panel is expanded, and the icons will shrink
...in this case CAD is a category of things  ....and will be added as folderview
![screenshot_20170119_204940](https://cloud.githubusercontent.com/assets/24593950/22123737/144e0562-de8d-11e6-81c4-860473a8d159.png)
![screenshot_20170119_210434](https://cloud.githubusercontent.com/assets/24593950/22123288/663efab8-de8b-11e6-9e33-e0346d6ac243.png)

**Comment by psifidotos** [comment] 2017-01-19 20:27
> No you're wrong, it is a folder view applet 

yeah, you are right as I mentioned at my latest post

> that the animation is smooth when icons are at their maximum size, while it is not smooth, when the panel is expanded, and the icons will shrink

I dont disagree with you that this occurs but this is definitely a folderview bug and nothing to do with Latte. Latte can not even workaround this... This is because of plasma developers decisions about icon sizes handling. Why arent you opening a bug at bugs.kde.org?

**Comment by JenaPlinsky** [comment] 2017-01-19 20:58
Well yes sure I'll do it !!
I wanted to be sure that the problem was no Latte
thanks a lot

**Comment by JenaPlinsky** [comment] 2017-01-19 21:26
applet size = 64pixel  ---> scaling is smooth
plugin=org.kde.plasma.**icon**   and  plugin=org.kde.plasma.**folder**

applet size< 64pixel  ---> scaling is no smooth
plugin=org.kde.plasma.**icon**   and  plugin=org.kde.plasma.**folder**

Since **both** plugins behave the same, in which team I should turn the problem? .folderview ... plasma or other

**Comment by psifidotos** [comment] 2017-01-19 21:49
I really dont know...
for plasma this is a design decision and is not considered a bug. This affects all plasmoids using  compact representation mechanism of plasma by using plasma icons

**Comment by audoban** [comment] 2017-01-19 23:58
This is not a bug, and I doubt it will be fixed. Because the icons scale with standard sizes, 32, 48, 64 etc. These are done on purpose by plasma. In addition, the plasma icons use integer values for sizes, Latte uses floating point values, therefore the effect is more smooth with Latte plasmoid.

What the user must do is block the zoom effect for the plasmoid, But there is also another solution and is to create a folderview that is compatible with the zoom effect of Latte, but we do not have the time to make a folderview fork.

**Comment by JenaPlinsky** [comment] 2017-01-20 06:35
Guys thank a lot !!!

**Comment by JenaPlinsky** [comment] 2017-01-22 21:11
Hey guys, I just made a request for cooperation to the plasma teem to evaluate this type of problem. I just hope that they understand me ;) Ciaoo

**Comment by psifidotos** [comment] 2017-01-24 19:38
@JenaPlinsky do you have the link of the bug for this?

**Comment by JenaPlinsky** [comment] 2017-01-24 19:47
https://bugs.kde.org/show_bug.cgi?id=375423

**Comment by psifidotos** [comment] 2017-01-24 19:50
:+1:

**Comment by JenaPlinsky** [comment] 2017-03-04 03:44
I tried somewhat of everything, but no one answers, Have you  suggestions to change something?
Why it has been marked as closed ?
![screenshot_20170304_042936](https://cloud.githubusercontent.com/assets/24593950/23575813/fafbc080-0093-11e7-9b1e-c6201874c642.png)

**Comment by psifidotos** [comment] 2017-03-04 06:23
As I had mentioned very early in  this discussion the behavior of folderview at Latte happens because of the core design decisions around icon sizes at the entire plasma.

they wont change the plasma core design decisions so they dont consider it a bug, not even an enhancement.

**Comment by psifidotos** [comment] 2017-03-04 06:32
all enhacements and bugs that are not Latte faults and have been reported upstream but there isnt an upstream movememt for some time are closed. This keeps the latte issues clean. 

Another way to go here is to update the perspective. If someone of the latte developers appears to help then ok, but if no action exists for some time it will be closed.

All enhancements that dont get the attention of Latte developers after some time of no action are closed

**Comment by JenaPlinsky** [comment] 2017-03-04 08:37
Is a great pity that the plasma team, does not come into Latte meeting although they will certainly have their reasons seen the great work they do.
Ok thanks for the clarification

**Comment by JenaPlinsky** [comment] 2017-03-04 09:03
I wonder, but you can not create a script that parse the properties of the applets in "lattedock-appletsrc" and once recovered the position of the icon with max resolution, use this to recreate the icons structure necessary to Latte ? ( being understood, that I have no idea how it works latte, and thus, I might say things that make no sense )

**Comment by psifidotos** [comment] 2017-03-04 09:58
plasma forces the use of icons step besaded on the theme used e.g.24, 36, 48, 64 nothing in between... in plasma can not exist and icon of size 34 or 44...

sorry, nothing can be done from our side...

**Comment by psifidotos** [comment] 2017-05-02 09:08
I conside this dead...

**Comment by psifidotos** [comment] 2017-05-16 09:03
@JenaPlinsky I need a favor concerning this...

I found a way  to workaround this I think... I uploaded two commits in master branch that implement a part of the workaround. I think you are using plasma 5.10 beta.
Can you please check the folderView animation and behavior in general and what happens with the animation with our latest master? 
The same also please and with launchers that are outside our Tasks plasmoid...

There is a chance that we can fix this whole mess a bit for Latte 0.7

thanks again...

**Closed** 2017-05-16 16:39 UTC
Labels: enhancement

**Comment by psifidotos** [comment] 2017-05-16 16:43
a folderview at 192px with smooth animation... :) and a launcher applet (telegram) that doesnt break its animation.... ;)

![image](https://cloud.githubusercontent.com/assets/2216474/26117650/e066b278-3a6f-11e7-8bfd-f1156e07c5fb.png)
