### ISSUE TITLE
Icons "dive" upon launch

### ISSUE THREAD

**Issue by MPE2016** [psifidotos/Latte-Dock#454] opened 2017-05-10 10:40 UTC
Hi there,

I have no other way of describing what i think is happening, so I included a small video that is pretty self-explanatory. I am using Manjjaro Linux (plasma 5.9.4) and Latte Dock 6.87.

Otherwise, I think you guys have made an amazing dock!

If you have any questions, feel free to ask!

[record.zip](https://github.com/psifidotos/Latte-Dock/files/989471/record.zip)

**Comment by psifidotos** [comment] 2017-05-10 13:47
@MPE2016 I cant reproduce with our master branch version...

what version are you using?

**Comment by psifidotos** [comment] 2017-05-11 17:59
fixed in master...

**Closed by psifidotos** 2017-05-11 17:59 UTC
Labels: needsinfo
