### ISSUE TITLE
Latte-dock video testing in debug mode

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#181] opened 2017-02-19 12:29 UTC
it is interesting to see with **VLC** **frame** by **frame** from minute **5:06** to **5:27**

there is nothing special, but you comprede well the dynamic of different things, although you know them already seen that it is the fruit in your efforts
the dock activation is regular?

https://youtu.be/zj-RWsVckmE

**Comment by psifidotos** [comment] 2017-02-19 12:55
> the dock activation is regular?

what do you mean ?

**Comment by JenaPlinsky** [comment] 2017-02-19 13:06
:) Nothing of special !!!!  just sometimes I noticed a light flickering on the edge of the screen, a slight hesitation before the dock rise
I do not know if there is space for more cleanings or if it was just mine impression

**Comment by psifidotos** [comment] 2017-02-19 18:20
> :) Nothing of special !!!! just sometimes I noticed a light flickering on the edge of the screen, a slight hesitation before the dock rise
> I do not know if there is space for more cleanings or if it was just mine impression

Yep!! I found a bug with the mask based on that video... when the mouse goes to the bottom edge the mask **shouldnt** go up without increasing its size... that was a wrong placement with consequences... it could be the reason the dock sometimes didnt raise !!! :)

thank u!!!!

fixed in master.... you shouldnt be able to reproduce 5:06-5:27

**Comment by JenaPlinsky** [comment] 2017-02-19 18:41
Great !!! The dock rise up trigger event, now seems decidedly more smooth !!!!

**Closed** 2017-02-19 19:13 UTC
