### ISSUE TITLE
very rare in startup phase of autostart folder a second dock is appearing on top

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#75] opened 2017-01-15 15:07 UTC
I dont have my infos when this occurs and in what circumstances....

**TEMP SOLUTION**
**_Until this is tracked down, users can use instead the plasma session restore feature_**

**Comment by audoban** [comment] 2017-01-16 06:12
I can not reproduce it. Then I do not know how to fix it.

**Comment by psifidotos** [comment] 2017-01-16 09:54
> I can not reproduce it. Then I do not know how to fix it.

me neither, there is a discussion with a user, but I can understand when it occurs:
https://github.com/psifidotos/Latte-Dock/issues/66

**Comment by 0140454** [comment] 2017-01-19 00:23
I think i meet the similar situation.

After executing `latte-dock`, I reboot my computer without closing it.
There are many unusable dock on top edge after reboot.

I have seen #66, and I think it is not caused by multiple instances of Latt Dock because we can know there is only one instance at that time in video.

https://youtu.be/b0jvvYz0GNo

**Comment by JenaPlinsky** [comment] 2017-01-19 18:14
TEST:
`
distro openSUSE thumbleweed
Plasma 5.8.85
Framework 5.31.0
QT 5.7.1
kernel 4.8.3.1 Vanilla
64 bit
latte-dock Version 0.5.91 Alpha installed from RPM
`


close latte-dock process
sudo killproc latte-dock:
![screenshot_20170119_190942](https://cloud.githubusercontent.com/assets/24593950/22119263/2e75d99a-de7b-11e6-87a1-700b3e1e4e90.png)

search latte-dock:
![screenshot_20170119_181046](https://cloud.githubusercontent.com/assets/24593950/22118238/49909ebc-de77-11e6-9e97-427a0eb6c416.png)

remove latte-dock:
![screenshot_20170119_181211](https://cloud.githubusercontent.com/assets/24593950/22118250/50fe4d70-de77-11e6-8486-33f5e93d5834.png)

search latte-doc ...ok now is not installed:
![screenshot_20170119_181300](https://cloud.githubusercontent.com/assets/24593950/22118274/6302cf28-de77-11e6-990d-8d94ce38ac29.png)


delete files:
[kactivitymanagerd-pluginsrc.txt](https://github.com/psifidotos/Latte-Dock/files/717332/kactivitymanagerd-pluginsrc.txt)
[kactivitymanagerdrc.txt](https://github.com/psifidotos/Latte-Dock/files/717336/kactivitymanagerdrc.txt)
[kactivitymanagerd-switcher.txt](https://github.com/psifidotos/Latte-Dock/files/717333/kactivitymanagerd-switcher.txt)
[Latte Dock-appletsrc.txt](https://github.com/psifidotos/Latte-Dock/files/717337/Latte.Dock-appletsrc.txt)
[plasma-org.kde.plasma.desktop-appletsrc.txt](https://github.com/psifidotos/Latte-Dock/files/717338/plasma-org.kde.plasma.desktop-appletsrc.txt)

reinstall latte-dock:
![screenshot_20170119_181406](https://cloud.githubusercontent.com/assets/24593950/22118280/68aa41d6-de77-11e6-92f9-5b8d80c63743.png)

reboot:
autostart latte-dock on kde login:
It always happens the same thing !!!! two dock panel !!!
![screenshot_20170119_184049](https://cloud.githubusercontent.com/assets/24593950/22118898/c7793210-de79-11e6-9b3c-38e8e382141a.png)

**Comment by psifidotos** [comment] 2017-01-19 19:56
unfortunatelly, I can not reproduce....
I am using Leap 42.2 with Plasma 5.8.5 and frameworks 5.29

`kactivitymanagerd-pluginsrc.txt`
`kactivitymanagerdrc.txt`
`kactivitymanagerd-switcher.txt`
`plasma-org.kde.plasma.desktop-appletsrc.txt `

these are irrelevant with Latte... Latte is a stadalone executable outside plasma so plasma is not touched from Latte and vice versa... You dont have to break your workflow

`Latte Dock-appletsrc.txt`

this is all is needed in order to restore to default behavior. We would like you to confirm the following:

- close Latte
- remove Latte Dock-appletsrc **or** lattedock-appletrc if you are using master branch
- open Latte

that is all... Is the problem still there?

**Comment by psifidotos** [comment] 2017-01-19 20:02
@JenaPlinsky 

by opening your Latte Dock-appletsrc in the end of the file exist:

```
[Containments][19]
activityId=
formfactor=0
immutability=1
lastScreen=-1
location=0
plugin=org.kde.latte.containment
timerHide=700
timerShow=200
visibility=2
wallpaperplugin=org.kde.image

[Containments][20]
activityId=
formfactor=0
immutability=1
lastScreen=-1
location=0
plugin=org.kde.latte.containment
timerHide=700
timerShow=200
visibility=2
wallpaperplugin=org.kde.image

[Containments][20][ConfigDialog]
DialogHeight=442
DialogWidth=382
```

these are to LatteDocks on top... how are they were created? I have totally no idea....

**Comment by JenaPlinsky** [comment] 2017-01-19 20:50
by following the steps that you indicated to me, everything works fine
[Latte Dock-appletsrc.txt](https://github.com/psifidotos/Latte-Dock/files/717735/Latte.Dock-appletsrc.txt)


...but if I reboot the problem reoccurs

**Comment by JenaPlinsky** [comment] 2017-01-19 21:04
the strange thing is that this thing only happens to me or a few others
 ... perhaps I should switched to opensuse 42.2 ;)

**Comment by psifidotos** [comment] 2017-01-19 21:27
> ...but if I reboot the problem reoccurs

So this occurs only on plasma start up?
What are using, plasma session restore or .config/autostart folder?

**Comment by JenaPlinsky** [comment] 2017-01-19 22:45
.config/autostart folder
yess it happens only on start-up event 

if I only kill its process and restart inside plasma session nothing happens

**Comment by audoban** [comment] 2017-01-19 23:41
Hello @JenaPlinsky 

I think that Location is wrong, the containment **19** and the  **20** having **location == Plasma::Types::Floating**

Please replace your config file with this.
```
[Containments][19]
activityId=
formfactor=0
immutability=1
lastScreen=-1
location=3
plugin=org.kde.latte.containment
timerHide=700
timerShow=200
visibility=2
wallpaperplugin=org.kde.image

[Containments][20]
activityId=
formfactor=0
immutability=1
lastScreen=-1
location=4
plugin=org.kde.latte.containment
timerHide=700
timerShow=200
visibility=2
wallpaperplugin=org.kde.image

[Containments][20][ConfigDialog]
DialogHeight=442
DialogWidth=382
```

Now you should have a dock on Top edge and another on the Bottom edge.

If this is true, The problem should be that Latte saved the configuration with a **wrong location**.

**Comment by psifidotos** [comment] 2017-01-20 14:22
> config/autostart folder
> yess it happens only on start-up event

can you also try the plasma session restore without the autostart directory? : 

- remove latte from .config/autostart
- enable at plasma systemsettings -> Startup/shutdown -> desktop session -> restore previous session
- start latte if it isnt running
- log out
- log in again
- does this issue remain ?

**Comment by JenaPlinsky** [comment] 2017-01-21 08:28
Ciao  Psifidotos I followed your instructions and everything works correctly. So, the problem would appear to be limited to autostart, right ?

**Comment by JenaPlinsky** [comment] 2017-01-21 08:41
Aahh sorry I forgot! Meanwhile I switched to Plasma 5.9.90

**Comment by psifidotos** [comment] 2017-01-21 08:55
> Ciao Psifidotos I followed your instructions and everything works correctly. So, the problem would appear to be limited to autostart, right ?

yes, if this is happening only with autostart folder this is limited to it...

> Aahh sorry I forgot! Meanwhile I switched to Plasma 5.8.90

you mean that the autostart folder issue could be relevant to 5.8.90 or that is fixed totally with 5.8.90?

**Comment by JenaPlinsky** [comment] 2017-01-21 09:03
Now I have replaced Latte in $HOME/.config/autostart
then reboot while **maintaining current session restore** !
and I get a strange thing
reappeared on the problem of two instances of Latte ....but now the second dock doesn't appear on the top side of the screen but overlapped to the main
**NB** just for practicality I moved one of the two left-side dock) here's the config file

![screenshot_20170121_095157](https://cloud.githubusercontent.com/assets/24593950/22173372/d8bd8088-dfc0-11e6-84d2-26a0f55bfdcb.png)
[Latte Dock-appletsrc.txt](https://github.com/psifidotos/Latte-Dock/files/721032/Latte.Dock-appletsrc.txt)

**Comment by JenaPlinsky** [comment] 2017-01-21 09:09
No, in the passage from  5.8.95 to 5.9.90, as you see, nothing has changed I always two instance ....except for the fact that now are overlapping

**Comment by JenaPlinsky** [comment] 2017-01-21 10:10
Now I recreated the original condition and thus:
Autostart and start with empty session

and here again the second instance !!!  ...but this time, as before, it is placed on the top

**Comment by psifidotos** [comment] 2017-01-21 11:45
> Now I have replaced Latte in $HOME/.config/autostart then reboot while maintaining current session restore ! and I get a strange thing reappeared on the problem of two instances of Latte ....but now the second dock doesn't appear on the top side of the screen but overlapped to the main

this could be because two different Latte instances are starting one from autostart folder and one from plasma session.

> No, in the passage from 5.8.95 to 5.9.90, as you see, nothing has changed I always two instance ....except for the fact that now are overlapping

so autostart folder issue isnt fixed from 5.8.95 to 5.9.90 ?

do you confirm that by just using the plasma session solution this problem is fixed?

**Comment by JenaPlinsky** [comment] 2017-01-21 13:01
-  I note that I am using a config file dirt
-  removed from the config file (dirt)    ...extra plugins = org.kde.latte.containment
and so now the config file contains only one instance of Latte

- then I removed the $HOME/.config/autostart/latte-dock.desktop (**latte-dock %u**)

- then I set the restoration of the previous session

- at the end logout and then login

now Latte continues to have only one Latte cointainments

I can confirm that...
by starting the previous session that was using Latte
or by starting with an empty session and then run Latte,
well ...everything works fine

The important thing is never use a dirty configuration file especially if we use "restore prevous session"

**Comment by JenaPlinsky** [comment] 2017-01-21 13:09
I also noted that in the configuration file, when combined with the autostart, I found inside it more than two containers Latte ... I have the impression that for each login it adds one new instance

**Comment by psifidotos** [comment] 2017-01-21 14:59
> The important thing is never use a dirty configuration file especially if we use "restore prevous session

I think that a simpler answer is that autostart folder is not supported yet and breaks the experience... if the user sticks with plasma restore session from start, this problem wont appear

**Comment by psifidotos** [comment] 2017-01-21 15:01
> I also noted that in the configuration file, when combined with the autostart, I found inside it more than two containers Latte ... I have the impression that for each login it adds one new instance

this is this bug and needs a developer to track it down and fix

**Comment by omni6** [comment] 2017-01-23 22:21
hello, i am also affected by this multiple docks at startup bug. i noticed that when i close the annoying (sometimes up to 15!!) glitching docks i get changes in my lattedock-appletsrc. Maybe it is useful for you to see what is changing...

```
--- -	2017-01-23 23:09:04.946100337 +0100
+++ /home/jan/.config/lattedock-appletsrc	2017-01-23 23:09:04.063157424 +0100
@@ -159,6 +159,10 @@
 visibility=2
 wallpaperplugin=org.kde.image
 
+[Containments][26][ConfigDialog]
+DialogHeight=488
+DialogWidth=450
+
 [Containments][27]
 activityId=
 formfactor=0
@@ -171,6 +175,10 @@
 visibility=2
 wallpaperplugin=org.kde.image
 
+[Containments][27][ConfigDialog]
+DialogHeight=488
+DialogWidth=450
+
 [Containments][28]
 activityId=
 formfactor=0
@@ -219,6 +227,10 @@
 visibility=2
 wallpaperplugin=org.kde.image
 
+[Containments][32][ConfigDialog]
+DialogHeight=488
+DialogWidth=450
+
 [Containments][33]
 activityId=
 formfactor=0
@@ -231,6 +243,10 @@
 visibility=2
 wallpaperplugin=org.kde.image
 
+[Containments][33][ConfigDialog]
+DialogHeight=488
+DialogWidth=450
+
 [Containments][34]
 activityId=
 formfactor=0
@@ -270,6 +286,10 @@
 visibility=2
 wallpaperplugin=org.kde.image
 
+[Containments][37][ConfigDialog]
+DialogHeight=488
+DialogWidth=450
+
 [Containments][38]
 activityId=
 formfactor=0
@@ -282,6 +302,10 @@
 visibility=2
 wallpaperplugin=org.kde.image
 
+[Containments][38][ConfigDialog]
+DialogHeight=488
+DialogWidth=450
+
 [Containments][39]
 activityId=
 formfactor=0
```

**Comment by psifidotos** [comment] 2017-01-24 15:33
> and here complete lattedock-appletsrc ... so many entries for systemtray!?

this doesnt look like the previous mentioned issue.

- Are you using master?
- Have you tried the previous mentioned solution ? ( close latte, delete its configuration, remove latte from autostart folder, start latte, set plasma session restore from systemsettings, log out, log in)

**Comment by omni6** [comment] 2017-01-24 17:47
its the same issue shown in this yt [video](https://www.youtube.com/watch?v=b0jvvYz0GNo&feature=youtu.be) from 0140454. here is a [screenshot](http://imgur.com/a/sTKq2) from my desktop.

> - Are you using master?
> - Have you tried the previous mentioned solution ? ( close latte, delete its configuration, remove latte from autostart folder, start latte, set plasma session restore from systemsettings, log out, log in)

yes and yes, the only way to get the docks so i configured is starting it manually.
i am not sure but i believe i noticed the issue since pulling git on Jan 17, 2017

**Comment by psifidotos** [comment] 2017-01-24 18:33
@omni6, I made a guess why this could happening, can you try branch **fix75** ?

**Comment by omni6** [comment] 2017-01-24 19:00
good guess i would say its solved! 

 restoring session and autostart works flawless now!!

**Comment by psifidotos** [comment] 2017-01-24 19:09
nice!!! lets merge then, and hope for the best !! ;)

**Closed** 2017-01-24 19:10 UTC
Labels: bug

**Comment by omni6** [comment] 2017-01-24 19:12
:+1:

**Comment by JenaPlinsky** [comment] 2017-01-24 22:22
Psifidotos and Arduban Now works great !!! very compliments
