### ISSUE TITLE
semantic icons issue

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#88] opened 2017-01-22 21:16 UTC
kodi icon appears on all activities although not Shared

**Comment by psifidotos** [comment] 2017-01-22 21:38
The kodi launcher or window?

**Comment by JenaPlinsky** [comment] 2017-01-22 21:41
launcher

**Comment by psifidotos** [comment] 2017-01-22 21:43
You want the kodi launcher to be only on specific activity?

**Comment by JenaPlinsky** [comment] 2017-01-22 21:46
It is already well set, only that it appearing on all activities

**Comment by JenaPlinsky** [comment] 2017-01-22 21:48
![screenshot_20170122_224740](https://cloud.githubusercontent.com/assets/24593950/22186358/d0876700-e0f4-11e6-85d9-89ec9807dd40.png)

**Comment by psifidotos** [comment] 2017-01-22 21:49
You have uncheck for this launcher the, show on all avtivities option, from its context menu but it still shows on all activities? Can you upload your lattedock-appletsrc file?

**Comment by psifidotos** [comment] 2017-01-22 21:53
Can you upload your lattedock-appletsrc file?

**Comment by JenaPlinsky** [comment] 2017-01-22 21:55
Yes
[Latte Dock-appletsrc.txt](https://github.com/psifidotos/Latte-Dock/files/722294/Latte.Dock-appletsrc.txt)

**Comment by psifidotos** [comment] 2017-01-22 22:00
The kodi laucher is not clean contains also the icondata in its name... this could be a distro issue concerning kodi.desktop file or plasma's libtaskmanager handling. Users have reported it also with skype

**Comment by JenaPlinsky** [comment] 2017-01-22 22:07
Now I switched to leap opensuse 42.2 for problems with the intel driver. I think

**Comment by psifidotos** [comment] 2017-01-22 22:15
We use the same, i will test and if it appears also for me I will open a bug report for libtaskmanager. One way to solve this is to clean the kodi.desktop by yourself.

**Comment by psifidotos** [comment] 2017-01-22 22:18
Something irrelevant, if you want the three circles applet in the beginning of the dock and the weather applet to look better you can add them a shadow from dock's.config window by setting shadows everywhere...

**Comment by JenaPlinsky** [comment] 2017-01-22 22:24
Ohhh yeah so that's better;)

**Comment by JenaPlinsky** [comment] 2017-01-22 22:26
a question ? with a leap, sometimes it happens that the milk freeze?

**Comment by psifidotos** [comment] 2017-01-22 22:28
I havent noticed something in my system

**Comment by JenaPlinsky** [comment] 2017-01-22 22:32
It also happened in tumbleweed but much more often. I know it does not depend on Latte ;)

Thanks a lot

**Comment by psifidotos** [comment] 2017-01-24 15:43
@JenaPlinsky, I installed kodi at my openSUSE Leap 42.2 but I dont have that issue.
Have you installed an alternative version for kodi e.g. from Packman ?
Can you send the file?
/usr/share/applications/kodi.desktop

**Comment by JenaPlinsky** [comment] 2017-01-24 17:03
[kodi.desktop.txt](https://github.com/psifidotos/Latte-Dock/files/727355/kodi.desktop.txt)

**Comment by psifidotos** [comment] 2017-01-24 18:01
I really dont know from where this desktop file is or if the metadata containing follow the standard..

You can try mine from the official repos:

**Comment by psifidotos** [comment] 2017-01-24 18:07
[kodi.desktop.txt](https://github.com/psifidotos/Latte-Dock/files/727545/kodi.desktop.txt)

**Comment by psifidotos** [comment] 2017-01-24 18:19
@JenaPlinsky also I would like you to test something!!!!

The problem appears if your drag n' drop the kodi icon right?
Can you try to open kodi and then set is as a launcher through its context menu by right clicking on it ?
Does the same issues still appears?

**Comment by JenaPlinsky** [comment] 2017-01-24 19:01
I have not dragged the icon, but I used the contextual menu "Show luncher WHEN NOT runnung" 
![screenshot_20170124_194651](https://cloud.githubusercontent.com/assets/24593950/22261803/9ef36808-e26e-11e6-950d-6d4e54fb282b.png)
![screenshot_20170124_194810](https://cloud.githubusercontent.com/assets/24593950/22261810/a38c6b8a-e26e-11e6-85fa-0da10885bca6.png)

I repeated what I had done, and now kodi launcher works fine
Now I notice a strange thing, the icon of kodi is now different 
....mmmmhhh It maybe that I have accidentally updated kodi by a "zypper up"

**Comment by psifidotos** [comment] 2017-01-24 19:12
@JenaPlinsky did you use my desktop file ?

**Comment by JenaPlinsky** [comment] 2017-01-24 19:17
oops sorry I had not seen !!!! I do not know why it works now !!! Perhaps guilt is of a zypper up ..... now I look at your file to understand the differences

**Comment by psifidotos** [comment] 2017-01-24 19:20
@JenaPlinsky I believe that neither your sent desktop file and mine are a good reference... We needed the desktop file that was really creating the point... I think that in the desktop file there were icon information, this is why the icons now have changed!! :)

so, let's close it for now until we find a launcher that has this issue again... I will then report upstream to plasma and see if this is plasma bug or distro one...

**Comment by JenaPlinsky** [comment] 2017-01-24 19:37
Ok aspettiamo e vediamo ;) great psifidotos

**Comment by psifidotos** [comment] 2017-01-24 19:37
;)

**Comment by JenaPlinsky** [comment] 2017-01-26 19:36
here we are 
kdevelop and kate launchers setted for the only "Develop" activity,
are now also shown, in the other activities
[lattedock-appletsrc.txt](https://github.com/psifidotos/Latte-Dock/files/733385/lattedock-appletsrc.txt)
![screenshot_20170126_202550](https://cloud.githubusercontent.com/assets/24593950/22347140/10edd918-e407-11e6-91ff-81f409e1cb52.png)

**Comment by JenaPlinsky** [comment] 2017-01-26 19:46
sorry, kate's launcher works fine the problem is only refered to the kdevelop's launcher

**Comment by psifidotos** [comment] 2017-01-26 20:02
Perfect!!!!

Send me your kdevelop.desktop file !!!

**Comment by JenaPlinsky** [comment] 2017-01-26 20:12
[KDevelop.txt](https://github.com/psifidotos/Latte-Dock/files/733479/KDevelop.txt)

**Comment by psifidotos** [comment] 2017-01-26 20:32
I dont think this is the one...
have you changed the icon for kdevelop by yourself? there could be a secondary desktop file for kdevelop in .local directoru

**Comment by psifidotos** [comment] 2017-01-26 20:45
I think, this is the one... file:///home/Ivan/.local/share/applications/kdevelop.desktop

**Comment by psifidotos** [comment] 2017-01-26 20:59
@JenaPlinsky  please test branch **fix88** I added a workaround for this and I found and a small bug from our side!!! Test it with launchers and tell me!!! ;) but I think it is ok now !!!

**Comment by JenaPlinsky** [comment] 2017-01-26 21:02
i've run launcher from kde menu
![screenshot_20170126_215549](https://cloud.githubusercontent.com/assets/24593950/22350116/e78a65e4-e412-11e6-9f0e-3dc92e3e2ad9.png)

![screenshot_20170126_215755](https://cloud.githubusercontent.com/assets/24593950/22350138/e9bf48f2-e412-11e6-98dd-f78eac9dd579.png)
here is local kdevelop
[kdevelop.desktop.txt](https://github.com/psifidotos/Latte-Dock/files/733581/kdevelop.desktop.txt)

**Comment by psifidotos** [comment] 2017-01-26 21:06
In order for the fix to work you must remove  and readd the launcher...

**Comment by psifidotos** [comment] 2017-01-26 21:08
and you can also test the two different ways of adding the launcher if it works ok... by drag n' drop and through context menu

**Comment by JenaPlinsky** [comment] 2017-01-26 21:23
I noticed that :
prev Milk
   item "show launcher on all activities" By **default** was **unchecked**

fix88
   item "show launcher on all activities" By **default** is now **checked**

in any case ...now everything works fine ... fixed

but only it fix kdevelop? ... or it could happen again?

**Comment by JenaPlinsky** [comment] 2017-01-26 21:26
Both methods work the same way

**Comment by JenaPlinsky** [comment] 2017-01-26 21:30
but it was a regression? days ago it seemed that worked well

**Comment by psifidotos** [comment] 2017-01-26 21:35
this is a general fix for all such cases... 

> fix88 item "show launcher on all activities" By default is now checked

this should have been the default behavior i dont know why this was broken in the past..

**Comment by psifidotos** [comment] 2017-01-26 21:38
> days ago it seemed that worked well

I dont know... the issue is very specific to desktop files that contain icon datas or have been set by the user to alternative  icons... i think this must have been fixed all over around

**Comment by JenaPlinsky** [comment] 2017-01-26 21:45
![screenshot_20170126_223626](https://cloud.githubusercontent.com/assets/24593950/22351446/3b60566a-e418-11e6-8cbb-6c98f117bce4.png)
![screenshot_20170126_223550](https://cloud.githubusercontent.com/assets/24593950/22351449/3e0bbdf0-e418-11e6-9e72-c966f25d0eec.png)
there is a problem, you see a blank icon that if I launch opens kdevelop
anyway. there's a strange thing .... I have an open kdevelop instance and the LED under the blank icon does not signal the running instance

**Comment by psifidotos** [comment] 2017-01-26 22:16
did you delete the local instance of kdevelop.desktop file ?

I managed to reproduce this bug in my system and everything works as expected in my system... I can not reproduce the blank case you are describing... only thing I can think of is that the kdevelop.desktop at .loca/.... folder was deleted....

**Comment by psifidotos** [comment] 2017-01-26 22:17
send me your appletsrc file for the blank case

**Comment by JenaPlinsky** [comment] 2017-01-26 22:23
> did you delete the local instance of kdevelop.desktop file ?
Yes
[lattedockrc.txt](https://github.com/psifidotos/Latte-Dock/files/733735/lattedockrc.txt)

**Comment by psifidotos** [comment] 2017-01-26 22:27
this file is empty... By deleting the local instance of kdevelop the launcher lost its reference... When I described to delete the launcher and re-add it I meant to use the latte's context menu to remove the launcher from latte...

If you want to test just set for your kdevelop the icon that you had chosen before... and then try to add it in Latte... In my system this now works even with setting local png icon

**Comment by JenaPlinsky** [comment] 2017-01-26 22:33
[lattedock-appletsrc.txt](https://github.com/psifidotos/Latte-Dock/files/733771/lattedock-appletsrc.txt)

**Comment by psifidotos** [comment] 2017-01-26 22:35
ok... the file is more than clean!!! 

I suppose for the blank case you deleted,
file:///home/Ivan/.local/share/applications/kdevelop.desktop
and now it can not be found

I consider this fixed until something else appears...

**Closed** 2017-01-26 22:39 UTC
Labels: upstream

**Comment by JenaPlinsky** [comment] 2017-01-26 22:51
> By deleting the local instance of kdevelop the launcher lost its reference

Blank Icon is still present, it has never disappeared, 
...although
/home/Ivan/.local/share/applications/    is now empty

**Comment by psifidotos** [comment] 2017-01-26 22:57
Blank Icon is still present, it has never disappeared,
...although
/home/Ivan/.local/share/applications/ is now empty

this is pretty logical... because in your file there is a reference for:
file:///home/Ivan/.local/share/applications/kdevelop.desktop

that now does not exist... can you remove the blank launcher icon and afterwards readd kdevelop as launcher for Latte?

**Comment by JenaPlinsky** [comment] 2017-01-26 23:06
I beg your pardon ...you can consider the issue fixed

**Comment by psifidotos** [comment] 2017-01-26 23:10
No worries!!!

If you didnt help in testing all these bugs would have reached so many users in the futute!!!
