### ISSUE TITLE
[Top Edge + Firefox 55]  dock doesn't rise at "dodge all windows" mode

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#665] opened 2017-08-11 23:38 UTC
Top dock don't rise with "dodge all windows" mode
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1219299/video.zip)

**Comment by psifidotos** [comment] 2017-08-12 00:13
this is too general... in my system works ok... I suppose it isnt relevant to Dodge All Windows but it should happen also to Dodge Active and Auto Hide... no?

Maybe your screen needs calibration? do you miss a pixel on the top?

**Comment by psifidotos** [comment] 2017-08-12 00:14
and the touch gestures of course... in case you have enable a touch gesture for you screen top edge

**Comment by JenaPlinsky** [comment] 2017-08-12 07:12
Autohide mode has always responded fine while other modes sometimes respond others do not
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1219560/video.zip)

**Comment by psifidotos** [comment] 2017-08-12 09:03
Is this happening only with the top dock?

Can you try commits and see when this started in your system?

**Comment by psifidotos** [comment] 2017-08-12 09:57
you can try also:

1. `latte-dock -d --graphics` and see if a line is appearing on top when hidden
2. `latte-dock -d --with-window` in order to observe what are the settings of the application when the dock is not appearing

**Comment by JenaPlinsky** [comment] 2017-08-12 09:59
The videos are not perfect but it seems that the problem only occurs with the firefox decoration both with the top and with the bottom
[native_plasma_decoration.zip](https://github.com/psifidotos/Latte-Dock/files/1219653/native_plasma_decoration.zip)
[firefox_gtk3_decoration.zip](https://github.com/psifidotos/Latte-Dock/files/1219655/firefox_gtk3_decoration.zip)
[apps.zip](https://github.com/psifidotos/Latte-Dock/files/1219656/apps.zip)

**Comment by psifidotos** [comment] 2017-08-12 10:01
@JenaPlinsky the shortcut `Super+`` does it make the dock to rise?

**Comment by psifidotos** [comment] 2017-08-12 10:07
@JenaPlinsky if you change window decoration from Oxygen to Breeze does it make any difference?

**Comment by JenaPlinsky** [comment] 2017-08-12 10:21
[firefox+breeze.zip](https://github.com/psifidotos/Latte-Dock/files/1219675/firefox.breeze.zip)
I have problems as well with breeze

**Comment by JenaPlinsky** [comment] 2017-08-12 10:33
![spectacle d18224](https://user-images.githubusercontent.com/24593950/29239932-4bd6788e-7f5a-11e7-9df5-f0c1c44f3968.png)
![spectacle l18224](https://user-images.githubusercontent.com/24593950/29239937-5e394998-7f5a-11e7-82c9-76b2e39f5318.png)

**Comment by JenaPlinsky** [comment] 2017-08-12 10:44
here is the interesting parameter window in action
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1219692/video.zip)

**Comment by psifidotos** [comment] 2017-08-12 11:00
Firefox will make us crazy... :) if you move the Firefox window a little more up... in order for the Firefox decoration edge to not overlap with the Latte 1px hidden state but to overlap with the Firefox inner window title part, does the same happens?

hint - strange: the contains mouse flag is changed correctly (can you check please from ksysguard if this issue is related to high cpu usage? maybe something goes cpu crazy and the Latte animation cant catch up)

**Comment by JenaPlinsky** [comment] 2017-08-12 11:13
Do i place firefox correctly?
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1219700/video.zip)
The problem does not repeat if I move **slowly**? Did you observe? Is it strange true?

**Comment by psifidotos** [comment] 2017-08-12 11:15
you moved the firefox window lower... I wanted it upper :)

**Comment by psifidotos** [comment] 2017-08-12 11:17
can you check also that this is related to "Behave as a normal dock window" from Tweaks page?

**Comment by JenaPlinsky** [comment] 2017-08-12 11:57
> you moved the firefox window lower... I wanted it upper :)

Ahahahahah I had, well understood
Just a moment, I work hard to make the video :) Slowly, I'll do it

**Comment by JenaPlinsky** [comment] 2017-08-12 12:28
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1219749/video.zip)

[dont_behave_as_normal_dock_windows.zip](https://github.com/psifidotos/Latte-Dock/files/1219753/dont_behave_as_normal_dock_windows.zip)

**Comment by JenaPlinsky** [comment] 2017-08-12 14:05
Here is the same behavior on the Bottom dock
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1219772/video.zip)

**Comment by psifidotos** [comment] 2017-08-12 14:17
end of ideas... I have no idea why this is happening only with Firefox and I still cant reproduce with Firefox in my system... is this stable version of Firefox or the development one ?

**Comment by JenaPlinsky** [comment] 2017-08-12 16:44
This is the version that creates the problem and is installed from
http://download.opensuse.org/repositories/mozilla/openSUSE_Leap_42.3/
I searched for repo 42.2 but I get the same revision so I did not try to modify the repository
- I could, however, try to see if there are differences with the repository version 42.2
- I could try with specific packages but I dont know how to look for them
![spectacle r24961](https://user-images.githubusercontent.com/24593950/29242326-422d0e66-7f8b-11e7-9af0-be59efc4bd32.png)

This version does not create any problem I thought it was a factory version instead iys date is older
![spectacle o24961](https://user-images.githubusercontent.com/24593950/29242332-791d4490-7f8b-11e7-927d-736f1a9fbef4.png)



These are my repositories
> Il repository 'google-earth' è aggiornato.                                                                                                                                                      
> Il repository 'http://download.opensuse.org/distribution/leap/42.3/repo/oss/' è aggiornato.                                                                                                     
> Il repository 'http://download.opensuse.org/repositories/home:/audoban/openSUSE_Leap_42.2/' è aggiornato.                                                                                       
> Il repository 'home:PerryWerneck' è aggiornato.                                                                                                                                                 
> Il repository 'http://download.opensuse.org/repositories/graphics/openSUSE_Leap_42.3/' è aggiornato.                                                                                            
> Il repository 'http://download.opensuse.org/distribution/leap/42.3/repo/non-oss/' è aggiornato.                                                                                                 
> Il repository 'http://download.opensuse.org/distribution/leap/42.3/repo/oss/' è aggiornato.                                                                                                     
> Il repository 'http://download.opensuse.org/repositories/Emulators:/Wine/openSUSE_Leap_42.3/' è aggiornato.                                                                                     
> Il repository 'http://download.opensuse.org/repositories/KDE:/Extra/openSUSE_Leap_42.3/' è aggiornato.                                                                                          
> Il repository 'http://download.opensuse.org/repositories/KDE:/Frameworks5/openSUSE_Leap_42.3/' è aggiornato.                                                                                    
> Il repository 'http://download.opensuse.org/repositories/KDE:/Qt5/openSUSE_Leap_42.3/' è aggiornato.                                                                                            
> Il repository 'http://download.opensuse.org/repositories/KDE:/Qt510/openSUSE_Leap_42.3/' è aggiornato.                                                                                          
> Il repository 'http://download.opensuse.org/repositories/KDE:/Qt59/openSUSE_Leap_42.3/' è aggiornato.                                                                                           
> Il repository 'http://download.opensuse.org/repositories/KDE:/Unstable:/Applications/KDE_Unstable_Frameworks_openSUSE_Leap_42.3/' è aggiornato.                                                 
> Il repository 'http://download.opensuse.org/repositories/KDE:/Unstable:/Extra/KDE_Unstable_Frameworks_openSUSE_Leap_42.3/' è aggiornato.                                                        
> Il repository 'http://download.opensuse.org/repositories/KDE:/Unstable:/Frameworks/openSUSE_Leap_42.3/' è aggiornato.                                                                           
> Il repository 'http://download.opensuse.org/repositories/KDE:/Unstable:/Qt/openSUSE_Leap_42.3/' è aggiornato.                                                                                   
> Il repository 'http://download.opensuse.org/repositories/LibreOffice:/Factory/openSUSE_Factory/' è aggiornato.                                                                                  
> Il repository 'http://download.opensuse.org/repositories/LibreOffice:/Unstable/openSUSE_Factory/' è aggiornato.                                                                                 
> Il repository 'http://download.opensuse.org/repositories/games/openSUSE_Leap_42.3/' è aggiornato.                                                                                               
> Il repository 'http://download.opensuse.org/repositories/mozilla/openSUSE_Leap_42.3/' è aggiornato.                                                                                             
> Il repository 'http://download.opensuse.org/update/leap/42.3/non-oss/' è aggiornato.                                                                                                            
> Il repository 'http://download.opensuse.org/update/leap/42.3/oss/' è aggiornato.                                                                                                                
> Il repository 'http://download.videolan.org/pub/vlc/SuSE/Leap_42.3/' è aggiornato.                                                                                                              
> Il repository 'http://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_42.3/' è aggiornato.                                                                                                
> Il repository 'http://opensuse-guide.org/repo/openSUSE_Leap_42.3/' è aggiornato.                                                                                                                
> Il repository 'http://packman.inode.at/suse/openSUSE_Leap_42.3/' è aggiornato.                                                                                                                  
> Il repository 'skype (stable)' è aggiornato.                                                                                                                                                    
> Il repository 'snappy' è aggiornato.                                                                                                                                                            
> Il repository 'vivaldi' è aggiornato.

**Comment by psifidotos** [comment] 2017-08-12 16:58
I dont understand which version creates the problem, the developer edition or the normal one?

I have moved to Neon the last weeks...

**Comment by JenaPlinsky** [comment] 2017-08-12 17:18
> I dont understand which version creates the problem, the developer edition or the normal one?
The Normal one 55.0.1 (64bits)

> I have moved to Neon the last weeks...
Interesting, how do you feel?

**Comment by psifidotos** [comment] 2017-08-12 17:36
> The Normal one 55.0.1 (64bits)

So strange... two different firefox, only one creating the issue... Do you have any kwin rules for firefox?

> Interesting, how do you feel?

It's ok but it is too early to judge

**Comment by JenaPlinsky** [comment] 2017-08-12 17:50
> So strange... two different firefox, only one creating the issue... Do you have any kwin rules for firefox?

Nothing at all

**Comment by JenaPlinsky** [comment] 2017-08-12 18:03
Firefox standard VS developer edition
[firefox_VS_firefox_devel_edition.zip](https://github.com/psifidotos/Latte-Dock/files/1219964/firefox_VS_firefox_devel_edition.zip)

**Comment by psifidotos** [comment] 2017-08-12 19:17
hehe crazy stuff ... :) in my system I Firefox 54.0  when it is updated I will check again for this...

**Comment by JenaPlinsky** [comment] 2017-08-12 19:25
Really crazy !!!! ... as if several graphics drivers and graphics servers were not enough

**Comment by AndydeCleyre** [comment] 2017-08-13 05:50
I'm using Firefox 55.0.1 on arch, and I have a latte dock on the right side of the screen, set to dodge active.

I'm also using the [Tab Tree](https://addons.mozilla.org/en-US/firefox/addon/tab-tree/) Firefox extension, which is adding a sidebar to the right side of Firefox.

When this side bar is enabled and Firefox is maximized (or along the right edge of the screen), I can**not** raise the dock by moving the cursor to the edge of the screen. When I hide the sidebar, I can.

**Comment by JenaPlinsky** [comment] 2017-08-13 07:57
@psifidotos   
@AndydeCleyre Thanks for your support
Your reporting led me to do further investigations, and I found out that with firefox 55.0.1
I get two different behaviors depending on the open tab...

[video.zip](https://github.com/psifidotos/Latte-Dock/files/1220333/video.zip)
- customization tab
       Here I observe a correct behavior

- web page tab
        Here it interacts with the proper functioning of the dock, preventing it from rising

**Comment by psifidotos** [comment] 2017-08-13 08:37
please do me a favour both... use Plank and tell me if same thing happens... big chance it does...

**Comment by JenaPlinsky** [comment] 2017-08-13 08:44
Now I'm on irc.mozzilla.org # bugzilla
Maybe someone can tell me something

**Comment by JenaPlinsky** [comment] 2017-08-13 08:49
I'm installing plank

**Comment by JenaPlinsky** [comment] 2017-08-13 09:03
@psifidotos ...Incredible but with Plank it always rise !!

**Comment by psifidotos** [comment] 2017-08-13 09:10
that's good!!! in that case we will probably be able to fix it for Latte also

**Comment by psifidotos** [comment] 2017-08-13 09:48
Does this happen only with Dodge modes in your systems?

**Comment by psifidotos** [comment] 2017-08-13 10:06
it should be fixed, please check...

**Closed** 2017-08-13 10:05 UTC
Labels: cantreproduce, needsinfo

**Comment by JenaPlinsky** [comment] 2017-08-13 10:13
- un-rise with fast movements
 Dodge active 
 Dodge maximized
 Dodge all windows
   - it rise with very slow movements towards to the edge
   - it rises if I get to the edge, then I get out of 1 pixel and then back to the edge



- always rise
    Autohide

**Comment by psifidotos** [comment] 2017-08-13 10:14
is this based on the last commit?

**Comment by JenaPlinsky** [comment] 2017-08-13 10:39
No :) just before
Now it work very fine !!!! Great

**Comment by psifidotos** [comment] 2017-08-13 12:21
Please for everyone using Firefox 55 follow: https://bugs.kde.org/show_bug.cgi?id=383450

things look pretty serious... Firefox 55 can create endless loops with kwin and increase the cpu usage for kwin endlessly...

**Comment by JenaPlinsky** [comment] 2017-08-13 12:58
Thanks for the hint ...
For now after an hour of random browsing, both kwin and plasmashel takes about 1% CPU

The new thing I notice is instead that,
after really much time firefox seems **to me** be much less hungry than resources .... i was usually restarting firefox at fairly short intervals due to exaggerated consumption of resources

**Comment by psifidotos** [comment] 2017-08-13 17:08
the firefox bug report can be found here: https://bugzilla.mozilla.org/show_bug.cgi?id=1389953

**Comment by JenaPlinsky** [comment] 2017-08-13 17:21
Very Good report

**Comment by AndydeCleyre** [comment] 2017-08-13 23:33
Thank you! Yes the behavior is fixed here as well with latte dock `0.7.0.r11.g4c06e50`.
