### ISSUE TITLE
Improve contents visibility doesn't work

### ISSUE THREAD

**Issue by DoubleIntegral** [psifidotos/Latte-Dock#908] opened 2018-03-08 06:55 UTC
KDE Plasma Version: 5.12.2
KDE Frameworks Version: 5.43.0
Qt Version: 5.10.1
OS: Manjaro x64, 4.14.23-1
Latte 4fc3b43

Background: solid color -> black (Select "Wallpaper Type" in desktop configuration and choose "Plain color")
Layout: Extended (it's one of default layouts) https://hastebin.com/ujihodisiy.md
Color scheme: Breeze Dark
Tweaks page screenshot: https://imgur.com/a/DBdFm
Steps to reproduce: 

1. Select "Breeze Dark" color scheme.
2. Enable "Improve contents visibility" option.
3. Set background to black color or any dark wallpaper.

When "improve contents visibility" selected, all widgets are tinted to dark gray color no matter what desktop background is set
Example (solid color: black is chosen for desktop background): https://imgur.com/a/l5MOH

Contents do change color when window is maximized/snapped to desktop side and "force solid background when maximized" is turned on

**Comment by DoubleIntegral** [comment] 2018-03-08 07:05
Figured out the issue. It seems to read color scheme properties but doesn't take into account dark themes and so defaults to dark font.

**Comment by michaldybczak** [comment] 2018-03-08 07:08
Great! Will test it when the fix will be committed.

**Comment by psifidotos** [comment] 2018-03-08 09:34
> Figured out the issue. It seems to read color scheme properties but doesn't take into account dark themes and so defaults to dark font.

how did you figure that out? did you use another theme and it works as expected?

> Great! Will test it when the fix will be committed.

you are using the latest commit so there can be no fix if we dont understand why it breaks in you system...

To ckeck out, the feature should do the following, independent of the plasma theme:

1. when you use whiteish background the panel provides darkish contents
2. when you use darkish background the panel provides whiteish contents

@michaldybczak when you open the plasma Activities panel on the left the background is shown correctly in there?

**Comment by michaldybczak** [comment] 2018-03-08 09:48
I cannot answer for @DoubleIntegral. However I checked light desktop theme and the option would only turn dark fonts white, so opposite of what I noticed with dark theme. There is no dynamic font color change on either type of desktop theme.

Not sure what "activities panel on the left background" is but I panel that add widgets on the left side opens correctly. I have set my Activities to the left upper corner and it opens correctly panel to switch Activities.

**Comment by psifidotos** [comment] 2018-03-08 10:30
> and it opens correctly panel to switch Activities.

in that panel do you see the Activities background correctly? eg. https://i.ytimg.com/vi/uxaDaXW67Oo/maxresdefault.jpg

can you make a screenshot for the Latte top panel -> Tweaks page?

> EDIT: to clarify...

something breaks in your system...

**Comment by michaldybczak** [comment] 2018-03-08 11:34
I think so:

![screenshot_20180308_123357](https://user-images.githubusercontent.com/10132958/37149091-0b4f8a64-22cd-11e8-90e4-1a1071d96ce7.jpg)

**Comment by JuanManuelM** [comment] 2018-03-08 12:24
Hi. I can confirm this issue. It happens in both and light theme. There is a problem also with the global menu (Active Window Control). Backgrounds are showed ok in the activitie panel.

![pantallazo_20180308_130115](https://user-images.githubusercontent.com/25255465/37150851-a8c79948-22d3-11e8-8269-f3a5c6908a63.png)

![pantallazo_20180308_004729](https://user-images.githubusercontent.com/25255465/37150860-ae6dfab8-22d3-11e8-98e7-8af3ac11d095.png)

**Comment by psifidotos** [comment] 2018-03-08 12:27
@michaldybczak the needed option is not enabled, you need to enable "Improve contents visiblity when the panel is transparent"

> There is a problem also with the global menu (Active Window Control). Backgrounds are showed ok in the activitie panel.

dont mess issues... just stick in the main issue and for any other issue open a new one

**Comment by psifidotos** [comment] 2018-03-08 12:29
and for the record....

> There is a problem also with the global menu (Active Window Control)

this was AWC responsibility and I am the one fixed it in its code... use the active window control master version from: https://phabricator.kde.org/source/plasma-active-window-control/

**Comment by psifidotos** [comment] 2018-03-08 12:32
@JuanManuelM show me in screenshot your Tweaks page

**Comment by psifidotos** [comment] 2018-03-08 12:45
@JuanManuelM @michaldybczak if you enable in Tweaks page "Improve contents visiblity when the panel is transparent" and the issue isnt fixed then the only way I can reproduce in my system is this:

_send me the layout file you are using and the wallpapers link in order to test out in my system to see if it is another setting that conflicts..._

**Comment by Magentium-Chris** [comment] 2018-03-08 12:48
I can confirm this issue. When running with "Improve contents visibility ... " with the Arc Dark theme, the icons are all greyed out, regardless of what is being attempted when a dark wallpaper is applied.

**Comment by psifidotos** [comment] 2018-03-08 12:50
@Magentium-Chris same thing applies to you...

_send me the layout file you are using and the wallpapers link in order to test out in my system to see if it is another setting that conflicts..._

**Comment by JuanManuelM** [comment] 2018-03-08 12:52
@psifidotos Here is my Tweaks page.

![pantallazo_20180308_004613](https://user-images.githubusercontent.com/25255465/37151937-d98b594e-22d7-11e8-8306-a7ef43655dde.png)

(Apologies for diverting the topic. I thought that problem with the global menu colour could be related to this. In any case, it also happens with the plasma global menu.)

**Comment by JuanManuelM** [comment] 2018-03-08 13:02
And here is a link to my layout file:

https://revistacuadernoatico.com/nextcloud/index.php/s/cu8KVhVjqbQimsy

I have tested with a lot of wallpapers, dark and clear...

**Comment by DoubleIntegral** [comment] 2018-03-08 14:13
@psifidotos 
Background: solid color -> black
Layout: Extended (it's one of default layouts) https://hastebin.com/ujihodisiy.md
Color scheme: Breeze Dark
Tweaks page screenshot: https://imgur.com/a/DBdFm

When choosing light themes (Breeze for example) feature works as expected.

**Comment by DoubleIntegral** [comment] 2018-03-08 14:17
I am so sorry for confusion, issue is still present on light themes. Screenshot with same configuration but Breeze color scheme and solid white background: https://imgur.com/a/VgcbC

**Comment by DoubleIntegral** [comment] 2018-03-08 14:44
Extra info:
KDE Plasma Version: 5.12.2
KDE Frameworks Version: 5.43.0
Qt Version: 5.10.1
OS: Manjaro x64, 4.14.23-1

**Comment by psifidotos** [comment] 2018-03-08 14:49
are you using single monitor or multi-monitor setup?

**Comment by DoubleIntegral** [comment] 2018-03-08 14:49
@psifidotos single monitor

**Closed** 2018-03-08 15:39 UTC
Labels: cantreproduce, needsinfo

**Comment by psifidotos** [comment] 2018-03-08 15:42
ok found it...

You are probably using SingleLayout mode for Latte. But single layout  had a bug and wasnt updating a very important variable for this feature `lastUsedActivity`. Based on that variable each layout remembers what is the current layout...

so probably this should be fixed for all of you... ;)

I hope you can enjoy now this fantastic feature...

**Comment by psifidotos** [comment] 2018-03-08 15:47
> In any case, it also happens with the plasma global menu.

@JuanManuelM  plasma menu had also some issues and I sent a patch that was accepted. But you should wait until plasma 5.13 for this...

**Comment by DoubleIntegral** [comment] 2018-03-08 15:47
Building it right now. Will come back with results soon

**Comment by DoubleIntegral** [comment] 2018-03-08 15:55
It works but color change is applied to everything, including icons: https://imgur.com/a/R1RzF
Should I open a new issue for this one?

**Comment by JuanManuelM** [comment] 2018-03-08 15:55
Testing the new commit and it works fine now. Thank you very much for your great work!

**Comment by psifidotos** [comment] 2018-03-08 16:02
> Should I open a new issue for this one?

this is something that cant be fixed... it's either for all or none...

**Comment by DoubleIntegral** [comment] 2018-03-08 16:05
I guess my one panel idea is not going to be a thing then. Oh well, if it can't be helped then it can't be helped.

**Comment by psifidotos** [comment] 2018-03-08 16:10
it is a plasma frameworks limitation... I only hope that the plasma mobile initiative will introduce changes in that area in order to support different color pallettes for different panels or applets....

**Comment by DoubleIntegral** [comment] 2018-03-08 16:14
I'm not too bummed out about it, I'll just use my dark background collection without adaptive coloring. It's not make or break for me

**Comment by michaldybczak** [comment] 2018-03-08 20:02
Wow, so much has happened in the time I was at work.
I updated latte and now it seems to work, although there are few wallpapers when this feature fails, but nonetheless in most of them it switches font colors which is super awesome. Now we can switch wallpapers without thinking that we need to switch desktop theme!

This is the wallpaper when it doesn't work correctly but it's nothing surprised, white background is only in the corner while the rest of the sky is intensely blue:

https://imgur.com/a/hITuR

Algorithms are not perfect and in most cases it works well so for me the feature works as intended now.

It's not only switching colors when wallpaper is changed. When I maximize windows and my panel becomes solid, it's original font is restores so it does adapt very well and works in various scenarios.
latte gives more and more freedom and becomes more and more flexible. Awesome! I will keep this feature on :+1: 

Thanks @psifidotos
