### ISSUE TITLE
Multi monitor "always visible" left and right justified panels result in wrong behaviour of windows when latte is started in multi screen

### ISSUE THREAD

**Issue by RomuloPBenedetti** [psifidotos/Latte-Dock#432] opened 2017-04-28 01:03 UTC
I will draw as I believe it will explain better. Just to summarize:
 
* **problem 1:** When maximized a window cover wrong space.
* **problem 2:** When moving a window, it suffer weird translation on the right monitor.

* **current solution:** Opening the right Pannel's settings and closing it.

I would like to add that when the system was installed monitors were shifted the left one was right and vice versa.

**system :** Fedora 25
**KDE Plasma:** 5.9.4
**KDE Framework:** 5.33.0
**QT::** 5.7.1

![explanation](https://cloud.githubusercontent.com/assets/12467382/25510033/9f0f3b3c-2b93-11e7-8b56-2505cee5f471.jpeg)

**Comment by psifidotos** [comment] 2017-04-28 04:23
Which latte version are you using?

**Comment by psifidotos** [comment] 2017-04-28 04:42
What do you mean shifted?

To confirm, you have a left dock in your left monitor and a right dock in the right monitor, both of them always visible?

**Comment by psifidotos** [comment] 2017-04-28 04:47
And one more thing, can you please make a screenshot of your multi screen setup from plasma systemsettings -> screens module?

**Comment by RomuloPBenedetti** [comment] 2017-04-28 07:54
0.6.0, I wanted to say that I changed the original position, the one that is right, originally was the left one for plasma, and the left one was the right one, I pointed this because some panel bugs with plasma I had in the past had to do with the monitor's position. I did this because the position did not map to the monitors physic place.

![screenshot_20170428_044952](https://cloud.githubusercontent.com/assets/12467382/25519497/6b67eec4-2bce-11e7-83c0-d8931cdb9b88.jpg)

**Comment by psifidotos** [comment] 2017-04-28 08:40
I will check it by i think we had made a commit before 0.6 version that was fixing almost an identical case for always visible panels...


Plasma system settings , monitors, what geometries shows? Can you make a screenshot?

**Comment by RomuloPBenedetti** [comment] 2017-04-28 08:57
Sure.

![image](https://cloud.githubusercontent.com/assets/12467382/25521611/b35f14fc-2bd6-11e7-9999-a9b5ccd0837c.png)

The right one is a 4k monitor, so I scale viewportin to overcome different PPIs, so it appears unusual, but I've noticed this when I was using Intel without viewportin scaling if I'm not wrong. I'm adding a video to better demonstrate the problem:

https://www.youtube.com/watch?v=QGKZogQG_ZY&feature=youtu.be

**Comment by psifidotos** [comment] 2017-04-28 09:32
based on the video the struts are not correct... i hope i can reproduce...

Could you try if by making the right monitor to not have a gap with the left monitor if it helps?

**Comment by psifidotos** [comment] 2017-04-28 15:42
well the news is that I tried v0.6 branch and this issue didnt appear in my system. I used the same screens positioning etc etc. but always visible was working without issues

you mentioned that in your system the physical screens positioning wasnt working correctly what did you mean ?

**Comment by RomuloPBenedetti** [comment] 2017-04-28 17:38
if I'm not wrong it is the package from fedora I'm using, Latte-Dock-0.6.0-1.fc25.x86_64. Will try to compile it. Are you using the fedora-install branch?

**Comment by psifidotos** [comment] 2017-04-28 17:59
my system is openSUSE... I just checked the fedora-install branch.... this is a lot outdated!!
it could be the reason of your bug if the package provided for fedora used this branch instead of the official v0.6 !!!

what latte version is the Latte settings window shows ?

**Comment by RomuloPBenedetti** [comment] 2017-04-28 18:10
It shows 0.6.0.
Well I tried the master as it is now working fine with fedora (running) as it did not work before, but the bug persists, now with the master version:

![spectacle m16118](https://cloud.githubusercontent.com/assets/12467382/25541284/7923ff0c-2c24-11e7-9ced-ff0b36f771a3.png)

Took from the terminal because now there is an advanced toggle on the place of the version number.

**Comment by RomuloPBenedetti** [comment] 2017-04-28 18:26
Have gone to native viewport size, still, the bug persists (the mismatched move pointer and window as an example):

![screenshot_20170428_151316](https://cloud.githubusercontent.com/assets/12467382/25541866/b478c748-2c26-11e7-9e52-aced3e70a678.jpeg)

Not exactly the same behavior, but still weird ones on original plasma arrangement of screens:

![screenshot_20170428_152126](https://cloud.githubusercontent.com/assets/12467382/25541895/cb51e800-2c26-11e7-85ff-cc28442dbc5d.jpeg)

**Comment by RomuloPBenedetti** [comment] 2017-04-28 18:34
same after the reboot. I would like to add that it did not appear to affect all windows in the same way. Windows not decorated by KDE as Vivaldi browser did not suffer from the moving displacement.

**Comment by psifidotos** [comment] 2017-04-28 18:49
1. if you replace the Latte docks with plasma panels what is happening? are they working correctly?

2. if you run `latte-dock -d --with-window` the debug windows for the latte docks will appear, the second record shows the screen geometry, are they shown correctly?

**Comment by RomuloPBenedetti** [comment] 2017-04-28 19:58
1 Plasma panels work correctly.

2 Geometry is correct:

![screenshot_20170428_164553](https://cloud.githubusercontent.com/assets/12467382/25544853/ca44f914-2c32-11e7-8978-bff2a597ad9a.png)

**Comment by RomuloPBenedetti** [comment] 2017-04-28 20:29
I looked it further and noticed those differences before and after opening options to force correction:

on the right monitor:

before:
**start layout size:** 1077 px.
**panel background thickness(automatic):** 6 
**panel background margin:** 0
**effect area:** 83, 0 6x2160
**content height:** 1200

after:
**start layout size:** 1157 px.
**panel background thickness(automatic):** 10
**panel background margin:** 2
**effect area:** 79, 0 10x2160
**content height:** 1280

on the left monitor:

before:
**start layout size:** 1077 px.
**panel background margin:** 0
**content height:** 1200

after:
**start layout size:** 1157 px.
**panel background margin:** 2
**content height:** 1280

**Comment by psifidotos** [comment] 2017-04-28 22:18
this is really strange... the plasma struts code and the latte one are identical...

@audoban do you have any ideas?

**Comment by psifidotos** [comment] 2017-04-28 22:47
If you try to play a bit with the zoom factor of the right dock... does it make any difference?

**Comment by psifidotos** [comment] 2017-04-28 22:59
Concerning the version number you can also find it by clicking the Latte icon in the Latte settings window

**Comment by RomuloPBenedetti** [comment] 2017-04-29 00:13
Ouch, I forgot to mention that It is only in **Justify** mode too...

**Comment by RomuloPBenedetti** [comment] 2017-04-29 00:32
Finally, I've found it, **show** in appearance is responsible for the problem when it is unchecked, And it was the only way to get transparency in 0.6.0. I don't see why to maintain this, you get the same effect with transparency now.

**Comment by psifidotos** [comment] 2017-04-29 06:39
1. Wait... you mean that the problem occurs only with a justify panel  in the right edge in the right screen and the zoom scale has no difference?

2. What do you mean about show in appearance was creating an issue?

**Comment by psifidotos** [comment] 2017-04-29 07:01
3. I also suspect that this issue is related to not using the correct screen when updating the compositor settings (struts). Try to set the right dock back to first screen and then again to the second... does it make any difference ?

**Comment by psifidotos** [comment] 2017-04-29 08:31
@RomuloPBenedetti we might have a fix for this... we will create a separate branch in order for you to test the fix first

**Comment by audoban** [comment] 2017-04-29 09:16
@RomuloPBenedetti hello, a possible fix is on the branch https://github.com/psifidotos/Latte-Dock/tree/fix432 4ef3107e21f3d6d538627b66f6f22b5006defcb8

**Comment by RomuloPBenedetti** [comment] 2017-04-29 10:44
I mean that selecting this checkbox on the screen solved everything:

![image](https://cloud.githubusercontent.com/assets/12467382/25554890/a35f4458-2caf-11e7-8b73-06df3c62ba87.png)

**Comment by psifidotos** [comment] 2017-04-29 11:23
Is it possible to check also the fix when show is not selected?

**Comment by RomuloPBenedetti** [comment] 2017-04-29 11:27
Sure, I will try the fix branch, and see if it turns possible to uncheck show without triggering the bug.

**Comment by psifidotos** [comment] 2017-04-29 12:32
It needs one more commit probably but we would like the feedback either way....

**Comment by psifidotos** [comment] 2017-04-29 16:44
@RomuloPBenedetti ok... the commit is in... please make a check.. is this fixed in all cases ?

**Comment by RomuloPBenedetti** [comment] 2017-05-01 06:01
Sorry for the delay, I've tested the fix branch now and it is working fine even with show marked, and, really thanks for the attention, I need to say (unfortunately... ) the kind of attention you guys gave is not the norm, It was really exceptional, thanks.

**Closed** 2017-05-01 06:20 UTC
Labels: needsinfo

**Comment by psifidotos** [comment] 2017-05-01 06:22
no worries... our pleasure...
