### ISSUE TITLE
New Layout - first impression

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#609] opened 2017-07-23 10:02 UTC
![spectacle ck7246](https://user-images.githubusercontent.com/24593950/28498308-8d858a06-6f9a-11e7-93b0-e9473a1321a8.png)

So if I well understand the functioning of the new Latte, I have to say that it goes far beyond my best expectations it is absolutely fantastic and totally centered on the activities and as you have said, it fully fulfills what I was suggesting with the issue #606 Pinable folderview 

I then proceeded as follows:....
- I've duplicated my global dock and each activity
- and for each one i've deleted the applets out of context

The only thing I could not do is:
- Does not allow me to use the same name for all my layouts (and this is normal) maybe you might think to associate automatically the layout name and the selected activity
- I can not sort the grid columns of the configuration form
- For the PowerSave activity I tried to drop my usual configuration for the one that replicates the default **plasma layout** ... I then copied and renamed the plasma layout but when I load the just mentioned layout  it back as my usual configuration

Congratulation guys

**Comment by psifidotos** [comment] 2017-07-23 10:58
Thanks!!!

> Does not allow me to use the same name for all my layouts (and this is normal) maybe you might think to associate automatically the layout name and the selected activity

By design the layout name is used as an id, so it isnt possible to have duplicates. Concerning the automatic naming for the activity, i wouldnt propose it because a layout can be assigned to more than one activities

> I can not sort the grid columns of the configuration form

I dont know if we can improve this in the layout manager but i dont know if it is that important. The default behavior is that layouts are ordered by their name always

> For the PowerSave activity I tried to drop my usual configuration for the one that replicates the default plasma layout ... I then copied and renamed the plasma layout but when I load the just mentioned layout it back as my usual configuration

That could be a bug that must be tracked. If i understood correctly a copied layout based on Plasma preset isnt show your favourite layout instead of the plasma one, right? The plasma one is shown correctly?

**Comment by JenaPlinsky** [comment] 2017-07-23 11:13
> I dont know if we can improve this in the layout manager but i dont know if it is that important. The default behavior is that layouts are ordered by their name always

It is true now I find everything ordered by name at first no ... so it's fine so

**Comment by JenaPlinsky** [comment] 2017-07-23 11:15
> That could be a bug that must be tracked. If i understood correctly a copied layout based on Plasma preset shows your favourite layout instead of the plasma one, right? 

Yep

> The plasma one is shown correctly?

Yep

**Comment by psifidotos** [comment] 2017-07-23 16:05
> Yep
> Yep

I cant reproduce this... You can try the following:

1. Remove the mentioned layout and the Plasma one
2. Press Defaults in order to readd properly the Plasma layout
3. Copy the Plasma layout
4. Press Apply button in order for 1-3 changes to be applied
5. check again what happens

**Comment by JenaPlinsky** [comment] 2017-07-23 17:50
I followed your directions to the letter and now works perfectly 
... I do not know what I'm doing wrong, maybe I did not give the Apply

**Closed** 2017-07-23 17:51 UTC
Labels: needsinfo

**Comment by psifidotos** [comment] 2017-07-23 18:15
@JenaPlinsky dynamic Layouts (automatic changing layouts for activities) is merged in newLayouts branch... ;) Finally!!! A dream came true... :)

**Comment by JenaPlinsky** [comment] 2017-07-25 00:44
Now, Plasma activities take on a deeper meaning and help us stay focused on our goals and projects, having everything we need at hand, that's exactly what I imagined was the initial plasma design
And with its malleability can satisfy even the most demanding user in full respect of the plasma philosophy

I really like a lot !!!!
@psifidotos  I propose you and @audoban as winner of the Akademy Awards 2017 in Almeira :)

**Comment by psifidotos** [comment] 2017-07-25 06:58
> Now, Plasma activities take on a deeper meaning and help us stay focused on our goals and projects, having everything we need at hand, that's exactly what I imagined was the initial plasma design

I think the same

> @psifidotos I propose you and @audoban as winner of the Akademy Awards 2017 in Almeira :)

hehe

**Comment by JenaPlinsky** [comment] 2017-07-25 21:17
![screenshot](https://user-images.githubusercontent.com/24593950/28594057-dd84d642-718e-11e7-9798-f198caa1403d.png)
@psifidotos  Sorry but I did not understand the difference between the three modes
Is not it enough to use the pin entry from the context menu?

**Comment by psifidotos** [comment] 2017-07-25 21:50
Now Latte supports shared launchers... 

Unique, the dock can have its own unique set of launchers infependent of other docks

Layout, different docks in the same layout can have the same set of launchers

Global, different docks can have to same set of launchers independent of layouts

**Comment by JenaPlinsky** [comment] 2017-07-26 22:53
I do not know what happened, but now I lost the launchers


--------------------------------------------------------------------------------
I want to have for the ...
- **primary monitor** a customized layout, starting from a basic template, for each activity, "PowerSave" excluded
- While in the **secondary monitor** I want to have an exact synchronized (if available) copy of the primary monitor
--------------------------------------------------------------------------------
For example, these are my activities:
- base model [defauilt milk panel with folderview as category launchers]
    - Office
         - What should I set here (unique.layout.global)?
    - Drawing
         - What should I set here (unique.layout.global)?
    - Cad
         - What should I set here (unique.layout.global)?
    - Developement
         - What should I set here (unique.layout.global)?
    - Cinema
         - What should I set here (unique.layout.global)?

- base model [panel as plasma default]
    - PowerSave
         - What should I set here (unique.layout.global)?


--------------------------------------------------------------------------------
Please tell me if I'm wrong,
In this example I'm using 6 activities and 2 layouts?
- my basic layout
       5 docks for monitor 1
       5 docks for monitor 2
- plasma panel layout
       1 docks for monitor 1
       1 docks for monitor 2

or...  6 activities and 7 layouts?

Sorry so much but until this feature has been introduced (unique.layout.global) it seemed to me all clear ...now seeing that I lost the launchers, I'm doing a lot of confusion

**Comment by JenaPlinsky** [comment] 2017-07-26 23:09
Pin from the contextual menu is always the correct way to associate pitchers with activities (or layouts)?
Is the item "all activities" still valid?

**Comment by psifidotos** [comment] 2017-07-27 08:41
> I do not know what happened, but now I lost the launchers

probably they are inside a layout file.
- Universal launchers are found at .config/lattedockrc under UniversalSettings, launchers
- Layout launchers are found at .config/latte/*layout.latte under LayoutSettings, launchers

you can check if you can find them in there first to be sure that you didnt lose them.

> " primary monitor a customized layout, starting from a basic template, for each activity, "PowerSave" excluded. "While in the secondary monitor I want to have an exact synchronized (if available) copy of the primary monitor "

ok... Some info, concerning Activities, You cant have based on Activities design diffent Activities in different monitors. An Activitiy when is activated all the monitors change to that Activity by design. Activities was a concept in order to get focused in a specific task.

"I want to have an exact synchronized (if available) copy of the primary monitor", no this is no possible. There is no synchronization possible between docks/layouts etc. except the launchers case.

> Pin from the contextual menu is always the correct way to associate pitchers with activities (or layouts)?

you can choose what is best for you

> Is the item "all activities" still valid?

yes of course

-------------------

What should I do in your case. You have get familiar with the pin option so the Univesal option is the best for you. You can:

1. Create a layout for one of the 5 common Activities that is going to have everything in common, such as docks, applets etc... set the launchers for every dock in it in Universal
2. Create the other 4 layouts based one the first one and add only the applets that are different.

Now the launchers for these 5 layouts are automatically synced and it is the same group. You can use the pin feature in order to separate them without noticing that it is the same group.

In case that in one of these 5 layout you want a new dock that is going to have its own specific launchers you will set it at: Unique

3. Create the 6th layout based on the Plasma and set its launchers to be Universal. Now the launchers are automatically synced also, use the Pin feature to show launchers only for that activity
