### ISSUE TITLE
[multi-screen], Latte plasmoid freezes when game disables compositor

### ISSUE THREAD

**Issue by eversins** [psifidotos/Latte-Dock#753] opened 2017-11-02 16:49 UTC
The latte dock plasmoid (applications in the dock) freeze if you launch a game which disables the desktop compositor.

You can still click on the icons if you can guess where they are located, here is a example video:
https://gfycat.com/gifs/detail/DefensiveFrankKingsnake

There are 3 ways the dock is displayed if you launch a game:
1. Everything freezes, icons and time is not updated
2. You see a yellow bar behind the icons, as seen here: https://i.imgur.com/UX83wrs.png
3. Black bar, nothing is show but a black bar, you can still use the dock if you can guess where icons are located

I am not sure if I am describing two separate problems here.

**Comment by psifidotos** [comment] 2017-11-02 17:02
can you replicate this with game 0ad ?

**Comment by psifidotos** [comment] 2017-11-02 17:03
do you know any free small size game in order to test in my system?

**Comment by eversins** [comment] 2017-11-02 17:18
Do you like old adventures? I could gift you "Day of the tentacle Remastered" or "Grim Fandango Remasterd"
Or something else you like? I have a lot of spare keys for games. Just tell me what you like. Another option would be to check steam for free to play games. Something like Dota maybe, I have no experience with that though, but it seems to happen with every game that disables the compositor.

**Comment by psifidotos** [comment] 2017-11-02 17:37
I am downloading RoboCraft ... I hope it is doing the job... it is **_Free To Play_**

**Comment by psifidotos** [comment] 2017-11-02 17:52
do I miss something? the game disabled compositing... from inside the game I used Alt+F2 and run kwrite... the kwrite window is shown ok in the Latte taskmanager...

Are you using a multi-screen environment?


![image](https://user-images.githubusercontent.com/2216474/32341829-45533eb4-c007-11e7-84ee-1e215839cbd0.png)

**Comment by eversins** [comment] 2017-11-02 20:05
Yes I am using multi-monitor with an NVIDIA GPU.
I have done some testing.

Switched to single-screen and start game -> black bar.
Restarted latte on single screen and start game -> Working like you describe but with the strange Yellow background as posted above.

So it looks like the core of the problem is with Multiple screens and the yellow background is a different problem?
Just tell me if you wan't me to test something else.

**Comment by psifidotos** [comment] 2017-11-02 20:57
> So it looks like the core of the problem is with Multiple screens and the yellow background is a different problem?

unfortunately I cant yet replicate it in my system... I used multi-screen case and I use the proprietary NVidia driver...

what Latte version are you running?

**Comment by eversins** [comment] 2017-11-02 22:04
Before I was using the git from AUR, now the package from repos. Version 0.7.1. I have always had this problem.

OS: Manjaro 17.0.6 Gellivara
Kernel: x86_64 Linux 4.13.10-1-MANJARO
Resolution: 3840x1200
DE: KDE 5.39.0 / Plasma 5.11.2
WM: KWin
CPU: Intel Core i7-4770K @ 8x 3.9GHz [27.8°C]
GPU: GeForce GTX 970
RAM: 4958MiB / 15988MiB

**Comment by psifidotos** [comment] 2017-11-03 05:34
For the orange issue what plasma theme are you using?

Have you tried any of the default plasma themes?

**Comment by eversins** [comment] 2017-11-03 14:57
I use official Breeze Dark. I still tested it with Breeze but got the same results.

The yellow background is the smallest problem here, dock actually works and updates even though it looks ugly.

It looks like to freeze the dock I don't even need to launch a game, disabling compositor with Shift+alt+F12 shows the same result.
I recorded it here: https://gfycat.com/gifs/detail/PresentGraciousAfricanharrierhawk

**Comment by psifidotos** [comment] 2017-11-03 16:51
> The yellow background is the smallest problem here, dock actually works and updates even though it looks ugly.

everything is important because that way we can find details about what produces the issue in order to be able to reproduce later... The orange behavior is very suspicious also...

**Comment by psifidotos** [comment] 2017-11-03 17:05
orange issues fixed with: https://commits.kde.org/latte-dock/0835fd7b4d1825f3d8731fd8705891f9819eb6ac

the orange issues was an easy bug, the fix will land in 0.7.2 until then you can fix in your system with following: Go to Appearance -> enable to show the panel background and adjust its size to 0% in order to show only a small line in the bottom for dots and lines. With this settings enabled in !compositing you should get the panel background drawn correctly for all the bar.

**Comment by psifidotos** [comment] 2017-11-03 17:07
@eversins in more thing please, can you export your layout and upload it here in order to test it in my system? there is a chance that some minor setting produces also the issue with the tasks...

**Comment by psifidotos** [comment] 2017-11-03 18:27
@eversins there is a chance that commit: https://commits.kde.org/latte-dock/c6cd7d975a3400e2798c572921cd2c17e51a3a11

fixes this... I dont know if you can build and test from kde repo, otherwise you will have to wait for 0.7.2 version to check this out...

**Comment by eversins** [comment] 2017-11-03 19:14
So a good reason to push 0.7.2 soon. :)

Here is my uploaded layout: https://pastebin.com/gt1R7kXg

I can install latte over AUR, which displays version: 0.7.1.r60.g9932ae8-1, are those commits already in this version? I don't really get the versioning numbers..

**Comment by psifidotos** [comment] 2017-11-03 19:54
The AUR version is updaed in few hours usually... switch to AUR version, if orange issue is fixed report back what happens with the tasks issue

**Comment by omni6** [comment] 2017-11-03 22:50
@eversins 
do not flag out of date unless the package doesn't build. An AUR git version **always** compile from **latest master**, the displayed version has nothing to do with the version you will have installed. 
as arch user you should know!

**Comment by eversins** [comment] 2017-11-04 01:32
@omni6 
Sorry I did not know that, its not exactly self explanatory with that name, I was not trying to abuse it.

@psifidotos 
I have installed the latest build (0.7.1.r71.gc6cd7d9-1).
The yellow background seems to be fixed, so for single monitor it works as expected, there is only shor flash with yellow background: https://gfycat.com/gifs/detail/LiquidValidArgentineruddyduck

Multi-monitor is unfortunately still broken, with a black or frozen dock. Maybe you could try to put you second Monitor to the left position? KDE has/had some other issues with that.

**Comment by psifidotos** [comment] 2017-11-04 07:21
the only thing that would make sense for tasks issue is the qt behavior that for windows out-of-screen the drawing is disabled, I cant think anything else...

You must play with your system in order to find out what is broken and see if the behavior is different:
1. change the dock's edge
2. change the dock's screen put it in the same screen that the game is playing
3. upload a screenshot from plasma systemsettings about how you have set your monitors, for screens resolutions, placement etc...
4. run `latte-dock -d --with-window` and send a screenshot of this values here, especially the top values that say the screen and window geometry

**Comment by psifidotos** [comment] 2017-11-04 07:22
5. reduce the maximum length of the dock to 95%

**Comment by eversins** [comment] 2017-11-05 15:45
1. Did not change anything
2. It is unrelated to games, I do the test now with just disabling compositor with SHIFT+ALT+F12.
3. https://i.imgur.com/OCd1o0M.png
4. https://i.imgur.com/tqZgK3O.png
5. Is the same as Nr. 1.?

I have noticed that if I close latte after initial boot and open it again, it works as expected, here is a video showing this: https://gfycat.com/gifs/detail/FlashySlipperyBarnswallow

**Comment by psifidotos** [comment] 2017-11-05 16:06
I definitely cant replicate in my system...

5. enable advance settings, tab Appearance -> Max Length -> set the slider to 95%

**Comment by psifidotos** [comment] 2017-11-05 16:09
ok...
important questions...

1. screenshot from (4) is when the problem occurs?

**Comment by eversins** [comment] 2017-11-05 17:21
> screenshot from (4) is when the problem occurs?
No this one is while it is happening/black: https://i.imgur.com/hcBXGyR.png

**Comment by psifidotos** [comment] 2017-11-06 18:34
The important is the isHidden that is set to true... if you go the mouse at the screen edge center arent the tasks shown again?

**Comment by eversins** [comment] 2017-11-06 19:06
Its hidden because I focus on the window to make the screenshot. 
You only see the black bar when the dock is shown..
https://gfycat.com/gifs/detail/ImmaculateChillyAmericancreamdraft

**Comment by psifidotos** [comment] 2017-11-06 20:09
make the same video but showing also the debug window in it... while the black bar occurs, hover with mouse over it... i wanna see the values in the debug window while you are hovering

**Comment by eversins** [comment] 2017-11-06 21:53
I got a good capture for you, it show the frozen dock first, then normal, then frozen again. You can see that the second time I disable compositor the same old frozen display is show as when enabling it the first time.

https://gfycat.com/gifs/detail/ClearFoolhardyAfricangoldencat

**Comment by psifidotos** [comment] 2017-11-06 22:11
When task icons are not updated if you increase the applets size from settings do they appear afterwards?

**Comment by eversins** [comment] 2017-11-06 22:56
Yes the dock updates as soon as I change size for 1px. It even works if I enable compositor and disable it again.

**Comment by psifidotos** [comment] 2017-11-07 07:56
Can you show me a video please? We might be able to force a redrawing with delay to see if it works

**Comment by eversins** [comment] 2017-11-07 15:12
Done: https://gfycat.com/gifs/detail/FirmGrimyIchthyostega

**Comment by psifidotos** [comment] 2017-11-07 20:29
this is probably an nvidia proprietary issue.. I am hoping of course that they will fix it so I could add a mechanism to force a redraw when going to !compositing mode...

but the thing is that I would like @eversins to test it first before merge it in... is that possible?

**Comment by eversins** [comment] 2017-11-07 20:31
Just tell me what to do, I'll gladly help.

**Comment by psifidotos** [comment] 2017-11-07 20:48
You must substitute two files in your system:

1. go to directory `/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui`
2. substitute `main.qml` file with the one I send
3. go to directory `/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/applet`
4. substitute `AppletItem.qml` file with the one I send
5. close Latte
6. start Latte

that is all... is the issue fixed?

**IMPORTANT:** to restore the old versions for your files either you will re-install latte-dock or you must have take them backup and restore them afterwards... I am referring to files, `main.qml` and `AppletItem.qml`

[AppletItem.qml.txt](https://github.com/psifidotos/Latte-Dock/files/1451573/AppletItem.qml.txt)
[main.qml.txt](https://github.com/psifidotos/Latte-Dock/files/1451574/main.qml.txt)

**Comment by eversins** [comment] 2017-11-07 21:13
I have repeated the steps I did before where I got the error 100% of the time.
The "fix" seems to have worked! I have not seen the bug once.

If you want me to test longer I can report back in 2-3 days?

Thanks for the great support for now, you have repeatedly shown to be the greatest dev I have seen on any project! Thank you so much for everything.

**Comment by psifidotos** [comment] 2017-11-07 21:16
thank you...

please test it for a day... :)

and send me that everything is ok in order to merge it for the upcoming 0.7.2 version

**Comment by eversins** [comment] 2017-11-07 23:18
Just happened again. I have to say that I had a kwin_x11 crash some time before (sadly something that happens since plasma 5.11), but this was long before launching the game and compositor being disabled, in case that has any relevance which would void this test.

https://gfycat.com/gifs/detail/ConventionalCarelessCoypu

**Comment by psifidotos** [comment] 2017-11-08 13:31
1. the issue returned once or happens all the time?
2. what I see from the video is that the task that is not shown in !compositing is a game. does the issue occurs for all new created windows or for specific ones?

**Comment by eversins** [comment] 2017-11-08 14:50
Okay I just got a clean test, soon after rebooting the problem occurred once disabling compositor, so the problem is still present.
https://gfycat.com/gifs/detail/SkeletalSoggyHoki


2. Do you mean if only one icon is not shown? Then the answer is no, every time the whole dock is frozen, even the system tray and Clock is frozen.

**Comment by eversins** [comment] 2017-11-08 14:58
The dock you see is always frozen like a screenshot from the time compositor gets disabled (or black), even when you enable and disable compositor again, it will show the same frozen "image" like the _first_ time you disabled compositor.

**Comment by psifidotos** [comment] 2017-11-08 16:23
ok... check please if this occurs also with Center alignment(from Justify) and if it freezes try to open a new window to see what happens

**Comment by psifidotos** [comment] 2017-11-08 17:20
@eversins I managed to reproduce in my system but it is so rare in my system that it is hard to play with it...

to reproduce it I had to do the following:

1. setup a multi-screen environment
2. change the screen geometry of the screen that the dock belongs to by moving it around
3. after that there are some rare cases that dock freezes in !compositing and it isnt come back

this is either qt or nvidia driver issue...
what is happening is that windows that are out of screen stop their painting and in that case they dont reenable it... this is why when we change the icon size or the screen edge that the dock belongs to the issue is fixed. Because that way the underlying libraries they update the window geometry and they reenable the painting...

problem is that I cant know when they issue occurs yet in order to force a fast repainting...

**Comment by eversins** [comment] 2017-11-08 22:41
Could it be a xorg problem as the main monitor is not at 0,0 but 1920,0? At least that caused problems with Plasma in the past, for examples it caused i.e minimize animation to move off screen to name one example. What multi monitor setup do you use? Just to be clear this is mine:
| Secondary |    Primary    |
|                   |      Dock      |

Any way I can help out? I know it is hard to reproduce and might seem a bit random. At least without the updates files you sent me I could reproduce it consistently I think. Do you want me to revert the changes and do more testing, I could also try to setup a test environment and give you remote access?

**Comment by psifidotos** [comment] 2017-11-08 22:44
unfortunately this can be solved only either by a very big timer...
e.g. a timer that waits for 10secs in order to force a full window redraw or through finding a way for Latte to always draw its contents regardless of the out-of-screen state... I would prefer the second so this case must be investigated first...

**Comment by psifidotos** [comment] 2017-11-08 22:52
@eversins @davidedmudson reported that for plasma:

> We have the exact same bug with our panel freezing after a full screen game is run. We haven't fixed it.

so this happens also with plasma panels in some cases. any fix for this will be coordinated with plasma devs... ;)

**Comment by eversins** [comment] 2017-11-08 23:57
Good to hear that you could pin point it. Would you please link to the bug report as I could not find it, even if it just to follow progress. Thank you!

**Comment by psifidotos** [comment] 2017-11-11 08:11
kde report: https://bugs.kde.org/show_bug.cgi?id=353983

**Closed by psifidotos** 2017-11-11 08:11 UTC
Labels: needsinfo, upstream

**Comment by eversins** [comment] 2017-12-14 15:04
Is there anything I/we can do to temporarily dirty fix this issue? It is a huge annoyance which many are confronted with daily. Since it is a KDE/Plasma bug I don't have high hopes for it being fixed anytime soon. Thank you.

**Comment by psifidotos** [comment] 2017-12-14 17:14
unfortunately I dont have any idea... this is going down to qt and there is no way for upstream projects to know when this occurs... at the same time this is x11 specific and not wayland... so this is leading to : "wayland will fix this far in the future..."

**Comment by eversins** [comment] 2017-12-14 19:44
Thanks for the reply, that was my fear "wayland will fix this far in the future..." seem to be a common response when it comes to KDE. Unfortunately that means it will probably never be fixed if using a nvidia card.

This problem, is so big I have actually looked at moving to another DE all together, just thought you might have an idea for a dirty fix to force the redraws, since you mentioned something like that in a previous post.

**Comment by psifidotos** [comment] 2017-12-14 19:46
I am sorry mate...
