### ISSUE TITLE
Latte-Dock doesn't work

### ISSUE THREAD

**Issue by HorusBlack** [psifidotos/Latte-Dock#580] opened 2017-07-02 18:40 UTC
I just installed it in Debian inside KDE plasma 5, but after configuring lattle, putting the cursor on the dock this closes automatically and does not show any error messages.
When trying to reopen the latte, the dock loads but restarts when the cursor is hovered over it.
Uninstall the dock and purge it and reinstall it but the problem is still there. I hope they can give me a solution

**Comment by psifidotos** [comment] 2017-07-02 18:46
what latte version?
what plasma version?
run latte from command line with: latte-dock -d

what it the output in such case?

**Comment by HorusBlack** [comment] 2017-07-02 18:54
> latte-dock_0.6.0-1_all.deb
>KDE plasma: 5.8.6
>KDE frameworks: 5.28.0
>Kernel: 4.9.0-3-amd64
>Os: 64 bits

Ok I'll try

**Comment by HorusBlack** [comment] 2017-07-02 18:57
When use the command, Show me this:

horusblack@LenovoY480:~/Descargas$ latte-dock -d
[debug 13:55:49.600600] - package is valid true
[debug 13:55:49.600600] - connector : "LVDS-1"  -  "10"
[debug 13:55:49.600600] - Known Screen -  "LVDS-1"  -  10
[debug 13:55:49.600600] - Latte::DockCorona the package QJsonObject({"KPlugin":{"Authors":[{"Email":"mvourlakos@gmail.com, audoban@openmailbox.org","Name":"Michail Vourlakos, Smith Ar"}],"Description":"Shell provided for the Latte Dock","Description[zh_TW]":"由 Latte Dock 提供的 Shell","Id":"org.kde.latte.shell","License":"GPLv3+","Name":"Latte Shell","Name[zh_TW]":"Latte Shell","ServiceTypes":["Plasma/Shell"],"Version":"0.6.0","Website":"https://github.com/psifidotos/Latte-Dock"},"Keywords":"shell","X-KDE-ParentApp":"latte-dock"}) is valid!
[debug 13:55:49.604604] - containment values:  true  -  -1
[debug 13:55:49.604604] - TASKS WILL BE PRESENT AFTER LOADING :::  true
[debug 13:55:49.685685] - add dock - containment id :  -1
[debug 13:55:49.685685] - Adding dock for container...
[debug 13:55:49.685685] - onPrimary:  true screen!!! : -1
[debug 13:55:49.730730] - adapting to screen...
[debug 13:55:49.748748] - SOURCE: QUrl("/usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml")
[debug 13:55:49.748748] -   Delayer  
[debug 13:55:49.748748] -       D, found screen:  "LVDS-1"
[debug 13:55:49.748748] - dock screen exists  :::  true
[warning 13:55:50.3030] - Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
[debug 13:55:50.147147] - ----------- Latte Plasmoid Signal: Activities number was changed ---------
[debug 13:55:50.147147] - 14f2eaf4-ae8e-497b-8f7f-bf0262971c9b
[debug 13:55:50.147147] - ----------- Latte Plasmoid Signal End ---------
[warning 13:55:50.163163] - file:///usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/main.qml:151:42: Unable to assign int to QObject*
[warning 13:55:50.503503] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:170:41: Unable to assign int to QObject*
[warning 13:55:50.503503] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1311: TypeError: Cannot read property 'visibility' of null
[warning 13:55:50.503503] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1286: TypeError: Cannot read property 'visibility' of null
[warning 13:55:51.7575] - file:///usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml:1302:12: Unable to assign [undefined] to double
Violación de segmento

**Comment by audoban** [comment] 2017-07-02 19:21
@HorusBlack do you can update to version 0.6.2 of latte?

**Comment by HorusBlack** [comment] 2017-07-02 20:24
It is the version I am given for debian, and I think it is the most updated. 0.6.0-1. but, Ok I'll try

**Comment by HorusBlack** [comment] 2017-07-03 01:20
I've updated, but the problem is still there. I guess I'll wait for the next version. Thanks for your help :)

**Comment by HorusBlack** [comment] 2017-07-03 01:41
I do not know what happened, change latte-dock to appear on top of the monitor and the problem disappeared. But if I put it on the bottom, it closes. I do not know if it works at all

**Comment by psifidotos** [comment] 2017-07-03 05:06
Close latte and try to remove all *latte" files in your .config folder in case your settings are broken

How did you set it to be in top as long as when you start Latte it crashes?

**Comment by HorusBlack** [comment] 2017-07-03 06:38
I already uninstall it with:
  apt-get remove latte-dock
  apt-get remove --auto-remove latte-dock
  apt-get purge --auto-remove wallch
 
Also upgrade to version 0.6.2
But the problem was solved for a moment, but it repeated itself again. To put it on top of the monitor, use the settings provided by the latte. I have to restart the computer to run latte but after 30 minutes the problem is repeated.

**Comment by psifidotos** [comment] 2017-07-03 11:35
I saw the video... so strange... can you please follow #147 to provide us with a backtrace?

**Comment by HorusBlack** [comment] 2017-07-03 16:04
It show me this. 
https://ibb.co/gQ21Xv
https://ibb.co/ko8fQF

**Comment by audoban** [comment] 2017-07-03 17:40
Hi @ HorusBlack can you install the debuginfo latte package, to get a useful backtrace?

**Comment by HorusBlack** [comment] 2017-07-03 17:47
How do I install it?

**Comment by psifidotos** [comment] 2017-07-03 17:51
it is debian I dont think it is needed...

@HorusBlack in your second screenshot when you get your Segmentation fault message, go afterwards at Status->Backtrace inside ddd. We want to see what are the messages inside that window

**Comment by HorusBlack** [comment] 2017-07-03 18:55
It show me this.
https://ibb.co/kuWyxv

**Comment by audoban** [comment] 2017-07-03 19:10
@psifidotos The backtrace still useless because it doesn't have _debuginfo_, but it is possible that the problem is in libtaskmager, I don't know, i cant see anything line related with our dock.

**Comment by psifidotos** [comment] 2017-07-03 19:12
Have you enabled window previews or highlight windows from the Tasks page?

**Comment by psifidotos** [comment] 2017-07-03 19:31
@audoban there is a chance that something changed in taskmanager's plugin in plasma 5.8.6 and now Latte is crashing... Problem is I dont have a plasma 5.8 available...

**Comment by HorusBlack** [comment] 2017-07-03 19:35
I did another test and give me this
https://ibb.co/fY7oxv

**Comment by psifidotos** [comment] 2017-07-03 19:53
this is different than the previous

**Comment by HorusBlack** [comment] 2017-07-03 20:04
What I did first was to run the ddd with execution. Then I opened the blacktrack and, at the end, I placed the cursor on the base. That is why the result is different.
https://ibb.co/kEbTVF

**Comment by audoban** [comment] 2017-07-03 23:58
@psifidotos is necessary have the debuginfo for get a backtrace useful.
I do not know how to install debuginfo packages in debian, for at least on opensuse each package have your package debuginfo corresponding.

@HorusBlack Sorry the backtrace can not tell us anything because The only thing I see are the chars __??__ You need the debuginfo package of plasma-workspace or libtaskmanager

**Comment by HorusBlack** [comment] 2017-07-04 02:31
Plasma-workspace is already in its most recent version (4: 5.8.6-2.1). How do I install libtaskmanager?.

**Comment by audoban** [comment] 2017-07-04 04:05
dont worry, libtaskmanager is a library, and you have already installed this library.

You can can use now ddd for get a backtrace useful.

**Comment by HorusBlack** [comment] 2017-07-04 06:04
I record the backtrace, in case I'm doing something wrong
https://youtu.be/o63swUmTJY4
https://ibb.co/n37iEa

**Comment by psifidotos** [comment] 2017-07-04 06:17
@HorusBlack the debug package is separate than the original package. A debug package is used only to help the developers understand why an app is crashing. You need the debug packages for latte-dock, plasma-workspace and plasma-desktop.

For debian I found this in order to install these packages
https://wiki.debian.org/DebugPackage

**Comment by psifidotos** [comment] 2017-07-04 11:53
@HorusBlack one more thing, I found a laptop with plasma 5.8.6... Latte didnt crash... the first crash you uploaded was definitely fixed in Latte version 0.6.2 .

Are you sure you installed v0.6.2 correctly? you can see the Latte version at its configuration window at its top right corner

**Comment by psifidotos** [comment] 2017-07-04 11:54
you can find v0.6.2 at RimMills packages, https://launchpad.net/~rikmills/+archive/ubuntu/latte-dock

**Comment by HorusBlack** [comment] 2017-07-04 15:58
You're right, it was not well updated. With version 0.6.2 the dock is no longer dropped. Thanks for your help.

**Comment by psifidotos** [comment] 2017-07-04 15:58
;-)

**Closed by psifidotos** 2017-07-04 15:58 UTC
Labels: needsinfo
