### ISSUE TITLE
[Multi - Screen] : Latte-dock starts in wrong position after restart

### ISSUE THREAD

**Issue by barbub** [psifidotos/Latte-Dock#503] opened 2017-05-28 18:13 UTC
I use an external display on my laptop, and the latte-dock I have set up is on the external display, with no latte-dock on the primary (laptop) display. Its position is set to be at the bottom. However, on each restart, it appears in the middle (center) of the primary display, not on the external display and not at the bottom. I can make it move to its proper position by deselecting and re-selecting the external display in the latte-dock setting, but this has to be done each time I restart the laptop. (My KDE panels keep their position, however, after restarting.)

**Comment by psifidotos** [comment] 2017-05-28 18:17
upload screenshots,
what latte version are you using?
export also your configuration and send it to take a look

**Comment by psifidotos** [comment] 2017-05-28 18:19
Try also the following, when you restart your laptop and your dock is not positioned correctly, close Latte and start it again, is it positioned correctly then?

**Comment by psifidotos** [comment] 2017-05-29 19:57
sorry wrong reference in the commit

**Comment by psifidotos** [comment] 2017-06-01 22:21
@barbub I need you to follow some steps and provide me feedback otherwise a regression cant be fixed.

1. The issue you describe appears only on aystem startup? If you start Latte after everything has been loaded does it position correctly the dock ?

2. If you run Latte from command line, latte-dock -d    what is the output?

**Comment by psifidotos** [comment] 2017-06-08 19:27
tested this configuration in a multi-screen environment... the issue is not confirmed... the user should had followed guidelines to track this down...

**Comment by gzmorell** [comment] 2018-03-20 10:07
Hi, I have the same issue.
I use latte-dock 0.7.4.1 on ArchLinux. Everything updated.
The issue:
Booting with 2 screens: there are issues with latte-dock position or size.
After Booting: Closing Latte-dock after complete boot and opening again and everything works as expected.
After Booting: Opening Latte settings and selecting the secondary screen and then the primary and everything works as normal.
Issues after booting:
1. If primary screen is configured as the right screen (in system settings Display and Monitor), then latte starts at the wrong screen (secondary) but with a wrong position (as if the screen size where the size of the primary). Trying to select primary screen in latte settings do not work. You have to apply "secondary screen" and then "primary screen" to go to normal. Closing Latte and opening again also works.
2. If primary screen is configured as the left screen (in system settings Display and Monitor), then latte starts at primary screen in the rigth position, but the icons size is wrong as it if where from secondary screen. Setting secondary screen and then back to primary and everything is normal again. Closing latte and opening again also works.
3. Attaching the secondary screen after complete boot has no issues.

I would be glad to help to solve this issue if possible.

**Comment by psifidotos** [comment] 2018-03-20 12:29
Can you please provide screenshots for 1 and 2. ?

These issues appear also if you log out and log in afterwards?

**Comment by gzmorell** [comment] 2018-03-20 13:44
This is normal screens(case 3):
https://ptpb.pw/J1iW.png
This is case 1:
https://ptpb.pw/xOYx.png
This is case 2:
https://ptpb.pw/9Wik.png

Logging out and logging in do not avoid problem. Same images are valid.
The screens are:
Primary (laptop screen) LVDS1: 1366x768
Secondary (external monitor) VGA1: 1920x1080

As you can see there is also an error with files located on desktop folder. They are shown in secondary screen when booting with both monitors connected. They are shown in primary when booting with only one monitor and attaching the monitor after kde plasma has started.

**Comment by psifidotos** [comment] 2018-03-20 20:24
1. why the top bar isnt shown at all at some screenshots?

2. for case 2 unfortunately I cant reproduce in my system neither with v0.7.x nor with master one.

3. for case 3 you should try the master version to check if this is still valid or if it has been fixed.

>  As you can see there is also an error with files located on desktop folder. They are shown in secondary screen when boo....

something can be weird in your system concerning the primary screen case... if you set your dock at specific screen is it always correct?

**Comment by gzmorell** [comment] 2018-03-20 23:14
1. It is just because is set auto-hide (i supose it was the cursor position white taking the snapshot).
3. I will try and send back info.

**Comment by psifidotos** [comment] 2018-03-27 20:56
@gzmorell I think we can find for info for this...
run in your system: `latte-dock -d --with-window` it shows a debug window for each dock... some of the info are relevant to screen identified for that dock, screen geometry, etc. etc...

please report again the issues but containing also that window in the screenshot

**Closed** 2018-04-08 16:07 UTC
Labels: cantreproduce, needsinfo
