### ISSUE TITLE
[Crash] - with VLC

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#234] opened 2017-03-06 03:52 UTC
Crash on closing event of VLC
![screenshot_20170306_044640](https://cloud.githubusercontent.com/assets/24593950/23596151/25512358-0228-11e7-8be5-aad7b74cac41.png)

here again
![spectacle fo1023](https://cloud.githubusercontent.com/assets/24593950/23596201/802deb8a-0228-11e7-960e-cd48336b039c.png)

**Comment by psifidotos** [comment] 2017-03-06 09:58
1. Can you reproduce this or is a rare case?
2. Do you use window previews?
3. Was something played at vlc when it was closing?

I am starting to believe that this is from the cache optimizations that were introduced

**Comment by JenaPlinsky** [comment] 2017-03-06 17:29
> Can you reproduce this or is a rare case?

Yes, it can be replicated 


> Do you use window previews?

What do you mean ?


> Was something played at vlc when it was closing?

No ...here is a [video](https://youtu.be/gy9DUoToydM)

do you think it has anything to do with kwin? we could ask for opinion to Martin

**Comment by psifidotos** [comment] 2017-03-06 17:39
try to disable window previews and see what happens...

I suppose this is not happening with plasma panels right?

I can not reproduce,

what vlc version are you using?
in vlc shown in the systray?

**Comment by psifidotos** [comment] 2017-03-06 17:40
this was always happening are some commits from the master branch activated it?

**Comment by JenaPlinsky** [comment] 2017-03-06 18:09
> try to disable window previews and see what happens...

but I do not know what and where 

> I suppose this is not happening with plasma panels right?

...the same thing happens also with the default panel 👍 
> I can not reproduce, 
> what vlc version are you using?

![spectacle uz8429](https://cloud.githubusercontent.com/assets/24593950/23622195/fc927568-029d-11e7-952b-615346c34997.png)

> in vlc shown in the systray?

[video](https://youtu.be/axhXwdRAMa0)
> 
> this was always happening are some commits from the master branch activated it?

sorry I did not understand

**Comment by psifidotos** [comment] 2017-03-06 18:29
> ...the same thing happens also with the default panel 

ok.... then this upstream definitely! It is probably inside the plasma-framework... I cant know why... but it might be because of the vlc version also (beta vlc 3.0)...

will you open a bug report at bugs.kde.org and attach also this thread and and the backtraces?

**Comment by psifidotos** [comment] 2017-03-06 18:35
strange this also!!! why appletDeleted is called even though vlc is just used by libtaskmanager!!!

**Comment by psifidotos** [comment] 2017-03-06 18:36
all crashes in plasmashell get high priority @JenaPlinsky they will respond quickly I think...

**Comment by JenaPlinsky** [comment] 2017-03-06 18:40
as mentioned in the issue #150 and as shown in the [video](https://www.youtube.com/watch?v=axhXwdRAMa0) 
plasmashell has a recovery function in case of a crash and therefore, also the default panel always comes back to life
for Latte, this could become a problem, ... In order to rescue the plasma funtionality we could think to different approaches

> Maybe when Latte will be robust and stable, you could think to implement some sort of "emergency mode" mechanism such as occurs, for Kwin and plasma-shell, I think

>     try to re-open a new latte-dock instance

>     if it is still unresponsive than try to restore a saved backup configuration file

>     if the last attempt did not work, then as an alternative, try to open the default Plasma panel

right now it could be enough to put a Latte's launcher on the desktop to help the less experienced users

**Comment by psifidotos** [comment] 2017-03-06 18:43
> plasmashell has a recovery function in case of a crash and therefore, also the default panel always comes back to life

plasma does not accept crashes!!! :)  they just dont know it....

**Comment by psifidotos** [comment] 2017-03-06 18:45
and I believe that vlc 3 has introduced something that confuses plasma... have you touched the vlc metadata desktop file in any way?

**Comment by JenaPlinsky** [comment] 2017-03-06 18:52
No @psifidotos ...never touched

**Comment by psifidotos** [comment] 2017-03-06 19:03
there is a discussion for this with all the big names in it: https://bugs.kde.org/show_bug.cgi?id=377050 :)

I will forward them to this thread also...

**Comment by psifidotos** [comment] 2017-03-06 19:12
@JenaPlinsky try to disable from your systray the media player and check please if it reoccurs... It is the only way an appletRemoval could occur...

**Comment by JenaPlinsky** [comment] 2017-03-06 19:58
@psifidotos as soon as I disable the media player in the systray plasmashell crash !!!! 👍 

Once the media player is disabled ... VLC works fine and can be shut down without crashing the system
Thus, the problem seems to be confined to the media player applet

**Comment by JenaPlinsky** [comment] 2017-03-06 20:52
DragonPlayer  
Amarok
MPV
MPlayer

all these don't crash plasmashell or Latte

**Closed** 2017-03-07 16:37 UTC
Labels: reported!, upstream
