### ISSUE TITLE
Proposing more configuration options for future versions of Latte Dock.

### ISSUE THREAD

**Issue by Petross404** [psifidotos/Latte-Dock#224] opened 2017-03-05 14:48 UTC
In this thread let the users and the developers to talk about various configuration options that they would like Latte to provide.

* I would like to be able to configure, the "density" of the launchers for a given size. I mean how far apart are one of another.

* Another feature would be to change the "distance" that the dock has from the screen's egde. Maybe some negative numbers could be given, so if a user has a small monitor could take advantage of some more pixels.

* Also it would be nice if custom launchers could be created, where the user can define the icon or the exact command that a launcher should execute. (Eg I use PopcornTime and and I can't create a launcher).

Please write your opinion too, so we discuss them and Latte adopts the best of the features out there. 👍

**Comment by adrfantini** [comment] 2017-03-07 14:31
One more: the ability to have it offset from the center by a given amount. Plank does this, and for vertical panels I do think it looks quite a bit better to have it at 30% height instead of 0/50/100% (bottom, centre, top).

**Comment by psifidotos** [comment] 2017-03-07 14:52
> One more: the ability to have it offset from the center by a given amount. Plank does this, and for vertical panels I do think it looks quite a bit better to have it at 30% height instead of 0/50/100% (bottom, centre, top).

This a lot of work to be supported because of many advanced feautures already merged in... Plank is doing many things but Latte on the other hand provides features that Plank doesnt... 

Multiple dock instances, window previews, Fill alignment, painting shadows externally, using blur and background contrast effects in some cases for the panel background, smart positioning for the dock instances etc etc....

**Comment by adrfantini** [comment] 2017-03-07 15:30
Yeah of course it was just an idea, only viable if the developing effort
required is not too high.
By the way, I just switched from Plank to Latte and I love it! Keep it up!

2017-03-07 15:52 GMT+01:00 Michail Vourlakos <notifications@github.com>:

**Comment by JenaPlinsky** [comment] 2017-03-07 17:31
@adrfantini Are u italian?

**Comment by adrfantini** [comment] 2017-03-07 21:44
Yep, indeed.

2017-03-07 18:31 GMT+01:00 Ivan Bordoni <notifications@github.com>:

**Comment by adrfantini** [comment] 2017-03-08 07:20
Ciao @JenaPlinsky , I actually think that the Italian Plasma userbase, while of course not as vast and diversified as e.g. the German one, is quite big and active. But this is not the place for having such a chat.

**Comment by psifidotos** [comment] 2017-03-09 15:49
> I would like to be able to configure, the "density" of the launchers for a given size. I mean how far apart are one of another.

sounds logical... but not so simple to support currently

> Another feature would be to change the "distance" that the dock has from the screen's egde. Maybe some negative numbers could be given, so if a user has a small monitor could take advantage of some more pixels.

we can always support adding spacers in Latte, that would be a transparent rectangle in the size of the current applet size which as a regular applet can be moved around wherever you want it... of course this is not precise in a matters of pixels if such is the need of the user...

> Also it would be nice if custom launchers could be created, where the user can define the icon or the exact command that a launcher should execute. (Eg I use PopcornTime and and I can't create a launcher).

setting the icon was a very old request but I cant remember why that was difficult back in the older days... concerning launchers creation this is upstream from libtaskmanager as long as you are able to create such launcher in any way with the regular plasma taskmanager then this will be also possible with Latte

**Comment by Petross404** [comment] 2017-03-10 08:36
Yes, spacers is another feature. This way one can organize the launchers and a space will indicate the limits of a 'category' of apps. 

But I am afraid one of us isn't understood. When I am talking about distance I mean from the bottom. If the applets 'touch' the screen's border.

**Comment by psifidotos** [comment] 2017-03-10 08:45
Can you create a mockup showing how this would look like in different cases with also the tasks plasmoid in it?

I cant think of a case that this will improve Latte appearance

**Comment by Petross404** [comment] 2017-03-10 18:09
The only meaningfull mockup I could make is this:
![untitled2](https://cloud.githubusercontent.com/assets/18561627/23806958/6fc17792-05cc-11e7-9c85-658e80f08dc4.png)

This way (by adding spaces) one can have clear "borders" or limits for every grouped launchers - eg first some plasma utilities, space, internet applications, space, media players, space, etc.

As for the distance from the screen's edge I mean the small gap underneath the launchers. 
![screenshot_20170310_200504](https://cloud.githubusercontent.com/assets/18561627/23807054/e719e392-05cc-11e7-93fe-77c316205c2d.png)

I know that I am using a transparent theme and that there is located something like a bar or something for the icons to "rest" on it and it can't be shown in my setup. But it would be good if I could just "place" my launcher on the edge of the screen instead of having a little gap in between. I can't explain my self more clearly in english :(

**Comment by psifidotos** [comment] 2017-03-10 20:51
> This way (by adding spaces) one can have clear "borders" or limits for every grouped launchers - eg first some plasma utilities, space, internet applications, space, media players, space, etc.

this can be easily added if you want, is already supported in the code but hasnt been exposed yet to the user...

> I know that I am using a transparent theme and that there is located something like a bar or something for the icons to "rest" on it and it can't be shown in my setup. But it would be good if I could just "place" my launcher on the edge of the screen instead of having a little gap in between.

the gap you are mentioning is used for showing the active window, windows instances... etc... if the user removes that gap then how the above states will be shown?

**Closed** 2017-03-10 23:29 UTC

**Comment by psifidotos** [comment] 2017-03-10 23:30
![image](https://cloud.githubusercontent.com/assets/2216474/23817238/41ae5464-05fa-11e7-8e2c-785f474a8b9d.png)

**Comment by Petross404** [comment] 2017-03-11 05:54
@psifidotos I reversed the position of dots and placed them above the launchers.

Anyway, no harm done. Thanks for the spacers :)

**Comment by psifidotos** [comment] 2017-03-11 05:57
> @psifidotos I reversed the position of dots and placed them above the launchers.

Yes... this is way to make the gap you were mentioning to minimum...

**Comment by Petross404** [comment] 2017-03-11 06:59
So, will a configuration option to lower the dock (even if it is for the minority of the users) ever be implemented?

**Comment by psifidotos** [comment] 2017-03-11 09:09
> So, will a configuration option to lower the dock (even if it is for the minority of the users) ever be implemented?

for what case ? dont on top of the task or on bottom of the tasks?

If you mean the onbottom case the concerns have been presented... how will the dots and lines for the tasks will be shown?

**Comment by Petross404** [comment] 2017-03-11 09:15
Not only for the bottom docks...if one has the dock on the side as well.

If the user has reversed the dots to be shown above the launchers, an option could be enabled to move the dock closer to the screen's edge. Otherwise, default behavior is kept

**Comment by psifidotos** [comment] 2017-03-11 09:39
you mean something like? the green rectangles touch the screen edge

![image](https://cloud.githubusercontent.com/assets/2216474/23822167/4720fe2e-064f-11e7-90ab-e641e2a3d58f.png)

**Comment by Petross404** [comment] 2017-03-11 10:48
> you mean something like? the green rectangles touch the screen edge

I mean **exactly** that. Because I disabled `Show Panel Background` I was looking for a way to do what the pic you posted shows.

BTW The third applet is weather applet? What is it's name? It's elegant.

**Comment by psifidotos** [comment] 2017-03-11 10:52
> I mean exactly that. Because I disabled Show Panel Background I was looking for a way to do what the pic you posted shows.

the picture is real... I was just playing with the margins to see how easy is this to be achieved for the reverse state of tasks... it can be done... when I find free time with not something to do, I will add it... :)

> BTW The third applet is weather applet? What is it's name? It's elegant.

in vertical mode:
https://www.linux-apps.com/content/show.php/Weather+Widget?content=169572

**Comment by Petross404** [comment] 2017-03-11 11:42
First I want to say thank you. Second I was talking with one developer at #gentoo-proxy-maint about Latte Dock and it's ebuild. As soon as release 0.6 is out, we will discuss about bringing latte-dock in gentoo, officially.

So...keep up the good work, cause the userbase is about to get somewhat bigger. I wish I knew how to program to help you even more guys and make Latte even more mature. Anyway, thanks again

**Comment by psifidotos** [comment] 2017-03-11 11:57
> As soon as release 0.6 is out, we will discuss about bringing latte-dock in gentoo, officially.

nice news!!
there are already packages for openSuse and Arch but it is from the first version 0.5.91 which is much outdated...
with the current plan version 0.6.0 is scheduled for the first weeks of April.. there will be a big announcement with features, videos, etc...

**Comment by Petross404** [comment] 2017-03-11 18:49
Ahem...Stupid question, but "Get New Widgets" can install Latte? If so there is no reason for packaging. Unless this way only the widget is provided...

**Comment by Petross404** [comment] 2017-03-17 15:59
@psifidotos I tried spacers for the first time. I can only put them as plasmoid outside the launchers or I can put inside the plasmoid that holds the launchers?

**Comment by psifidotos** [comment] 2017-03-17 16:02
> put them as plasmoid outside the launchers or I can put inside the plasmoid that holds the launchers?

you can only put them as plasmoids outside the launchers,
you can not put them inside the plasmoid holding the launchers and unfortunately I dont think this is even technologically possible...

**Comment by Petross404** [comment] 2017-03-17 16:14
Hmm...Unless a "null", empty launcher could be created to serve as a space, but again neither custom launchers are supported from Plasma.

Maybe in the future something will change :) Thank you psifidote

**Comment by psifidotos** [comment] 2017-03-17 16:28
> Hmm...Unless a "null", empty launcher could be created to serve as a space, but again neither custom launchers are supported from Plasma

this a good idea!!!!! I hadnt thought  that.... we could create a ghost launcher!!!! that could be done!!! but let's leave that for 0.7 version!!! ;)

**Comment by Petross404** [comment] 2017-03-17 16:34
Last day I saw that audoban has created a [seperator](https://store.kde.org/p/998907/). Can this be integrated in Latte somehow?

You know to serve as a "spacer" till a another solution is found. But again, it might not be able to lie inside launcher's plasmoid. Arghh Plasma is somewhat restive!

**Comment by psifidotos** [comment] 2017-03-17 16:40
> Last day I saw that audoban has created a seperator. Can this be integrated in Latte somehow?

it can be added of course as an applet but not inside the tasks plasmoid...

**Comment by Petross404** [comment] 2017-03-17 16:41
> but not inside the tasks plasmoid...

Well, that's the point!

**Comment by John-Gee** [comment] 2017-06-25 06:43
Hello,

I've just started using Latte, and it really is nice, but there are 1 thing I am heavily missing, and a few optional ones.

The big one for me: 
I would like an option to have the window's title displayed somehow in the launcher. Honestly I am not even sure how that would work, but I always have multiple browser windows opened, and in the current situation there is no quick way for me to know which is which, I have to either hover and wait for the preview, or just click them one by one till I get the right one.


Less important ones:

- It would be nice if the launcher icons could be configured to be smaller than the icons of apps running, I have that with standard Plasma and I really like it. Maybe also allow these launchers to be in a somewhat different place, though I probably could do that with spacers. For now I'm using the quicklaunch applet for that.

- This might be my lack of understanding, but some applets reach to the mouse and zoom, while others don't. In my case windows / Latte Plasmoid, and Application Launcher react but Pager, Quicklaunch, Systray and the Digital Clock (not that this one matters, but the Analogic one did react) don't. It feels uneven.

- Allow more than one dock on the same border. I should be able to get one dock in each corner and one in the center, provided they don't overlap each other.

Thank you!

**Comment by psifidotos** [comment] 2017-06-25 07:18
> I would like an option to have the window's title displayed somehow in the launcher. Honestly I am not even sure how that would work, but I always have multiple browser windows opened,..

I tried once to implement it, the result was horrible. The tooltips showing window tiltes were out of place and the behavior wasnt consistent. I think that the only  approach that makes sense in to have a signle dock top-centered tooltip that changes its title based on hovering. I dont know if my second attempt will produce something that I will like to merge #567

>It would be nice if the launcher icons could be configured to be smaller than the icons of apps running, I have that with standard Plasma and I really like it. Maybe also allow these launchers to be in a somewhat different place, 

this is a design decision for Latte, the more same size and the better alignment between icons the more concrete the design decision. Personally to distinguish them I use separators. You can have separators everywhere you want....

![image](https://user-images.githubusercontent.com/2216474/27514288-fdca14ca-598e-11e7-9c1d-f58a05ffa272.png)

> This might be my lack of understanding, but some applets reach to the mouse and zoom, while others don't

this isnt Latte fault, it is that these plasmoids havent been created by their programmers with Latte case in their mind. When they were zoomed they were changing their layouts, so Latte added a heuristic algorithm for them to disable their animation in order to not break the parabolic effect experience. Personally all these applets I put them on the dock edges. I hope that in the future programmers will embrace the Latte case and provide plasmoids/applets that work beautifully with Latte

> Allow more than one dock on the same border. I should be able to get one dock in each corner and one in the center, provided they don't overlap each other.

This is harder than it sounds based on how Latte was designed. What is that you cant achieve with the Justify mode? You can always of course combine Latte with plasma panels which are placed everywhere. I have seen a user case that put two plasma panels left and right and Latte in the center

**Comment by John-Gee** [comment] 2017-06-25 07:47
> I tried once to implement it, the result was horrible. The tooltips showing window tiltes were out of place and the behavior wasnt consistent. I think that the only approach that makes sense in to have a signle dock top-centered tooltip that changes its title based on hovering. I dont know if my second attempt will produce something that I will like to merge #567

I understand, I have no idea how it could work visually, but I still feel like it's needed, so I hoped someone would know better.

> this is a design decision for Latte, the more same size and the better alignment between icons the more concrete the design decision. Personally to distinguish them I use separators. You can have separators everywhere you want....

Hmm, that could work I suppose. I only have 5 launchers, so nothing that takes too much room, I guess it's more a matter of what I'm used to. How about a different color scheme, maybe just darker icons or something alike if the app is not launched.

> this isnt Latte fault, it is that these plasmoids havent been created by their programmers with Latte case in their mind. When they were zoomed they were changing their layouts, so Latte added a heuristic algorithm for them to disable their animation in order to not break the parabolic effect experience. Personally all these applets I put them on the dock edges. I hope that in the future programmers will embrace the Latte case and provide plasmoids/applets that work beautifully with Latte

I see. Then does that mean that the Application Launcher is Latte compatible? Are there replacements applets that you'd suggest?

> This is harder than it sounds based on how Latte was designed. What is that you cant achieve with the Justify mode? You can always of course combine Latte with plasma panels which are placed everywhere. I have seen a user case that put two plasma panels left and right and Latte in the center

I was just thinking that having 3 separate docks would allow the space between them to remain trigger-free in the case of auto-hiding, while justifying the dock uses the whole border and so will trigger everywhere on it. It's nothing of importance.


Thank you for the quick reply!

**Comment by psifidotos** [comment] 2017-06-25 08:58
> How about a different color scheme, maybe just darker icons or something alike if the app is not launched.

i have tried in the past with opacity, contrast, color adjustment... didnt like any... the design decision to distinguish launchers from tasks is the dots and lines under them, if they dont have they are launchers

> I see. Then does that mean that the Application Launcher is Latte compatible? Are there replacements applets that you'd suggest?

most applets that provide an icon or representation that fits in a rectangle when they are in a dock/panel are Latte compatible, such as the analog clock also... i dont know any replacements yet that provide a better Latte experience. The thing is that any developer that creates plasmoids doesnt have to change anything from its workflow to make them Latte compatible.... now that Latte is being adopted from more users I believe that developers at store.kde.org would like to support the case... if you find a plasmoid in the kde store that doesnt work beaitifully with Latte, ping the developer and make a feature request

**Comment by John-Gee** [comment] 2017-06-25 09:09
Alright, I will do that.

Thank you!
