### ISSUE TITLE
Dock on the left side won't appear when mouse hover over. But putting dock on right, top, bottom works normally.

### ISSUE THREAD

**Issue by kevinsmia1939** [psifidotos/Latte-Dock#999] opened 2018-04-19 05:16 UTC
Manjaro KDE stable
latte dock 0.7.4-1
I place a dock on the left of my screen. 
Set the Visibility to Dodge Active/Dodge All Windows/Dodge Maximized/Auto Hide
Place windows/active windows over the left dock.
Left dock hide normally as it should.
Drag mouse to left side to try to make dock appear.
Dock on left side don't appear.
Only happen to left side.
Swapping with left dock with bottom dock, same problem.
Something wrong with "left" location specifically.
Thanks

**Comment by kevinsmia1939** [comment] 2018-04-19 08:04
Some update
I found out that if the mouse was push all the way the the left corner of the screen. The dock don't appear. But if I move mouse cursor to the right by about 1 pixel the dock appear.
Hope this give some clue.

**Comment by psifidotos** [comment] 2018-04-19 11:39
Has been fixed in master a little bit but in general is a plasma X11 limitation

**Closed by psifidotos** 2018-04-19 11:39 UTC

**Comment by kevinsmia1939** [comment] 2018-04-19 12:27
What do you mean by fix a little bit? Is there still a few problem on the master? Are there plans to fix this plasma limitation? Thanks.

**Comment by psifidotos** [comment] 2018-04-19 12:36
The issue is related to plasma touch gestures. If you disable touch gestures for left edge from plasma systemsettings and relogin afterwards the issue is gone.

In master even with touch gestures under X11 the experience is a little better.

For wayland the issue doesnt exist.

**Comment by kevinsmia1939** [comment] 2018-04-19 13:02
@psifidotos Disabling touch gesture and re-login works thanks.
