### ISSUE TITLE
Make Latte compatible with kdesrc-build tool

### ISSUE THREAD

**Issue by kurthindenburg** [psifidotos/Latte-Dock#453] opened 2017-05-10 00:32 UTC
I'm trying to use kdesrc-build.kde.org to build from github master on a neon.kde.org OS

Are the packages I have not recent enough?

CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/KF5Package/KF5PackageMacros.cmake:55 (message):
  couldn't generate metainfo for org.kde.latte.shell: Error: Can't find
  plugin metadata: /mnt/projects/Devel/KDE/src/latte-dock/build/shell/release

---

[  3%] Generating org.kde.latte.shell-shells-metadata.json
Error: File not found:  "/mnt/projects/Devel/KDE/src/latte-dock/build/shell/release/metadata.desktop" 
 ((null):0, (null))
Error: Failed to resolve filenames "/mnt/projects/Devel/KDE/src/latte-dock/build/shell/release/metadata.desktop" "" 
 ((null):0, (null))
CMakeFiles/org.kde.latte.shell-shells-metadata-json.dir/build.make:60: recipe for target 'org.kde.latte.shell-shells-metadata.json' failed

**Comment by psifidotos** [comment] 2017-05-10 04:12
What command are you using to build Latte?

**Comment by kurthindenburg** [comment] 2017-05-10 12:17
[cmake.txt](https://github.com/psifidotos/Latte-Dock/files/989678/cmake.txt)
[build.txt](https://github.com/psifidotos/Latte-Dock/files/989679/build.txt)

**Comment by psifidotos** [comment] 2017-05-10 12:20
No i mean... do you run,

sh install.sh

and these are the errors?

**Comment by kurthindenburg** [comment] 2017-05-10 12:25
The command I use is 'kdesrc-build latte-dock --debug'

Top of cmake.txt has the actual command it runs:

# kdesrc-build running: 'cmake' '/mnt/projects/Devel/KDE/src/latte-dock' '-DBUILD_TESTING=TRUE' '-DCMAKE_BUILD_TYPE:STRING=debug' '-DCMAKE_CXX_FLAGS:STRING=-pipe ' '-DCMAKE_INSTALL_PREFIX=/mnt/projects/Devel/KDE/inst/kdeneon/kde5trunk'
# from directory: /mnt/projects/Devel/KDE/build/latte-dock

**Comment by psifidotos** [comment] 2017-05-10 12:28
try run:

sh install.sh

**Comment by kurthindenburg** [comment] 2017-05-10 12:31
The whole point of kdesrc-build is to have everything automated; if latte-dock can't be build using it, that's fine. Thanks.

**Comment by psifidotos** [comment] 2017-05-10 12:39
if Latte cant use kdesrc-build yet, nothing prevents from someone to help in order to make it compatible with it... the only reason may this doesnt work is that some cmakelist files reference the build directory statically... do you know another way to access the absolute path of the build directory inside a CMakeLists.txt file?

**Comment by kurthindenburg** [comment] 2017-05-10 13:43
I think "${CMAKE_BUILD_DIR}" but I'd have to read docs/test it

**Comment by psifidotos** [comment] 2017-05-10 13:46
I have just sent an email to plasma devs... the issue is with **_plasma_install_package_** I cant find a way to use absolute paths.... kdesrc-build usually puts the build directory far from the source code... so either plasma_install_package should be able to install from the build directory and not the source directory or I dont know yet what plasma devs propose... :) we 'll see...

**Comment by psifidotos** [comment] 2017-05-10 15:05
@kurthindenburg can you please check branch `fix453` if this is ok with kdesrc-build?

**Comment by kurthindenburg** [comment] 2017-05-10 15:09
[100%] Linking CXX executable latte-dock
/usr/lib/x86_64-linux-gnu/libKF5WaylandClient.so.5.34.0: undefined reference to `wl_proxy_marshal_constructor_versioned'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
app/CMakeFiles/latte-dock.dir/build.make:501: recipe for target 'app/latte-dock' failed
make[2]: *** [app/latte-dock] Error 1
CMakeFiles/Makefile2:230: recipe for target 'app/CMakeFiles/latte-dock.dir/all' failed

**Comment by psifidotos** [comment] 2017-05-10 15:11
maybe  #346 ?

**Comment by psifidotos** [comment] 2017-05-10 15:12
@kurthindenburg you know anything about `clang` ?

**Comment by kurthindenburg** [comment] 2017-05-10 15:15
no, I could test with gcc - give me a minute

**Comment by psifidotos** [comment] 2017-05-10 15:15
I merged in master because this is no longer an issue with our CMake files...

**Comment by kurthindenburg** [comment] 2017-05-10 15:17
OK another issue than - thanks for the kdesrc-build fix

[100%] Linking CXX executable latte-dock
/usr/lib/x86_64-linux-gnu/libKF5WaylandClient.so.5.34.0: undefined reference to `wl_proxy_marshal_constructor_versioned'
collect2: error: ld returned 1 exit status
app/CMakeFiles/latte-dock.dir/build.make:501: recipe for target 'app/latte-dock' failed

**Comment by psifidotos** [comment] 2017-05-10 15:28
it sounds like the wayland version is not sufficient... but I cant be sure...

@audoban do you have any other ideas?

**Comment by psifidotos** [comment] 2017-05-10 15:41
@kurthindenburg it sounds like you have built kde frameworks yourself but at some point wayland was updated... So the kde frameworks you are using (kwayland more specific) uses other wayland version than the one provided by the system...

**Comment by kurthindenburg** [comment] 2017-05-11 00:19
I use neon.kde.org developer install  - if the versions I have installed are not enough, could you update the CMakeLists.txt version requirements?

**Comment by psifidotos** [comment] 2017-05-11 04:22
This isnt in our side... it looks like an issue with your system, not even neon... the minimum requirement for kwayland is 5.29 and you are using 5.34... ask dor help in neon forums and at #203

**Closed by psifidotos** 2017-05-11 04:22 UTC
Labels: enhancement

**Comment by psifidotos** [comment] 2017-05-11 04:26
one more thing, if you run our own, sh install.sh, does the same problem appears?

**Comment by kurthindenburg** [comment] 2017-05-11 12:49
same issue

**Comment by psifidotos** [comment] 2017-05-11 12:52
it is almost certain then that something is wrong in your system... there is a chance that your distro updated wayland and didnt build properly kwayland afterwards

**Comment by psifidotos** [comment] 2017-05-24 12:01
@kurthindenburg can you please tell me how did you manage to use latte with kdesrc-build? I ask because latte is not in standard modules, did ypu add it yourself ?

**Comment by kurthindenburg** [comment] 2017-05-24 12:10
Add this to your .kdesrc-buildrc - this format basically works for anything using cmake and git

module latte-dock
    repository git://github.com/psifidotos/Latte-Dock.git
    branch master
end module

Also, as a FYI, neon.kde.org fixed the linking issue I had.

**Comment by psifidotos** [comment] 2017-05-24 16:00
thank you !

**Comment by psifidotos** [comment] 2017-05-24 16:01
I hope the experience is ok for you now...
