### ISSUE TITLE
Duplicate item for Firefox after upgrade

### ISSUE THREAD

**Issue by Aetf** [psifidotos/Latte-Dock#341] opened 2017-03-28 21:55 UTC
When Firefox starts, instead of replace the launcher item, another new item is created for the new window. See screenshot:

![image](https://cloud.githubusercontent.com/assets/1519759/24426671/50b52d0e-13d6-11e7-983d-63e4347fed80.png)

Relevant lines in `lattedock-appletsrc`:
```
[Containments][1][Applets][2][Configuration][General]
isInLatteDock=true
launchers=multi;*;3;file:///usr/share/applications/firefox-nightly.desktop;file:///usr/share/applications/atom.desktop;file:///home/aetf/.local/share/applications/netease-cloud-music.desktop
```

Also, if I instead right click and pin the Firefox window item, it losses icon after I close Firefox.

![image](https://cloud.githubusercontent.com/assets/1519759/24429316/889cbbac-13df-11e7-82c1-056a2200331f.png)

```
[Containments][1][Applets][2][Configuration][General]
isInLatteDock=true
launchers=multi;*;4;file:///usr/share/applications/firefox-nightly.desktop;file:///usr/share/applications/atom.desktop;file:///home/aetf/.local/share/applications/netease-cloud-music.desktop;file:///usr/bin/firefox-nightly
```

I'm using version 0.5.98, and there's no issue when I used 0.5.91

**Comment by psifidotos** [comment] 2017-03-29 04:39
Try to reproduce with plasma taskmanager... the first issue is not from Latte, either plasma or firefox update...

try and the second issue with plasma taskmanager, there is a chance that this is not Latte faults .... both issues are happening because of faulty desktop file

**Comment by psifidotos** [comment] 2017-03-29 04:40
and more specific the firefox-nightly desktop file

**Comment by Aetf** [comment] 2017-03-29 05:21
The firefox nightly desktop file doesn't change during the upgrade. Anyway I'll check if there's anything wrong with that once I get to my computer.

**Comment by psifidotos** [comment] 2017-03-29 06:45
check also the plasma taskmanager behavior... Latte is using the plasma tasks model

**Comment by Aetf** [comment] 2017-03-29 14:48
Firefox desktop file (translations for GenericName, Comment are excluded for brief), nothing seems wrong to me...
```
[Desktop Entry]
Name=Firefox Nightly
GenericName=Web Browser
Comment=Browse the World Wide Web
Exec=firefox-nightly %u
Terminal=false
Type=Application
Icon=firefox-nightly-icon
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;
StartupNotify=true
Actions=NewTab;NewWindow;NewPrivateWindow;

[Desktop Action NewTab]
Name=Open new tab
Exec=firefox-nightly -new-tab about:newtab

[Desktop Action NewWindow]
Name=Open new window
Exec=firefox-nightly -new-window

[Desktop Action NewPrivateWindow]
Name=New private window
Exec=firefox-nightly -private-window
```

Created a new panel on the left side with plasma task manager. Firefox entry is pinned before start. No duplication after window open. No icon error.

![image](https://cloud.githubusercontent.com/assets/1519759/24460717/22bf4aaa-146d-11e7-8f52-97f25140e51f.png)

**Comment by psifidotos** [comment] 2017-03-29 14:52
@Aetf is this also true with the plasma only-icons task manager ?

**Comment by Aetf** [comment] 2017-03-29 14:57
Yes, icons only task manager also works well.

![image](https://cloud.githubusercontent.com/assets/1519759/24461202/6bd56a48-146e-11e7-8944-727eccbca068.png)

**Comment by psifidotos** [comment] 2017-03-29 14:59
@Aetf are you sure you have pinned firefox as a launcher in the plasma taskmanager ?

**Comment by Aetf** [comment] 2017-03-29 15:11
![output2](https://cloud.githubusercontent.com/assets/1519759/24461820/6025e9b4-1470-11e7-8e91-2d0603227d1a.gif)

**Comment by psifidotos** [comment] 2017-03-29 15:27
@Aetf did you notice that for a sec even the plasma taskmanager in showing a second firefox icon and afterwards it removes it ?

very strange behavior, we will have this open until we find other cases also and understand what is happening...

**Comment by Aetf** [comment] 2017-03-29 15:37
Yeah I noticed that...

My intuition is that somehow the opened window is recognized as `/usr/bin/firefox-nightly` while the pinned launcher in latte dock is `/usr/share/application/firefox-nightly.desktop`. When the window is pinned in latte dock, it is added as `/usr/bin/firefox-nightly`, so that's different from the launcher.

Actually, I got the launcher in latte dock with icon by manually edit `lattedock-appletsrc` and change `/usr/bin/firefox-nightly` to `/usr/share/application/firefox-nightly.desktop`.

For the plasma task manager, I'm not sure what it uses for the launcher. But probably it does something and recognizes that `/usr/share/application/firefox-nightly.desktop` and `/usr/bin/firefox-nightly` are the same app so it merges them later.

Oddly enough, this worked for latte 0.5.91

**Comment by Aetf** [comment] 2017-03-29 15:41
Oh, from [`Latte Dock-appletsrc`](https://github.com/Aetf/Dotfiles/blob/b62c6d16effabbfb67474b07d89c363414ddcf07/home/config/Latte%20Dock-appletsrc#L51) before the upgrade, firefox was pinned as `/usr/bin/firefox-nightly`, but with `?iconData=....`, so that's why it correctly shows icon.

Probably I shouldn't manually use the desktop file as launcher. But anyway latte should add the `iconData` parameter to the uri, or preferably, directly uses desktop file, as for other applications.

**Comment by psifidotos** [comment] 2017-03-29 16:05
> Probably I shouldn't manually use the desktop file as launcher. But anyway latte should add the iconData parameter to the uri, or preferably, directly uses desktop file, as for other applications.

all this behavior you are mentioning is done from plasma libtaskmanager... Latte has nothing to do with it except the ?iconData=.... which has an internal code to remove it...

This was done because it was creating enormous appletsrc files. The identification of the launcher to /usr/bin/firefox-nightly is done also from plasma libtaskmanager and it is a mistake in my opinion. The launcher url that the libtaskmanager should return is : /usr/share/applications/firefox-nightly.desktop

feel free to provide patches....

also, the launcher url we are using from libtaskmanager is LauncherUrlWithoutIcon, that means that the launcher shouldnt contain any icon data at all...

**Comment by Aetf** [comment] 2017-03-29 16:42
Tried other applications. It seems this only happens to some of the applications. Sublime Text also loses icon once pinned, but Atom, WMail and Netease Cloud Music works well. 

The behavior is totally random to me :( and unfortunately I'm not familiar with either latte or libtaskmanager codebase...

**Comment by psifidotos** [comment] 2017-04-10 07:58
@Aetf as long as you are running >=plasma 5.9 you could try our branch **launchers59**.... contains the new launchers mechanism and there is a big chance that fixes this for you... that branch will be merged in master in two weeks...

**Comment by Aetf** [comment] 2017-04-10 18:08
Yeah, `launchers59` branch works, it pins the window with iconData appended to the url. So after closing the window, it remains the window icon.

However, the icon is pixelated, probably because it's taken from the window icon and thus doesn't have high enough resolution compared to the launcher icon (the left one).

![image](https://cloud.githubusercontent.com/assets/1519759/24875573/8a6f9384-1df6-11e7-914c-84b683761274.png)

Actually the root reason is that `libtaskmanager` should return desktop file rather than binary path for the window. And I finally found the reason for this: the window class should match the desktop file name, or there must be a `StartupWMClass` entry in the desktop file. After I change the desktop file accordingly, I can get launcher icon nicely associated with the window.

**Comment by psifidotos** [comment] 2017-04-10 18:54
nice... `launchers59 ` provide  us exactly the same behavior with official plasma taskmanager... any problem we have, it should also exist for the official plasma taskmanager and must be fixed `upstream`...

**Comment by psifidotos** [comment] 2017-04-21 13:41
fixed in master

**Closed by psifidotos** 2017-04-21 13:41 UTC
Labels: bug, needsinfo
