### ISSUE TITLE
audio icon + mute option as in task manager

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#142] opened 2017-02-05 12:53 UTC
This is the description of plasma 5.9 announcement about this feature:

"And should you rather want to focus on one particular task, applications currently playing audio are marked in Task Manager similar to how it’s done in modern web browsers. Together with a button to mute the offending application, this can help you stay focused."

and this link points to an illustrative image:

[https://www.kde.org/announcements/plasma-5.9/mute.png](https://www.kde.org/announcements/plasma-5.9/mute.png)

Perhaps adding the icon is the most tricky part given the small space available, but I would propose doing as in task completion, this is, adding a relatively small circle at top right location, where to show the small audio icon.

What do you think?

**Comment by psifidotos** [comment] 2017-02-05 12:56
this Plasma 5.9 specific, supporting it means breaking compatibility with Plasma 5.8...
It is also relevant to #138 that were introduced for Plasma 5.9

Personally I dont find it yet that important... I would prefer to handle #138 first and when we decide to break compatibility with Plasma 5.8 then we could implement also this one...

**Comment by polarathene** [comment] 2017-02-10 03:14
Is there no way to support new features in Plasma with conditonial checks? Such as the audio/mute only being supported on Plasma 5.9+, no access to such information? It sounds unfortunate if 5.8 users stop receiving updates because of breaking compatibilty to support newer Plasma features, especially since 5.8 is a LTS.

**Comment by psifidotos** [comment] 2017-02-10 05:31
I agree, no new feature breaking plasma 5.8 exerience should be accepted

**Comment by polarathene** [comment] 2017-02-10 07:08
@psifidotos Is your project unable to provide conditional features by checking what Plasma version is provided by the system? I've not done any KDE/Plasma/Qt development yet, not sure if this is possible(I would assume it would be), it's fairly common on other platforms to do feature detection or conditional compilation with environment vars.

**Comment by psifidotos** [comment] 2017-02-10 07:45
it could be possible when the feature is implemented... but the feature is not yet a priority

**Comment by polarathene** [comment] 2017-02-10 07:48
@psifidotos Good to know, sounded like you could not add new feature that would break 5.8. I thought that meant no way to have conditions based on Plasma version to prevent breakage.

**Comment by kupiqu** [comment] 2017-02-10 11:07
Wondering whether at some point it would make sense to have a Latte LTS version or branch

**Comment by polarathene** [comment] 2017-02-10 11:16
@kupiqu Latte hasn't reached a proper release yet far as I understand. It's not that common far as I know to releae LTS versions for apps. 

What you can see sometimes is a version is released that many use but for whatever reason do not update to a new release(usually because of API breakage or similar to justify a new major version), so you have a v1 and v2, then when bugs get fixed they can be merged into the v1 branch which does not contain the new features/code of v2. 

Look into gitflow, it's probably similar to what you're asking for.

**Comment by kupiqu** [comment] 2017-02-10 11:19
I agree, that's basically why I said, at some point :)

**Comment by psifidotos** [comment] 2017-04-07 12:07
I can try to add this for upcoming 0.7 version...

**Comment by psifidotos** [comment] 2017-04-12 17:20
_### Just to add here... I observed some media players e.g. **bomi and baka** do not work properly with mpris connection in my system and I should investigate this also when implementing this feature_

**Comment by mmiat** [comment] 2017-04-23 11:00
+1

**Closed** 2017-04-30 15:54 UTC
Labels: enhancement

**Comment by psifidotos** [comment] 2017-04-30 15:55
![image](https://cloud.githubusercontent.com/assets/2216474/25565782/921e149e-2dd6-11e7-87b9-2448c331ad3c.png)

**Comment by psifidotos** [comment] 2017-04-30 16:28
the configuration option to enable/disable audio indicators.. The mpris behavior for bomi and baka was also fixed

![image](https://cloud.githubusercontent.com/assets/2216474/25566046/15565ec6-2ddb-11e7-841b-bfbfea161d3f.png)

**Comment by JenaPlinsky** [comment] 2017-04-30 20:19
Very nice and useful 👍

**Comment by kupiqu** [comment] 2017-05-01 04:18
The feature works great, thank you!

Apparently it fails with smplayer though Could you please take a look?

Also, do you think the background could be of a different color? It doesn't seem to work very well with dark icon themes such as breeze-dark or papirus-dark.

**Comment by psifidotos** [comment] 2017-05-01 05:40
It uses pulseaudio... i suppose you must make smplayer to use pulseaudio

I dont know about the dark icon themes... make a a screeshot and i can accept patches that improve the situation

**Comment by kupiqu** [comment] 2017-05-01 05:49
> It uses pulseaudio... i suppose you must make smplayer to use pulseaudio

it is already set to use pulse. It might be because it uses mpv as backend and latte is trying to set the icon on mpv (which doesn't exist), instead of smplayer?

if I check on audio applications (plasma widget) I see mpv instead of smplayer...

> I dont know about the dark icon themes... make a a screeshot and i can accept patches that improve the situation

![image](https://cloud.githubusercontent.com/assets/3875196/25573121/3f4a0608-2e10-11e7-9270-8e0b23d5283a.png)

This is with papirus-dark (same occurs with breeze-dark). For now I'm using papirus-light which sort of workarounds the issue...

**Comment by psifidotos** [comment] 2017-05-01 06:09
> it is already set to use pulse. It might be because it uses mpv as backend and latte is trying to set the icon on mpv (which doesn't exist), instead of smplayer?

probably... smplayer fault... we use the same code with plasma so I suppose same problem also there...

**Comment by kupiqu** [comment] 2017-05-01 06:12
yes, makes sense. at least we figured it out. i'll try to let the developer know about this...

**Comment by psifidotos** [comment] 2017-05-01 07:34
@kupiqu in the new design I use the theme's background color so it is a matter of correct theme choice from now on... ;)

![image](https://cloud.githubusercontent.com/assets/2216474/25574742/b2edecac-2e59-11e7-841a-520a4a112c11.png)

**Comment by kupiqu** [comment] 2017-05-01 09:51
perfect!

**Comment by kupiqu** [comment] 2017-05-09 22:43
Wrt to SMPlayer, this is the what I got from the developer:

> SMPlayer provides a MPRIS2 interface, at least it's used by the Ubuntu sound indicator to display some buttons (volume control, play/pause...) for SMPlayer. If Plasma uses instead pulseaudio then I find normal that it displays a button for mpv since it's mpv the application that sends audio, not SMPlayer.

I replied

> Plasma also uses MPRIS2 (since Plasma Workspaces 4.9 https://www.kde.org/announcements/4.9/plasma.php), and works just fine with all other applications using MPRIS2, so I don't think this is the problem.
> 
> However, it seems that SMPlayer is somehow transparent to Plasma and it only sees the mpv/mplayer backend (I also tried installing mplayer to see if this was any different, and it is not).
> 
> You mentioned "...Ubuntu sound indicator to display some buttons (volume control, play/pause...) for SMPlayer". This can also be done in Plasma audio widget but the widget doesn't realize about this being SMPlayer, but mpv instead, and this could be the same in Ubuntu, actually... Then because of this, the task manager is unable to link the audio stream (mpv) to the active application (SMPlayer), so the controls do not appear in the task bar.
> 
> What I am asking is that there should be in principle a way to export the MPRIS2 audio stream as SMPlayer instead of mpv. If that would be the case, then the issue I am referring would be fixed...

And finally he responded:

> The audio stream can't be passed through MPRIS2. 
> 
> MPRIS2 just provides some functions that other applications can use to control SMPlayer (or any application with support for MPRIS2) like play/pause, play next, change volume...

So I guess this will not get fixed anytime soon :/

**Comment by psifidotos** [comment] 2017-05-10 04:30
The developer didnt understand exactly... the issue is the following... when smplayer is using pulseaudio it identifies itself as mpv instead of smplayer, noone wants to use mpris2 to send audio, this is not possible... it is also the reason no smplayer icon is shown for that audiostream in plasma volume control... alternative apps e.g. bomi, they use pulseaudio and mpv and have solved this

**Comment by psifidotos** [comment] 2017-05-10 10:10
@kupiqu on the other hand if the developer doesnt want... we can add a workaround and blacklist smplayer... if an mpv app in not open and an smplayer is, we can forward the audio stream identification to SMPlayer...

**Comment by psifidotos** [comment] 2017-05-10 10:12
I will have a mechanism for such cases to force forwarding for audio streams during the day...

**Comment by kupiqu** [comment] 2017-05-10 10:13
That would be great!

But let me try one more (and last) time... I'm sending what you explained to the SMPlayer dev to see if he is willing to fix this...

**Comment by kupiqu** [comment] 2017-05-10 14:58
I found how to fix this:

> A fast look into 'man mpv' and I saw the following option:
> 
> --audio-client-name=<name>
>               The  application name the player reports to the audio API. Can be
>               useful if you want to force a different audio profile (e.g.  with
>               PulseAudio),  or  to  set  your  own  application name when using
>               libmpv.
> 
> I actually tried it in Options -> Preferences -> Advanced -> MPlayer/mpv with:
> 
> --audio-client-name=SMPlayer

I asked the SMPlayer dev if he wants to use this by default so other Plasma users unaware of this can also benefit...

**Comment by psifidotos** [comment] 2017-05-10 15:01
@kupiqu perfect!!! ;)

**Comment by kupiqu** [comment] 2017-05-10 22:44
SMPlayer developer added that option in svn commit r8556 :-)
