### ISSUE TITLE
Dev's Forum

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#2] opened 2016-12-25 16:18 UTC
....discussions from the developers concering Latte....

**Comment by audoban** [comment] 2016-12-25 16:41
I will begin by renaming the whole project.

**Comment by psifidotos** [comment] 2016-12-25 17:33
@audoban I just show the message... I 've already uploaded some.... I just cant load the translations for the latte shell its configuration window and I dont know why yet....

**Comment by psifidotos** [comment] 2016-12-25 17:39
@audoban do you maybe have a telegram, for more direct contact, avoiding double efforts and interact faster? You can send it to me at my e-mail if you want to...

**Comment by audoban** [comment] 2016-12-25 18:03
Yes, I have. My alias is @audoban

**Comment by audoban** [comment] 2016-12-25 18:03
Yes, I have, my alias is @audoban

**Comment by psifidotos** [comment] 2016-12-26 20:47
Johan hello!!!

I checked the visibilitymanager api, this is what is missing concerning the ui part...

Q_PROPERTIES

bool blockHiding : 
this is needed because there are circumstances that dock must not hide itself. Such a case are the contextmenus from plasmoids. For our latte plasmoid we can support this easily, for the others I dont know if this works but we can always override some functionality from the containmentinterface, this is the way now dock was doing this.

bool containsMouse : this is very useful in my old api I had named it isHovered but containsMouse is better semantics

bool isHidden : this is your state property


Q_SIGNALS

mustBeShown : informs the ui that all the animations to show must run and the ui must also update the isHidden flag

mustBeHidden : such as the previous signal but for hiding


---------


One more thing: Had you found a way in Candil to expose the dock into the containment qml part? I have found a way to do this through the qml dockui but I am not that satisfied with this implementation

**Comment by audoban** [comment] 2016-12-26 20:59
Having in mind the concept of orchestrator that you propose.
Today I will make a second visibility manager interface, I would like you to see it.

> bool blockHiding :
this is needed because there are circumstances that dock must not hide itself. Such a case are the contextmenus from plasmoids. For our latte plasmoid we can support this easily, for the others I dont know if this works but we can always override some functionality from the containmentinterface, this is the way now dock was doing this.

The method show(), fulfills that function, and when call restore(), this unlock visible state.

> bool containsMouse : this is very useful in my old api I had named it isHovered but containsMouse is better semantics

Is a better solution.

> bool isHidden : this is your state property

Q_PROPERTY visibleState was replaced for isHidden

> Q_SIGNALS
mustBeShown : informs the ui that all the animations to show must run and the ui must also update the isHidden flag
mustBeHidden : such as the previous signal but for hiding

This is possible, but this signals would be emitted before that isHiddenChanged?

**Comment by audoban** [comment] 2016-12-26 21:07
> One more thing: Had you found a way in Candil to expose the dock into the containment qml part? I have found a way to do this through the qml dockui but I am not that satisfied with this implementation

Yes I found it, exist a solution, with a context property. https://github.com/psifidotos/Latte-Dock/commit/37c349e32e30fcf1e48280b0318c2e0192efd600

**Comment by psifidotos** [comment] 2016-12-26 22:32
> One more thing: Had you found a way in Candil to expose the dock into the containment qml part? I have found a way to do this through the qml dockui but I am not that satisfied with this implementation

> Yes I found it, exist a solution, with a context property. 37c349e


Are we sure that this way isnt the same dock applied for all dock containments? In Latte the user can set multiple docks for different screens and positions...

**Comment by psifidotos** [comment] 2016-12-26 22:37
> The method show(), fulfills that function, and when call restore(), this unlock visible state.

Can you give me the series of events for you api? In my implementation I was doing this...

to show:

1. VisibilityManager sends a mustBeShown signal when the tasks must appear
2. The ui catches that signal and updates mask and plays the needed animation
3. In the end the ui sets the isHidden to false

to hide:

1. VisibilityManager sends a mustBeHidden signal
2. The ui catches that signal and plays the needed animation
3. The ui sets the isHidden to true and updates mask

> > bool containsMouse : this is very useful in my old api I had named it isHovered but containsMouse is better semantics

> Is a better solution.

Οκ...

> > bool isHidden : this is your state property

> Q_PROPERTY visibleState was replaced for isHidden

nice...

> > Q_SIGNALS
> > mustBeShown : informs the ui that all the animations to show must run and the ui must also update the isHidden flag
mustBeHidden : such as the previous signal but for hiding

> This is possible, but this signals would be emitted before that isHiddenChanged?


Yes you can read above the explanation...

**Comment by audoban** [comment] 2016-12-26 22:38
> Are we sure that this way isnt the same dock applied for all dock containments? In Latte the user can set multiple docks for different screens and positions...

[QQuickView::engine()](http://doc.qt.io/qt-5/qquickview.html#engine) each dockview has an instance of QMLEngine.

**Comment by audoban** [comment] 2016-12-26 22:57
> Can you give me the series of events for you api? In my implementation I was doing this...

> to show:
    VisibilityManager sends a mustBeShown signal when the tasks must appear
    The ui catches that signal and updates mask and plays the needed animation
    In the end the ui sets the isHidden to false
to hide:
    VisibilityManager sends a mustBeHidden signal
    The ui catches that signal and plays the needed animation
    The ui sets the isHidden to true and updates mask

Ok. Now I understand your intention.
Update the state isHidden is responsability of ui.

mustBeShown, mustBeHidden: this signals will sends whenever it can, ui must be decide whether to update the var isHidden, and always avoiding unnecessary calls.

**Comment by audoban** [comment] 2016-12-26 22:59
also, show() and restore() will be dropped.

**Comment by psifidotos** [comment] 2016-12-26 23:11
> > Are we sure that this way isnt the same dock applied for all dock containments? In Latte the user can set multiple docks for different screens and positions...

> QQuickView::engine() each dockview has an instance of QMLEngine.

Nice!!! This is cleaner!!! 
I will update the ui when I return...

> Ok. Now I understand your intention.
Update the state isHidden is responsability of ui.

> mustBeShow, mustBeHidden: this signals will sends whenever it can, ui must be decide whether to update the var isHidden, and always avoiding unnecessary calls.

Yep...

> > bool blockHiding :
> > this is needed because there are circumstances that dock must not hide itself. Such a case are the contextmenus from plasmoids. For our latte plasmoid we can support this easily, for the others I dont know if this works but we can always override some functionality from the containmentinterface, this is the way now dock was doing this.

> The method show(), fulfills that function, and when call restore(), this unlock visible state.

If these functions are doing only this then their semantics are not right and also the ui this way will not be able to access a blockingHide flag. I was using it for !immutable state in order to not hide the dock in that state but of course this behavior can be added in the internals of visibilitymanager

**Comment by psifidotos** [comment] 2016-12-26 23:16
> void showTemporarily

where did you use it? Do you remember the use case?

**Comment by psifidotos** [comment] 2016-12-26 23:24
> Yes I found it, exist a solution, with a context property. 37c349e

Actually this breaks Latte in master until I update the ui. Would it be possible to revert it back until I return? 

It would be good to have a **not break master** policy... Anything that needs more steps in order to integrate correctly with Latte can be on alternative public branches and we merge them when both of us have made the necessary commits in these branches...

**Comment by audoban** [comment] 2016-12-27 00:22
mm, I will revert the change

1. showTemporarily() same to show() but with a specific timer, and restore last state. I wanted to use for when dock needed attention set isHidden to true, and call mustBeShow, and after to false when the is triggered then call mustBeHidden.

2. showImmediately() same to show() but without a specific timer, and then I call restore() for unlock visible state.

**Comment by audoban** [comment] 2016-12-27 00:43
summarizing.

* Update the property isHidden is responsibility of ui, except when, ui call showTemporarily().

* When a window change your geometry or your state, VisibilityManager call mustBeHidden() or mustBeShown(), just when timerShow or timerHide are triggered, respectively.

* If the active window no longer intersects the dock and timerHide is stopped and timerShow run. 
This behavior will be controlled for each type of visibility. The important thing is that MustBeHide and MustBeShown will be called when needed.

**Comment by psifidotos** [comment] 2016-12-27 01:19
> Update the property isHidden is responsibility of ui

exactly...

> When a window change your geometry or your state, VisibilityManager call mustBeHidden() or mustBeShown(), just when timerShow or timerHide are triggered, respectively.

perfect...

> If the active window no longer intersects the dock, VisibilityManager stops the timerHide and timerShow began to run.
> This behavior will be controlled for each type of visibility. The important thing is that MustBeHide and MustBeShown will be called when needed.

beautiful...

> showTemporarily().

I can not think of any case this is needed... the ui updates mask when it is needed and if the backend wants to signal a showing for specific attention needed from other plasmoids, it can use the mustBeShown, mustBeHidden signals and a timer

**Comment by audoban** [comment] 2016-12-27 01:23
ok, showTemporarily() will be dropped.

**Comment by psifidotos** [comment] 2016-12-27 09:23
this api is starting to look pretty clean and neat...

**Comment by psifidotos** [comment] 2016-12-28 12:04
> This must be fixed URGENTLY

@ audoban please confirm this in the #psifidotos branch in order to merge it in master

**Comment by psifidotos** [comment] 2016-12-28 16:24
@audoban I think that it would be a good idea at some point to rename folder **corona** to something else...

e.g.
- **app**
- ....

**Comment by psifidotos** [comment] 2016-12-28 16:44
> > Are we sure that this way isnt the same dock applied for all dock containments? In Latte the user can set multiple docks for different screens and positions...
> QQuickView::engine() each dockview has an instance of QMLEngine.

class PLASMAQUICK_EXPORT ContainmentView : public KQuickAddons::QuickViewSharedEngine

above is specification of ContainmentView, probably all the containmentviews share the same engine....

**Comment by audoban** [comment] 2016-12-28 18:40
> Unfortunately this doesnt reflect in the currect reality... Latest commit in master that enables us to test it does not confirm this... All views use the same engine from corona probably... that means that with the code we are using we are exposing to all docks the same (first) dock...
Behavior confirming this: Add a second a dock in Latte, events from the first dock (as its visibility) hide also the second dock or events from the second dock change the behavior of the first one...
This must be fixed URGENTLY

> class PLASMAQUICK_EXPORT ContainmentView : public KQuickAddons::QuickViewSharedEngine

Now I'm not at home, and I can not confirm it. But it probably is.

> I think that it would be a good idea at some point to rename folder corona to something else..
 e.g. app

I'm agree. and also liblattedock, I don't understand what files go there .I want to move it to app.

**Comment by psifidotos** [comment] 2016-12-28 20:08
> I'm agree. 

ok... Let it on me... I will create to combine visibilitymanager-dev and psifidotos branches...

> and also liblattedock, I don't understand what files go there .I want to move it to app.

unfortunately this is not possible... We have a Latte plasmoid that can be added inside plasmashell for anyone wanting to test things or even for promossion... So in liblattedockplugin are put things that are used both from the plasmoid and the latte-dock application... So currently in there there are only the types and the windowsystem for compositing tracking... I dont think that anything else will be needed...

**Comment by psifidotos** [comment] 2016-12-28 20:24
> ok... Let it on me... I will create to combine visibilitymanager-dev and psifidotos branches...

@audoban 
unfortunately this didnt work out yet :) ... let me know when we are ready to try merging visibilitymanager-dev...

**Comment by psifidotos** [comment] 2016-12-28 20:47
@audoban 

I changed corona directory to app in master... When we merge the visibilitymanager-dev all the paths should be updated automatically....

**Comment by audoban** [comment] 2016-12-30 01:40
the visibility branch has been merged with master, into visibilitymanager-dev.

**Comment by psifidotos** [comment] 2016-12-30 21:44
Johan I dont quit agree with the latest way of commiting into master... The way you did it created to history paths...
there are duplicate commits...

the way I propose is the following:

1. git pull origin master (this downloads all the latest commits)
2. git checkout localbranch (you checkout your local branch that has your features, in case these **arent already commited**)
3. git rebase master (these commits are getting on top of the current master)
4. fix any conflicts
5. git checkout master
6. git merge localbranch

this is a way to keep master cleaned up from messed up history....

**Comment by psifidotos** [comment] 2017-01-01 08:38
It would be good also to commit in master regular small commits (max 2-3 together) instead of a bunch of commits... it will help the development a lot, and reviewing each other... major features of course dont fall in that category

**Comment by psifidotos** [comment] 2017-01-03 09:10
@audoban I propose to have a different default value for hideTimer, 1000, would be just fine... With 0 the dock behaves very awkward, it hides itself very fast, I dont think this is a very good first user experience

**Comment by audoban** [comment] 2017-01-03 16:41
Then, also set a default value for showTimer, 350, It is very uncomfortable for the dock to appear immediately.

**Comment by psifidotos** [comment] 2017-01-03 18:22
> Then, also set a default value for showTimer, 350, It is very uncomfortable for the dock to appear immediately.

agree... as long as this is the minimum possible...

**Comment by psifidotos** [comment] 2017-01-04 08:10
concerning the **menu** branch I wont merge... I am expecting your opinion first, for me the interaction experience that provides is ideal...

**Comment by audoban** [comment] 2017-01-04 08:53
Many separators. With a separator is sufficient, between the preferences, and close window.

And I cant see the timers.
![screenshot_20170104_032355](https://cloud.githubusercontent.com/assets/7884292/21635790/989f68a4-d22d-11e6-81f5-29558f3e1407.png)

the slider feel very slow. It is because ui config save configuration while update the value and it is very cost. On candil dock I had the same problem, and I resolved this with a property for iconSize on dockview, and then I saved the configuration just when hide ui config. 
solutions:
1. save the configuration just when user don't drag, setting to false [updateValueWhileDragging](http://doc.qt.io/qt-5/qml-qtquick-controls-slider.html#updateValueWhileDragging-prop),
2. expose a property from dockview, and save just when ui close, and restore when containment is created.

For zoom factor, is not necessary update the value while dragging.

I don't like buttons + and - for sliders, is sufficient with the slider and a text.
I like the value in percentage more than in decimal for zoom slider.
the text for values of sliders should have a minimumWidth, because when the text change also do the slider.
You can use mSize ```Layout.minimumWidth: theme.mSize(theme.defaultFont).width * 4```

**Comment by audoban** [comment] 2017-01-04 08:56
I really liked how the menu was ordered. And now it feels that it is easier to configure 👍 good job

**Comment by psifidotos** [comment] 2017-01-04 14:37
> Many separators. With a separator is sufficient, between the preferences, and close window.

You mean for the menu ? Some of them is the default of plasma, but having our own implementation fixes this easily... 

> And I cant see the timers.

This is important... From Alignment changes we will gain some space but it is a good idea to add also scrollbars in case they are needed... the buttons of add, remove dock I prefer them in the context menu and only in editing mode so I propose to leave from the configuration window. One good idea is the context menu to be also available with right click in the configuration window

> save the configuration just when user don't drag, setting to false updateValueWhileDragging,

I will go for this...

> I don't like buttons + and - for sliders, is sufficient with the slider and a text.

I agree

> I like the value in percentage more than in decimal for zoom slider.

This can fixed for user's visual perspective, but what would be minimum-maximum values?

> the text for values of sliders should have a minimumWidth, because when the text change also do the slider.
You can use mSize Layout.minimumWidth: theme.mSize(theme.defaultFont).width * 4

I'll give this a test

> I really liked how the menu was ordered. And now it feels that it is easier to configure 👍 good job

thank u... do u agree to merge menu branch in master then?

**Comment by audoban** [comment] 2017-01-04 17:41
>thank u... do u agree to merge menu branch in master then?

Yes agree,

This can fixed for user's visual perspective, but what would be minimum-maximum values?

100 and 200

> You mean for the menu ? Some of them is the default of plasma, but having our own implementation fixes this easily...

If they are by default we can leave it like this.

> the buttons of add, remove dock I prefer them in the context menu and only in editing mode so I propose to leave from the configuration window. One good idea is the context menu to be also available with right click in the configuration window

The place where they are well. But I don't have problem If you want to change them.

**Comment by psifidotos** [comment] 2017-01-04 18:51
> 100 and 200

I tried with 0% - 100% as this the zoom factor not the icon size and seems more logical...

> The place where they are well. But I don't have problem If you want to change them.

I think it will make the configuration window more clean... And it will not be for the user so easy to add, remove dock or close the application which are not that frequent actions... But I dont know how to add these actions in the containmentActions and make them to show only when the containment is in state userConfiguring....

**Comment by psifidotos** [comment] 2017-01-04 22:38
@audoban  do you know a good way to debug some crashes ? in new menu branch adding many docks and removing them creates some crashes...

**Comment by psifidotos** [comment] 2017-01-05 11:38
I think that now it's time to clean up a bit the dockview, it has some old code concerning length, maxLength, maxThickness and offset... These are not needed I think with Latte's way of doing things...

@audoban do you agree to be cleaned up from there?

**Comment by psifidotos** [comment] 2017-01-05 12:04
@audoban during the day I am going to merge the menu branch into the master... I dont find any reason not to... There is only #41 but this is something that we must handle either way...

**Comment by psifidotos** [comment] 2017-01-16 16:25
@audoban I need some help with styling in C++... I use astyle in qtcreator for c++ but in my files I have new lines that start with spaces and others that dont.. I think that this is different from your style, is it not ?

**Comment by audoban** [comment] 2017-01-16 17:07
> I think that now it's time to clean up a bit the dockview, it has some old code concerning length, maxLength, maxThickness and offset... These are not needed I think with Latte's way of doing things...

> @audoban do you agree to be cleaned up from there?

Yes I agree.

> I need some help with styling in C++... I use astyle in qtcreator for c++ but in my files I have new lines that start with spaces and others that dont.. I think that this is different from your style, is it not ?

Options > Behavior > and check button Clean whitespace and In entire document

**Comment by psifidotos** [comment] 2017-01-16 17:18
> Yes I agree.

perfect... this is done I think....

> Options > Text Editor > Behavior > and check button Clean whitespace and In entire document

perfect... finally!! I wont break again the whitespaces!!!

**Comment by audoban** [comment] 2017-01-16 18:36
Apparently is astyle who is creating those damn blanks.
I added this option to avoid this, **--delete-empty-lines** to astylerc.

**Comment by psifidotos** [comment] 2017-01-24 20:02
@audoban as the #73 is going to be delayed until Plasma provides something robust to work on with, how about #12...

Do you think we should make a release with the current feature set or try to support multi-screen also?
my opinion is half and half, as I can help with multi-screen but I dont know how must work needs...

I read in Qt 5.8 that multi-screen has become more robust and that is good news also for Qt everywhere...

**Comment by audoban** [comment] 2017-01-25 05:10
> @audoban as the #73 is going to be delayed until Plasma provides something robust to work on with, how about #12...

I can provide basic support and experimental until that Plasma will give access to API Legally

> Do you think we should make a release with the current feature set or try to support multi-screen also?
my opinion is half and half, as I can help with multi-screen but I dont know how must work needs...

This point is the most important. We need planning how we will come to improve multi screen support.

> I read in Qt 5.8 that multi-screen has become more robust and that is good news also for Qt everywhere...

Great news 👍

**Comment by psifidotos** [comment] 2017-01-25 18:18
> I can provide basic support and experimental until that Plasma will give access to API Legally

very nice...

> This point is the most important. We need planning how we will come to improve multi screen support.

What do you have in mind ? I think that at CandilDock you had some work for this...
investigating this a bit, the containment has a screen settings and in general some slots concerning changing screens. The plasmashell uses also a screenpool in order to keep a map for the screens that are used.

Two things must be taken into consideration I think:
1. QScreen which is returned from Qt is not always valid, so special care must be taken to avoid crashes concerning e.g. (m_screen->)   situations in all the Latte stack.
2. We must have in our mind that a containment (and its dockView) might be associated with a screen that even though is not active currently, it could be at a later time in the future. e.g. I am going with my laptop at work and connect it at an external monitor. 

For this external monitor I create a specific Latte dock.
1. this containment and dock is not active when I return at home so the configuration concerning this shouldnt be deleted at any time
2. when I am at home this configuration doesnt have to be loaded
3. also a garbage collector for screens that arent used any more from the user could be a good idea... This could be a list of all recorded screens and the user could be able to delete from this list any screen that doesnt use any more and there is a specific dock associated with it

what are your ideas?


Concerning Wayland I read: [http://phoronix.com/scan.php?page=news_item&px=Budgie-From-GNOME-To-Qt]()

notice how often it is mentioned in the article the fact that panel windows outside GNOME is so difficult to handle the wayland situation. Plank I think was first implemented for Budgie.
This makes me think that at some point in the future if we need something from kwin wayland we could jump in and help kwin developers to support our case. I dont think they will be negative...

But one step at a time... :)

**Comment by audoban** [comment] 2017-01-25 20:40
> Two things must be taken into consideration I think:

Also we need define some behaviors for the following situations.

I will write the case with 2 Screens, later we come to define this more generally for more monitors.

- 1. Screen duplicated, 2 screens share the same image with the same resolution.
 Naturally the Dock will be shown on both screens.

- 2. Screen extended, both screens behave as one
Maybe the most complicated, especially when I disconnect a screen because the Dock might disappear.
Also we need carefully when a screen is overlay over another, or when both screen sharing a edge.
We need to ensure that the Dock don't disappear of edge for appear on the edge of the next screen.

- 3. Screen secondary(external), the primary is off and second screen have the desktop.
We need to sure that when I want to back to primary screen, the dock remember your last screen, or remember on that screen was created.

> this containment and dock is not active when I return at home so the configuration concerning this shouldn’t be deleted at any time
> when I am at home this configuration doesn’t have to be loaded

So cool.

> also a garbage collector for screens that arent used any more from the user could be a good idea... This could be a list of all recorded screens and the user could be able to delete from this list any screen that doesnt use any more and there is a specific dock associated with it

Maybe add this feature to config ui?

> notice how often it is mentioned in the article the fact that panel windows outside GNOME is so difficult to handle the wayland situation. Plank I think was first implemented for Budgie.
This makes me think that at some point in the future if we need something from kwin wayland we could jump in and help kwin developers to support our case. I dont think they will be negative...

I also hope that KWin developers be kind to us.

**Comment by psifidotos** [comment] 2017-01-25 22:22
> Screen duplicated, 2 screens share the same image with the same resolution. Naturally the Dock will be shown on both screens.

I think this is semi-automatic. The two screens share the same resolution settings x,y,width,height

> Maybe the most complicated, especially when I disconnect a screen because the Dock might disappear.

if the dock is not set to be on all screens, then the dock shouldn show and also should release resources

>Also we need carefully when a screen is overlay over another, or when both screen sharing a edge.
We need to ensure that the Dock don't disappear of edge for appear on the edge of the next screen.

I think that this is not an issue. Our current architecture of handling edges protects us from this. The two screens have a unified geometry but different x,y start values. 

> Screen secondary(external), the primary is off and second screen have the desktop. We need to sure that when I want to back to primary screen, the dock remember your last screen, or remember on that screen was created.

Containment already provides previous of last screen setting. If i remember correctly in Plasma 5 there is no such thing as a primary screen. When cloning takes place the window I dont think it changes screen even though it shows on both screens

----

Except the above: I dont know if we can provide one dock to be on all screens? Is this feasible? How can this be achieved in screens with different resolutions? for example one screen has resolution 800x600 and the other 1680x1050 how is it going to be shown, where, and how the visibilitymanager will behave? are we going to have for the same containment two different dockViews?

> Maybe add this feature to config ui?

I was thinking the same

> I also hope that KWin developers be kind to us.

I am positive. we ve got the same goal in this

**Comment by psifidotos** [comment] 2017-01-26 13:36
@audoban I also think that I can start experimenting with multi-screen the first weeks of February... I can setup then a multi-screen setup with two screens in order to check all this...

**Comment by audoban** [comment] 2017-01-26 20:01
> Except the above: I dont know if we can provide one dock to be on all screens? Is this feasible? How can this be achieved in screens with different resolutions? for example one screen has resolution 800x600 and the other 1680x1050 how is it going to be shown, where, and how the visibilitymanager will behave? are we going to have for the same containment two different dockViews?

I think that isn't feasible, the feature "add dock" supplies this need. A containment associated to 2 or more DockViews is very complicated, diferents resolutions, taskmanger, filters on taskmanager, control of mask, etc.

**Comment by audoban** [comment] 2017-01-26 20:02
> I also think that I can start experimenting with multi-screen the first weeks of February... I can then setup a multi-screen setup with two screens in order to check all this...

And I too.

**Comment by psifidotos** [comment] 2017-01-26 20:05
> And I too.

Perfect !!! We can confront together the monster !!!

**Comment by audoban** [comment] 2017-01-26 20:13
jeje xD

**Comment by psifidotos** [comment] 2017-01-28 15:30
@audoban I supported maxLength through the configuration window and only inside the containment... The maxLength of dockView can be removed I think...

**Comment by psifidotos** [comment] 2017-01-28 16:27
@audoban one more thing!!! I observed the plasmashell memory consumption!!! it is always under <100Mbyte because I use only Latte for my panels!!!

**Comment by audoban** [comment] 2017-01-28 18:17
@psifidotos well and Latte consumes 60 MB for me. I do not know how much or little.

**Comment by psifidotos** [comment] 2017-01-28 18:23
@audoban I am at 120Mb but this is having 2 docks and the following applets in them:
- activitity pager
- folderview (to show activity's linked files)
- latte plasmoid (of course)
- weather plasmoid
- analog clock
- systray
- change user plasmoid
- apps launcher
- clock plasmoid to show the date

**Comment by audoban** [comment] 2017-01-28 19:21
> @audoban I am at 120Mb

While the user experience is the best, I think it's fine,...

**Comment by psifidotos** [comment] 2017-01-29 07:26
@audoban last commits werent rebased on master before commiting so we again have double history road in master, any problem with this?

**Comment by audoban** [comment] 2017-01-29 08:10
b397576ed92525ecc079c9a8ca13fa3dbab17d85 on this commit? Mm I did not notice.

**Comment by psifidotos** [comment] 2017-01-29 08:13
no prob.. personally just before I do a
- git checkout master
- git merge "mybranch"
- git push origin master

I first try:
- git checkout master
- git pull origin master
if it downloads updates then the "mybranch" must be updated
- git checkout "mybranch"
- git rebase master

ok... no worries...

**Comment by audoban** [comment] 2017-01-29 08:19
@psifidotos  I was going to do a revert but it seems that I can not anymore.

**Comment by psifidotos** [comment] 2017-01-29 08:23
dont worry... next time... ;-) these things happen

**Comment by psifidotos** [comment] 2017-01-31 19:46
@audoban I would like you opinion concerning #113. Currently our panel shadows are drawn inside our window that works correctly for the general Latte user case, that is animating contents and transparency. But if we try to provide also a plasma clone experience e.g. the top dock on the top then in that case snapping can not work correctly in any case. A space between windows and dock occurs when a window reaches near our dock.

I can support this for very specific cases when only the following occur
Always Visible + zoom factor 1.0 + Fill mode

I managed to use the PanelShadows class from plasma source code but in order to achieve this I have to create a special case for dockview for which the dockview size is exactly as the mask size sent by the container.
This special case will occur only when these are happening: Always Visible + zoom factor 1.0 + Fill mode

of course this adds more c++ code and complexity

my opinion is to support it from now in a case we need it also in the future for other cases we might dont even see now

what is your opinion?

**Comment by audoban** [comment] 2017-02-01 05:19
>  I would like you opinion concerning #113. Currently our panel shadows are drawn inside our window that works correctly for the general Latte user case, that is animating contents and transparency. But if we try to provide also a plasma clone experience e.g. the top dock on the top then in that case snapping can not work correctly in any case. A space between windows and dock occurs when a window reaches near our dock.

I don't want to draw shadows with KWIN api, is unfeasible for our case and very complex.
I think that the problem is a wrong calculating of absolute geometry. The snap works with the reserve space(struts), the plasmoid should give to VisibilityManager a geometry without shadows. Because otherwise we would also have the same problem with the PanelShadows that you propose.

The snapping depends on the struts, not the shadow or the contents of the dock.

I keep saying this class PanelShadows will complicate the Dock.

Or you may be wrong, but I don't see it sense to create a class PanelShadows for specific situations.

**Comment by psifidotos** [comment] 2017-02-01 09:26
> I think that the problem is a wrong calculating of absolute geometry. The snap works with the reserve space(struts), the plasmoid should give to VisibilityManager a geometry without shadows. Because otherwise we would also have the same problem with the PanelShadows that you propose.

no it isnt an absolute geometry case, we are not talking about the struts case that defines the screen geometry free space which is used when maximizing a window or dragging a window to screen edges. To observe it you can add a top dock that shows its panel background at maximum and is always visible with zoom factor 1.0. In such case what ever you do if you try to drag a window near our dock then there is always a empty space under our dock #113  except if you drag it with force in order to activate snapping. Another way to observe this is to use the Air theme which has very big shadows, In that case even with the snapping (struts case) you are mentioning there is an issue as the mouse events do not go to underneath windows when you click over the shadows.

So for technological limitations concerning our implementation we have:

1. **regular snapping for windows is not working correctly**
2. **our shadows do not pass through the mouse events to go to underneath windows**

> I don't want to draw shadows with KWIN api, is unfeasible for our case and very complex.

this is not exactly the case. I am not proposing to substitute all the shadows  drawing from direct calls to wayland and x11. I am proposing only for specific cases e.g. when our dock behaves or tries to behave as a regular plasma panel. A very good example for this is a **top dock, always visible, with zoom factor 1.0 and showing its panel background,** .

> The snapping depends on the struts, not the shadow or the contents of the dock.

not in all cases, there are cases that depends only to the window's geometry and not the struts

> I keep saying this class PanelShadows will complicate the Dock.
> Or I'm may be wrong, but I don't see it sense to create a class PanelShadows for specific situations.

I propose to upload the work around this on a branch for review and see how complex dockview becomes. I was afraid the same but in the end it isnt so much work, panelshadows class is just a copy paste from plasma, dependencies for x11,xcb,wayland were added of course (but I believe in the end we will inventual add them either way), the dockview complexity isnt that big...

I aggree that it looks too much drawbacks in order to support the case but on the other hand has a very specific goal to **_make Latte as a central panel manager for all panels_**.

I will keep working on this as I like it in my system and unfortunately without it I dont think we can support properly the top bar paradigm which is very popular in mac, gnome, unity.
We can stay of course in the central goal of the project and say to the users that for the top bar paradigm or for shadows that leave the mouse events to pass through you should only use plasma panels.

**Comment by psifidotos** [comment] 2017-02-01 23:05
@audoban  concerning the above you can try **_snapping_** branch.
it contains the fix for the gap and snapping that was mentioned. 
To compile it you need also x11, xcb and kwayland development packages

it works only for docks that the user has set: 
**Always Visible, zoom factor:1.0, maximum panel size, Justify alignment**

try a theme with very big shadows to see its magic e.g. air theme...

**Comment by audoban** [comment] 2017-02-02 23:54
I'm testing with arc theme and below configuration, but I have a free space between the window and the Dock 
*Always Visible, zoom factor:1.0, maximum panel size, Justify alignment, 32px icon, arc theme*
 and also happen with all locations and alignments.

**Comment by audoban** [comment] 2017-02-03 00:18
> I'm testing with arc theme and below configuration, but I have a free space between the window and the Dock
Always Visible, zoom factor:1.0, maximum panel size, Justify alignment, 32px icon, arc theme
and also happen with all locations and alignments.

False alarm. The background were isn't full

I'm going to add one more use to that class.

**Comment by audoban** [comment] 2017-02-03 00:38
However I am not convinced with this feature.
eg: My size icon is 32px, then the max background thickness is 38px, but if I setting the background thickness to 36, appear a free space between the window and the Dock.

I propose apply the shadow of KWIN when background thickness is major or equal to icon Size

**Comment by psifidotos** [comment] 2017-02-03 16:56
@audoban ok I uploaded the commit to check if you want...

**Comment by audoban** [comment] 2017-02-03 17:14
@psifidotos ok, I will check.

**Comment by audoban** [comment] 2017-02-03 17:22
@psifidotos better but AlwaysVisible is broken.
Start an application from Dock, note that when it bounce, the struts change it's geometry

**Comment by psifidotos** [comment] 2017-02-03 17:40
> Start an application from Dock and note that when it bounce, the struts change it's geometry

when? for external shadows we need zoom factor 0% , what bounce?

**Comment by psifidotos** [comment] 2017-02-08 18:59
@audoban a crash was discovered when the screen geometry is changed, more infos at #154 . Thankfully the user reported the backtrace correctly, I uploaded the fix but I dont know why it is working!!! :)

if you know why, please inform me!!! :)

**Comment by audoban** [comment] 2017-02-11 04:15
Thanks @psifidotos, maybe is fault Qt::QueuedConnection, this connection isn't direct. The event loop decides when call the slot.

```
The slot is invoked when control returns to the event loop of the receiver's thread. The slot is executed in the receiver's thread.
```

**Closed** 2017-04-23 00:00 UTC
Labels: community
